.TH XEUPHORIC 1 @{SELF_DATE} "Xeuphoric @{VERSION}"
.\"
.\"	OO - synopsis item for optional option with no argument
.\"
.de OO
[\\fB\\-\\$1\\fP]
..
.SH NAME
xeuphoric \- an Oric emulator
.SH SYNOPSIS
.B xeuphoric \-\-help
.br
.B xeuphoric \-\-version
.br
.B xeuphoric
[\fB\-1\fP|\fBa\fP|\fBt\fP]
[\fB\-djJpQrg\fP]
[\fB\-A\fP \fIfile\fP]
[\fB\-s\fP \fInum\fP]
[\fB\-S\fP \fBarts\fP|\fBauto\fP|\fBoss\fP]
[\fB\-X\fP \fBalways\fP|\fBauto\fP|\fBnever\fP]
[\fB\-z\fP \fInum\fP]
.RI [ file \ ...]
.SH DESCRIPTION
xeuphoric is a port to SDL of Euphoric, Fabrice Francès' Oric emulator.
It emulates the Oric-1, the Oric Atmos and the Telestrat.
This version is based on Euphoric 0.99b, which was the most recent source
available at the time.
.PP
The original documentation of Euphoric 0.99b is in \fBdoc/euphoric-0.99b\fP.
.SS Differences with Euphoric 0.99b
.IP \(bu 3
There is no \fBoriclite\fP target.
.IP \(bu 3
The keyboard handling code is different.
The new code only implements raw mode.
The so-called ASCII mode has been removed.
.IP \(bu 3
The video emulation code is different.
In this version, the 60 Hz attribute is ignored.
.IP \(bu 3
There is a man page.
.IP \(bu 3
The distribution archive is source code, not binaries.
.IP \(bu 3
The distribution archive is in tar format, not zip format.
The name of the archive includes the version number.
When extracted, it creates a directory including the version number.
.IP \(bu 3
[\fBprtsc\fP] is disabled.
It's replaced by [\fBf12\fP], which writes a screenshot in PPM format.
.IP \(bu 3
Joystick handling is disabled.
.IP \(bu 3
The command line is now parsed with \fBgetopt\fP(3).
Syntax errors in command line do not cause the usage to be printed anymore.
.IP \(bu 3
The \fB\-tj\fP option has been renamed \fB\-J\fP.
.IP \(bu 3
Error messages are printed to standard error instead of standard output.
They now include strerror(errno) if relevant.
Numerous fixes in host.c error messages.
.IP \(bu 3
New options \fB\-\-help\fP and \fB\-\-version\fP.
.IP \(bu 3
New option \fB\-A\fP, to disable audio output or write it to file.
.IP \(bu 3
New option \fB\-g\fP, to enable GTK2/Glade2 debugger
.IP \(bu 3
The config files and ROM files are now dealt with so that you can run Xeuphoric
from any directory without having to set the \fBORIC\fP environment variable
(which
has been removed).
.IP \(bu 3
Tape emulation has been changed to favour lower-case file names on the host and
a \fB.tap\fP extension.
\fBCLOAD\fP still supports file names in all caps and/or without an extension
for compatibility.
.SH OPTIONS
If the first argument is \fB\-\-help\fP, Xeuphoric prints a usage message on
standard output and exits successfully.
.PP
If the first argument is \fB\-\-version\fP, Xeuphoric prints its version number
on standard output and exits successfully.
.PP
Otherwise, the command line is parsed with \fBgetopt\fP(3).
.SS Machine to emulate
.TP
.B \-1
Emulate an Oric-1.
\fB\-1\fP and \fB\-at\fP are mutually exclusive.
.TP
.B \-a
Emulate an Oric Atmos.
This is the default.
\fB\-a\fP, \fB\-1t\fP are mutually exclusive.
.TP
.B \-t
Emulate a Telestrat.
Telestrat emulation implies 6551 emulation which requires (1) the
\fBioperm\fP(2) system call and (2) super-user privileges (i.e. you must be
logged in as \fBroot\fP or make the xeuphoric executable setuid \fBroot\fP).
Failing either of the above, Xeuphoric will run with 6551 emulation disabled.
\fB\-t\fP and \fB\-1adj\fP are mutually exclusive.
.SS Peripherals to emulate
.TP
.B \-d
Emulate a Microdisc.
\fB\-d\fP and \fB\-t\fP are mutually exclusive.
.TP
.B \-j
Emulate a Jasmin.
\fB\-j\fP and \fB\-t\fP are mutually exclusive.
.TP
.B \-J
Emulate a Telestrat joystick.
This used to be \fB\-tj\fP in Euphoric.
\fB\-J\fP and \fB\-1a\fP are mutually exclusive.
.TP
.B \-p
Emulate a P.A.S.E. joystick interface.
.SS Audio
.TP
.BI \-A \ file
With the OSS output method, write audio to \fIfile\fP.
\fIfile\fP is assumed to be an OSS dsp device.
It is configured to 8-bit unsigned mono PCM at 25600 Hz.
.PP
.RS
If the configuration ioctl()s fail, which probably means that \fIfile\fP is not
an OSS dsp device, a warning is printed but audio output is written to it
anyway.
You can take advantage of this to save the audio output to file.
Note that for this to work, \fIfile\fP \fImust\fP already exist.
E.G.: \fBtouch audio.raw && xeuphoric -Aaudio.raw\fP.
Likewise, you can disable audio output, by using \fB\-A/dev/null\fP.
.PP
By default, \fB/dev/dsp\fP is used.
.RE
.TP
\fB\-S arts\fP|\fBauto\fP|\fBoss\fP
Sound output method.
.RS
.TP
.B arts
Only try libarts (or abort if compiled without libarts support).
.TP
.B auto
Try libarts first and fall back on OSS.
It's the default.
.TP
.B oss
Only try OSS (or abort if compiled without OSS support).
.RE
.SS Video
.TP
\fB\-X\fP \fBalways\fP|\fBauto\fP|\fBnever\fP
XShm usage.
.RS
.TP
.B always
Always use XShm; if compiled without XShm support or XShm is not available at
run-time, abort.
.TP
.B auto
Use XShm if it's available and fall back on regular XImages otherwise.
It's the default.
.TP
.B never
Don't use XShm, even if it's available.
.RE
.TP
.BI \-z \ num
Set the zoom factor to \fInum\fP.
Allowed values are 1, 2 and 3.
The default is 1.
.SS Miscellaneous
.TP
.B \-Q
Quit on illegal instructions (the default is to hang).
.TP
.B \-r
Restart from a dump.
.TP
.BI \-s \ num
Set the speed index to \fInum\fP percent of an actual Oric.
The default is 100.
.SH VIDEO OUTPUT
The video part of the ULA is emulated into a 240\(mu224 window (times the zoom
factor).
The emulation is believed to be accurate for most uses except for the 60-Hz
attributes which is ignored.
.PP
Uses that rely on microscopic (sub-frame) timing characteristics won't be
emulated properly.
In particular, while the video output of the real Oric is interlaced, Xeuphoric
displays both odd and even lines on every frame.
The frame rate is also slightly off (20000 cycles instead of 19968).
Another potential cause of incompatibilities is that while the real ULA renders
the display little by little, Xeuphoric renders it all at once from a snapshot
of the video RAM.
.PP
On greyscale displays, Xeuphoric does not attempt to weight the components, as
the most common X server implementation (XFree86) appears to do that already.
If you have problems distinguishing Oric colours on your display, let me know
about it.
.SH SOUND OUTPUT
Xeuphoric emulates the 8912 by generating a mono PCM stream at 25600 Hz in
8-bit unsigned format.
See the \fB\-A\fP option for further details.
.PP
The sound quality is lousy, probably because of the single-threaded nature of
Xeuphoric.
.SH PRINTER OUTPUT
FIXME - to be written
.SH KEYBOARD INPUT
Xeuphoric maps one physical key of the host to exactly one physical key of the
Oric.
Any keymap that may exist on the host is cheerfully ignored.
In particular, if you have an AZERTY keyboard and you press the key labelled
[\fBa\fP] on your physical keyboard, the virtual Oric thinks you have pressed
the [\fBq\fP] key on its virtual keyboard.
Note that more than one host key may be mapped to the same Oric key.
.PP
Here's a list of Oric keys along with the names of the PC keys that are mapped
to them.
The host key names in the listing assume US layout.
.PP
.ta 10 28 38
Oric key	Host key	Oric key	Host key
.br
[\fB'\fP]	[\fB'\fP]	[\fBf\fP]	[\fBf\fP]
.br
[\fB,\fP]	[\fB,\fP]	[\fBg\fP]	[\fBg\fP]
.br
[\fB-\fP]	[\fB-\fP]	[\fBh\fP]	[\fBh\fP]
.br
[\fB.\fP]	[\fB.\fP]	[\fBi\fP]	[\fBi\fP]
.br
[\fB/\fP]	[\fB/\fP]	[\fBj\fP]	[\fBj\fP]
.br
[\fB0\fP]	[\fB0\fP]	[\fBk\fP]	[\fBk\fP]
.br
[\fB1\fP]	[\fB1\fP]	[\fBl\fP]	[\fBl\fP]
.br
[\fB2\fP]	[\fB2\fP]	[\fBle\fP]	[\fBlctrl\fP], [\fBleft\fP]
.br
[\fB3\fP]	[\fB3\fP]	[\fBlshift\fP]	[\fB<\fP], [\fBlshift\fP]
.br
[\fB4\fP]	[\fB4\fP]	[\fBm\fP]	[\fBm\fP]
.br
[\fB5\fP]	[\fB5\fP]	[\fBn\fP]	[\fBn\fP]
.br
[\fB6\fP]	[\fB6\fP]	[\fBo\fP]	[\fBo\fP]
.br
[\fB7\fP]	[\fB7\fP]	[\fBp\fP]	[\fBp\fP]
.br
[\fB8\fP]	[\fB8\fP]	[\fBq\fP]	[\fBq\fP]
.br
[\fB9\fP]	[\fB9\fP]	[\fBr\fP]	[\fBr\fP]
.br
[\fB;\fP]	[\fB;\fP]	[\fBreturn\fP]	[\fBenter\fP]
.br
[\fB=\fP]	[\fB=\fP]	[\fBright\fP]	[\fBright\fP], [\fBrctrl\fP]
.br
[\fB[\fP]	[\fB[\fP]	[\fBrshift\fP]	[\fBrshift\fP]
.br
[\fB\\\fP]	[\fB\\\fP]	[\fBs\fP]	[\fBs\fP]
.br
[\fB]\fP]	[\fB]\fP]	[\fBspace\fP]	[\fBspace\fP]
.br
[\fBa\fP]	[\fBa\fP]	[\fBt\fP]	[\fBt\fP]
.br
[\fBb\fP]	[\fBb\fP]	[\fBu\fP]	[\fBu\fP]
.br
[\fBc\fP]	[\fBc\fP]	[\fBup\fP]	[\fBup\fP], [\fBralt\fP]
.br
[\fBctrl\fP]	[\fBcapslk\fP]	[\fBv\fP]	[\fBv\fP]
.br
[\fBd\fP]	[\fBd\fP]	[\fBw\fP]	[\fBw\fP]
.br
[\fBdel\fP]	[\fBbacksp\fP]	[\fBx\fP]	[\fBx\fP]
.br
[\fBdown\fP]	[\fBdown\fP], [\fBlalt\fP]	[\fBy\fP]	[\fBy\fP]
.br
[\fBe\fP]	[\fBe\fP]	[\fBz\fP]	[\fBz\fP]
.br
[\fBesc\fP]	[\fBtab\fP]
.br
.ta 5
.SH JOYSTICK INPUT
FIXME - to be written
.SH CASSETTE I/O
All cassette I/O is emulated via files on the host.
There are two emulation modes, physical and logical.
See the Euphoric documentation for a description of the physical mode and how
to activate it.
.PP
In logical mode, the Oric ROM is patched to use host files.
read-sync (E696h/E735h) is patched to locate the host file and open it in
read-only mode.
read-byte (E630h/E6C9h) is patched to read a character from the file opened by
read-sync.
write-sync (E6BAh/E75Ah) is patched to compute the name of the host file, open
it for writing, and write the \fB.tap\fP header.
write-byte (E5C6h/E65Eh) is patched to write a character to the file opened by
write-sync.
.SS CSAVE
The \fBCSAVE\fP command is patched to take its argument, lower-case it, append
\fB.tap\fP and use that as a host file name.
If you leave out the argument (\fBCSAVE ""\fP), the host file is
\fB________.tap\fP (eight underscores).
.PP
There is no way to save to a file whose name contains upper case or non-ASCII
characters or doesn't have the \fB.tap\fP extension.
.PP
The host file is opened in truncate mode.
However, the second and subsequent times you \fBCSAVE""\fP, the host file is
opened in append mode, even if you \fBCSAVE""\fP to other files in between.
For example,
.PP
.RS
.ta 20
.nf
\fBCSAVE"/TMP/FOO"\fP	overwrite \fB/tmp/foo.tap\fP
\fBCSAVE""\fP	overwrite \fB________.tap\fP
\fBCSAVE"/TMP/FOO"\fP	overwrite \fB/tmp/foo.tap\fP
\fBCSAVE""\fP	append to \fB________.tap\fP
.fi
.ta 5
.RE
.PP
If the host file can't be opened, a diagnostic is printed to standard error.
If running in Atmos mode, 02B1h is also incremented.
Warning: write errors are \fInot\fP detected.
Consider this a bug.
.SS CLOAD
There exist a significant number of .tap files that don't follow the same
naming conventions as Xeuphoric (all-caps names, no extension, extensions other
than \fB.tap\fP).
\fBCLOAD\fP attempts to be compatible with both \fBCSAVE\fP and the more
creatively named files out there by trying several host file names in
sequence\ :
.RS 2
.IP #1 4
The name formed by lower-casing the argument and appending \fB.tap\fP.
.IP #2 4
The name formed by appending \fB.TAP\fP to the argument.
.IP #3 4
The name formed by lower-casing the argument.
.IP #4 4
The argument.
.RE
.PP
For each name, Xeuphoric attempts to open the named file.
If that succeeds, we've got a winner.
If that fails with error \fBENOENT\fP ("No such file or directory"), it goes on
to the next name.
If that fails for any other reason, it prints an error message and returns to
the first name.
.PP
If all file names are exhausted, Xeuphoric returns to the first name.
Thus the algorithm loops until a name is successfully opened or \fBCLOAD\fP is
interrupted by NMI.
.PP
Leaving the argument out (\fBCLOAD ""\fP) is equivalent to providing an
argument of \fB________\fP (eight underscores).
.PP
For example, here are two \fBCLOAD\fP commands along with the file names that
would be used:
.TP
\fBCLOAD "/TMP/FOO"\fP
\fB/tmp/foo.tap\fP
.br
\fB/TMP/FOO.TAP\fP
.br
\fB/tmp/foo\fP
.br
\fB/TMP/FOO\fP
.TP
\fBCLOAD ""\fP
\fB________.tap\fP
.br
\fB________.TAP\fP
.br
\fB________\fP
.RE
.SS Tape files
A tape file begins with the three-byte sequence 16h 16h 16h, normally followed
by 24h.
.SH HOT KEYS
The following keys are special to Xeuphoric:
.TP
.RB [ f1 ]
Switch between the emulation and the setup screen.
.TP
.RB [ f2 ]
Toggle the sound (disabled).
.TP
.RB [ f4 ]
Double the emulation clock frequency (or reset it to the nominal value if it
was below it).
You can go as high as your hardware will allow, up to 65,536\ MHz.
.TP
.RB [ f5 ]
Halve the emulation clock frequency (or reset it to the nominal value if it was
above it).
You can go as low as you want as long as the number of cycles per frame is an
integer.
With the current value of 20,000 cycles per frame, the minimum clock frequency
is 31.25\ kHz.
.TP
.RB [ f6 ]
Jasmin boot.
.TP
.RB [ f7 ]
Warm reset (NMI).
.TP
.RB [ f8 ]
Cold reset (RES)
.TP
.RB [ f9 ]
Dump and quit.
.TP
.RB [ f10 ]
Quit.
.TP
.RB [ f12 ]
Writes a screenshot in packed PPM format as \fBxeuphoric_%03u.ppm\fP.
.SH FILES
Xeuphoric attempts to parse all the following config files in order:
.PP
.RS
@{RCFILES}
.RE
.PP
Xeuphoric does not stop at the first match\ ; if all three files exist, they're
all parsed.
Thus you can set defaults for all the parameters in the system-wide config
file.
Users inherit those settings but can override some or all of them from their
personal config files.
Likewise, it's possible to override parameters on a per-directory basis by
creating a \fB.xeuphoricrc\fP file in that directory.
For example, if \fB~/o1\fP contains an Oric-1 project you are working on, you
can make Xeuphoric start in Oric-1 mode by default in that directory by typing
\fBecho Computer=Oric1 >~/o1/.xeuphoricrc\fP.
.PP
The ROM files are searched for in the following directories:
.PP
.RS
@{DATAPATH}
.RE
.PP
For a given file, the first match found is used.
For example, it's possible to use an alternative ROM file for a project by
putting a copy of that file in the directory where the project resides.
.SH ENVIRONMENT
.TP
.B DISPLAY
The name of the X server to connect to.
.TP
.B HOME
Used to locate config files and ROM files.
.SH EXIT STATUS
\fB0\fP	OK
.br
\fB>0\fP	An error occurred
.SH BUGS
See \fBTODO\fP.
.SH AUTHOR
André Majorel <URL:http://www.teaser.fr/~amajorel/>
.PP
Contributions by Jede <URL:http://www.oric.org/>
.PP
Euphoric was written by Fabrice Francès
<URL:http://homepage.ensica.fr/~frances/>
.SH LEGAL
\fBatmos.rom\fP, \fBmicrodisc.rom\fP and \fBoric1.rom\fP are copyright 1983
Tangerine.
Tangerine is defunct.
We don't know who the current assignee of the copyright is (if any).
.PP
\fBhyperbasic.rom\fP, \fBteleass.rom\fP, \fBtelematic.rom\fP and
\fBtelemon-2.4.rom\fP are copyright Oric International.
Oric International is defunct.
We don't know who the current assignee of the copyright is (if any).
.PP
\fBjasmin.rom\fP is copyright Technologie Recherche et Applications Nouvelles.
As far as I know, T.R.A.N. doesn't exist anymore.
We don't know who the current assignee of the copyright is (if any).
.PP
Euphoric 0.99b is copyright Fabrice Francès 1994-1997 and available under the
terms of version 2 of the GNU General Public License.
.PP
The rest is copyright André Majorel 2000-2004 and available under the terms of
version 2 of the GNU General Public License.
.SH SEE ALSO
<URL:http://oric.free.fr/emulator.html>
.br
.BR ppm (5)
