; Events generated by Arkos Tracker 2.

Events
	.word 865	; Wait for 864 frames.
	.byt 0

Events_Loop
	.word 1729	; Wait for 1728 frames.
	.byt 0

	.word 0	; End of sequence.
	.word Events_Loop	; Loops here.
