; Song Encounter IntroA, in AKY version 1.0, generated by Arkos Tracker 2.

Subsong0
Subsong0DisarkGenerateExternalLabel

; Header
Subsong0DisarkByteRegionStart0
	.byt 128	; Format version: 0 and endianness: little-endian.
	.byt 3	; How many channels are encoded.
; Frequency of the PSG index 0: 1000000Hz.
	.byt 64, 66, 15, 0
Subsong0DisarkByteRegionEnd0

Subsong0_Linker
Subsong0DisarkPointerRegionStart1
; Pattern 0
Subsong0_LinkerLoop	; Loops here.
Subsong0DisarkWordForceNonReference2
	.word 256	; Duration in frames.
	.word Subsong0_Track_0
	.word Subsong0_Track_1
	.word Subsong0_Track_2

Subsong0DisarkWordForceNonReference3
	.word 0	; Loops (duration = 0).
	.word Subsong0_LinkerLoop
Subsong0DisarkPointerRegionEnd1

; The tracks.
Subsong0_Track_0
Subsong0DisarkByteRegionStart4
	.byt 255	; Duration.
Subsong0DisarkByteRegionEnd4
Subsong0DisarkPointerRegionStart5
	.word Subsong0_RegisterBlock_0
Subsong0DisarkPointerRegionEnd5

Subsong0DisarkByteRegionStart6
	.byt 1	; Duration.
Subsong0DisarkByteRegionEnd6
Subsong0DisarkPointerRegionStart7
	.word Subsong0_RegisterBlock_0
Subsong0DisarkPointerRegionEnd7

Subsong0_Track_1
Subsong0DisarkByteRegionStart8
	.byt 64	; Duration.
Subsong0DisarkByteRegionEnd8
Subsong0DisarkPointerRegionStart9
	.word Subsong0_RegisterBlock_3
Subsong0DisarkPointerRegionEnd9

Subsong0DisarkByteRegionStart10
	.byt 64	; Duration.
Subsong0DisarkByteRegionEnd10
Subsong0DisarkPointerRegionStart11
	.word Subsong0_RegisterBlock_4
Subsong0DisarkPointerRegionEnd11

Subsong0DisarkByteRegionStart12
	.byt 64	; Duration.
Subsong0DisarkByteRegionEnd12
Subsong0DisarkPointerRegionStart13
	.word Subsong0_RegisterBlock_5
Subsong0DisarkPointerRegionEnd13

Subsong0DisarkByteRegionStart14
	.byt 32	; Duration.
Subsong0DisarkByteRegionEnd14
Subsong0DisarkPointerRegionStart15
	.word Subsong0_RegisterBlock_6
Subsong0DisarkPointerRegionEnd15

Subsong0DisarkByteRegionStart16
	.byt 32	; Duration.
Subsong0DisarkByteRegionEnd16
Subsong0DisarkPointerRegionStart17
	.word Subsong0_RegisterBlock_5
Subsong0DisarkPointerRegionEnd17

Subsong0_Track_2
Subsong0DisarkByteRegionStart18
	.byt 8	; Duration.
Subsong0DisarkByteRegionEnd18
Subsong0DisarkPointerRegionStart19
	.word Subsong0_RegisterBlock_10
Subsong0DisarkPointerRegionEnd19

Subsong0DisarkByteRegionStart20
	.byt 16	; Duration.
Subsong0DisarkByteRegionEnd20
Subsong0DisarkPointerRegionStart21
	.word Subsong0_RegisterBlock_10
Subsong0DisarkPointerRegionEnd21

Subsong0DisarkByteRegionStart22
	.byt 8	; Duration.
Subsong0DisarkByteRegionEnd22
Subsong0DisarkPointerRegionStart23
	.word Subsong0_RegisterBlock_10
Subsong0DisarkPointerRegionEnd23

Subsong0DisarkByteRegionStart24
	.byt 16	; Duration.
Subsong0DisarkByteRegionEnd24
Subsong0DisarkPointerRegionStart25
	.word Subsong0_RegisterBlock_10
Subsong0DisarkPointerRegionEnd25

Subsong0DisarkByteRegionStart26
	.byt 8	; Duration.
Subsong0DisarkByteRegionEnd26
Subsong0DisarkPointerRegionStart27
	.word Subsong0_RegisterBlock_10
Subsong0DisarkPointerRegionEnd27

Subsong0DisarkByteRegionStart28
	.byt 8	; Duration.
Subsong0DisarkByteRegionEnd28
Subsong0DisarkPointerRegionStart29
	.word Subsong0_RegisterBlock_10
Subsong0DisarkPointerRegionEnd29

Subsong0DisarkByteRegionStart30
	.byt 8	; Duration.
Subsong0DisarkByteRegionEnd30
Subsong0DisarkPointerRegionStart31
	.word Subsong0_RegisterBlock_10
Subsong0DisarkPointerRegionEnd31

Subsong0DisarkByteRegionStart32
	.byt 16	; Duration.
Subsong0DisarkByteRegionEnd32
Subsong0DisarkPointerRegionStart33
	.word Subsong0_RegisterBlock_10
Subsong0DisarkPointerRegionEnd33

Subsong0DisarkByteRegionStart34
	.byt 8	; Duration.
Subsong0DisarkByteRegionEnd34
Subsong0DisarkPointerRegionStart35
	.word Subsong0_RegisterBlock_10
Subsong0DisarkPointerRegionEnd35

Subsong0DisarkByteRegionStart36
	.byt 16	; Duration.
Subsong0DisarkByteRegionEnd36
Subsong0DisarkPointerRegionStart37
	.word Subsong0_RegisterBlock_10
Subsong0DisarkPointerRegionEnd37

Subsong0DisarkByteRegionStart38
	.byt 8	; Duration.
Subsong0DisarkByteRegionEnd38
Subsong0DisarkPointerRegionStart39
	.word Subsong0_RegisterBlock_10
Subsong0DisarkPointerRegionEnd39

Subsong0DisarkByteRegionStart40
	.byt 8	; Duration.
Subsong0DisarkByteRegionEnd40
Subsong0DisarkPointerRegionStart41
	.word Subsong0_RegisterBlock_10
Subsong0DisarkPointerRegionEnd41

Subsong0DisarkByteRegionStart42
	.byt 8	; Duration.
Subsong0DisarkByteRegionEnd42
Subsong0DisarkPointerRegionStart43
	.word Subsong0_RegisterBlock_22
Subsong0DisarkPointerRegionEnd43

Subsong0DisarkByteRegionStart44
	.byt 16	; Duration.
Subsong0DisarkByteRegionEnd44
Subsong0DisarkPointerRegionStart45
	.word Subsong0_RegisterBlock_22
Subsong0DisarkPointerRegionEnd45

Subsong0DisarkByteRegionStart46
	.byt 8	; Duration.
Subsong0DisarkByteRegionEnd46
Subsong0DisarkPointerRegionStart47
	.word Subsong0_RegisterBlock_22
Subsong0DisarkPointerRegionEnd47

Subsong0DisarkByteRegionStart48
	.byt 16	; Duration.
Subsong0DisarkByteRegionEnd48
Subsong0DisarkPointerRegionStart49
	.word Subsong0_RegisterBlock_22
Subsong0DisarkPointerRegionEnd49

Subsong0DisarkByteRegionStart50
	.byt 8	; Duration.
Subsong0DisarkByteRegionEnd50
Subsong0DisarkPointerRegionStart51
	.word Subsong0_RegisterBlock_22
Subsong0DisarkPointerRegionEnd51

Subsong0DisarkByteRegionStart52
	.byt 8	; Duration.
Subsong0DisarkByteRegionEnd52
Subsong0DisarkPointerRegionStart53
	.word Subsong0_RegisterBlock_22
Subsong0DisarkPointerRegionEnd53

Subsong0DisarkByteRegionStart54
	.byt 8	; Duration.
Subsong0DisarkByteRegionEnd54
Subsong0DisarkPointerRegionStart55
	.word Subsong0_RegisterBlock_22
Subsong0DisarkPointerRegionEnd55

Subsong0DisarkByteRegionStart56
	.byt 16	; Duration.
Subsong0DisarkByteRegionEnd56
Subsong0DisarkPointerRegionStart57
	.word Subsong0_RegisterBlock_22
Subsong0DisarkPointerRegionEnd57

Subsong0DisarkByteRegionStart58
	.byt 8	; Duration.
Subsong0DisarkByteRegionEnd58
Subsong0DisarkPointerRegionStart59
	.word Subsong0_RegisterBlock_22
Subsong0DisarkPointerRegionEnd59

Subsong0DisarkByteRegionStart60
	.byt 16	; Duration.
Subsong0DisarkByteRegionEnd60
Subsong0DisarkPointerRegionStart61
	.word Subsong0_RegisterBlock_22
Subsong0DisarkPointerRegionEnd61

Subsong0DisarkByteRegionStart62
	.byt 8	; Duration.
Subsong0DisarkByteRegionEnd62
Subsong0DisarkPointerRegionStart63
	.word Subsong0_RegisterBlock_22
Subsong0DisarkPointerRegionEnd63

Subsong0DisarkByteRegionStart64
	.byt 8	; Duration.
Subsong0DisarkByteRegionEnd64
Subsong0DisarkPointerRegionStart65
	.word Subsong0_RegisterBlock_22
Subsong0DisarkPointerRegionEnd65


; The RegisterBlocks.
Subsong0DisarkByteRegionStart66
Subsong0_RegisterBlock_0
	.byt 0	; Initial State: no software, no hardware.

Subsong0_RegisterBlock_0_Loop
	.byt 4	; Non-initial State, no software no hardware.

	.byt 8	; Loop to index 1.
Subsong0DisarkPointerRegionStart67
	.word Subsong0_RegisterBlock_0_Loop
Subsong0DisarkPointerRegionEnd67


Subsong0_RegisterBlock_3
	.byt 89	; Initial State: software only.
	.byt 239, 0	; Software period.

	.byt 41	; Non-initial State, software only.

	.byt 229	; Non-initial State, software only.
	.byt 28	; New LSB for software period.
	.byt 1	; New MSB for software period, maybe with noise.

	.byt 33	; Non-initial State, software only.

Subsong0_RegisterBlock_3_Loop
	.byt 93	; Non-initial State, software only.
	.byt 102	; New LSB for software period.

	.byt 33	; Non-initial State, software only.

	.byt 221	; Non-initial State, software only.
	.byt 239	; New LSB for software period.
	.byt 0	; New MSB for software period, maybe with noise.

	.byt 33	; Non-initial State, software only.

	.byt 221	; Non-initial State, software only.
	.byt 28	; New LSB for software period.
	.byt 1	; New MSB for software period, maybe with noise.

	.byt 33	; Non-initial State, software only.

	.byt 8	; Loop to index 4.
Subsong0DisarkPointerRegionStart68
	.word Subsong0_RegisterBlock_3_Loop
Subsong0DisarkPointerRegionEnd68


Subsong0_RegisterBlock_4
	.byt 89	; Initial State: software only.
	.byt 239, 0	; Software period.

	.byt 41	; Non-initial State, software only.

	.byt 229	; Non-initial State, software only.
	.byt 63	; New LSB for software period.
	.byt 1	; New MSB for software period, maybe with noise.

	.byt 33	; Non-initial State, software only.

Subsong0_RegisterBlock_4_Loop
	.byt 93	; Non-initial State, software only.
	.byt 123	; New LSB for software period.

	.byt 33	; Non-initial State, software only.

	.byt 221	; Non-initial State, software only.
	.byt 239	; New LSB for software period.
	.byt 0	; New MSB for software period, maybe with noise.

	.byt 33	; Non-initial State, software only.

	.byt 221	; Non-initial State, software only.
	.byt 63	; New LSB for software period.
	.byt 1	; New MSB for software period, maybe with noise.

	.byt 33	; Non-initial State, software only.

	.byt 8	; Loop to index 4.
Subsong0DisarkPointerRegionStart69
	.word Subsong0_RegisterBlock_4_Loop
Subsong0DisarkPointerRegionEnd69


Subsong0_RegisterBlock_5
	.byt 89	; Initial State: software only.
	.byt 213, 0	; Software period.

	.byt 41	; Non-initial State, software only.

	.byt 101	; Non-initial State, software only.
	.byt 253	; New LSB for software period.

	.byt 33	; Non-initial State, software only.

Subsong0_RegisterBlock_5_Loop
	.byt 221	; Non-initial State, software only.
	.byt 63	; New LSB for software period.
	.byt 1	; New MSB for software period, maybe with noise.

	.byt 33	; Non-initial State, software only.

	.byt 221	; Non-initial State, software only.
	.byt 213	; New LSB for software period.
	.byt 0	; New MSB for software period, maybe with noise.

	.byt 33	; Non-initial State, software only.

	.byt 93	; Non-initial State, software only.
	.byt 253	; New LSB for software period.

	.byt 33	; Non-initial State, software only.

	.byt 8	; Loop to index 4.
Subsong0DisarkPointerRegionStart70
	.word Subsong0_RegisterBlock_5_Loop
Subsong0DisarkPointerRegionEnd70


Subsong0_RegisterBlock_6
	.byt 89	; Initial State: software only.
	.byt 190, 0	; Software period.

	.byt 41	; Non-initial State, software only.

	.byt 101	; Non-initial State, software only.
	.byt 253	; New LSB for software period.

	.byt 33	; Non-initial State, software only.

	.byt 221	; Non-initial State, software only.
	.byt 63	; New LSB for software period.
	.byt 1	; New MSB for software period, maybe with noise.

	.byt 33	; Non-initial State, software only.

	.byt 221	; Non-initial State, software only.
	.byt 190	; New LSB for software period.
	.byt 0	; New MSB for software period, maybe with noise.

	.byt 33	; Non-initial State, software only.

Subsong0_RegisterBlock_6_Loop
	.byt 93	; Non-initial State, software only.
	.byt 253	; New LSB for software period.

	.byt 33	; Non-initial State, software only.

	.byt 221	; Non-initial State, software only.
	.byt 63	; New LSB for software period.
	.byt 1	; New MSB for software period, maybe with noise.

	.byt 33	; Non-initial State, software only.

	.byt 221	; Non-initial State, software only.
	.byt 190	; New LSB for software period.
	.byt 0	; New MSB for software period, maybe with noise.

	.byt 33	; Non-initial State, software only.

	.byt 8	; Loop to index 8.
Subsong0DisarkPointerRegionStart71
	.word Subsong0_RegisterBlock_6_Loop
Subsong0DisarkPointerRegionEnd71


Subsong0_RegisterBlock_10
	.byt 89	; Initial State: software only.
	.byt 204, 2	; Software period.

	.byt 41	; Non-initial State, software only.

	.byt 37	; Non-initial State, software only.

	.byt 33	; Non-initial State, software only.

Subsong0_RegisterBlock_10_Loop
	.byt 29	; Non-initial State, software only.

	.byt 8	; Loop to index 4.
Subsong0DisarkPointerRegionStart72
	.word Subsong0_RegisterBlock_10_Loop
Subsong0DisarkPointerRegionEnd72


Subsong0_RegisterBlock_22
	.byt 89	; Initial State: software only.
	.byt 126, 2	; Software period.

	.byt 8
Subsong0DisarkPointerRegionStart73
	.word Subsong0_RegisterBlock_10 + 3	; Optimization: goto common Block at index 1.
Subsong0DisarkPointerRegionEnd73

Subsong0_RegisterBlock_9
	.byt 89	; Initial State: software only.
	.byt 204, 2	; Software period.

	.byt 8
Subsong0DisarkPointerRegionStart74
	.word Subsong0_RegisterBlock_10 + 3	; Optimization: goto common Block at index 1.
Subsong0DisarkPointerRegionEnd74

Subsong0_RegisterBlock_21
	.byt 89	; Initial State: software only.
	.byt 126, 2	; Software period.

	.byt 8
Subsong0DisarkPointerRegionStart75
	.word Subsong0_RegisterBlock_10 + 3	; Optimization: goto common Block at index 1.
Subsong0DisarkPointerRegionEnd75

Subsong0DisarkByteRegionEnd66
