@ECHO OFF

::
:: Set the build paremeters
::
SET OSDKLINK=-B
SET OSDKADDR=$500
SET OSDKNAME=TAPERIPPER
SET OSDKFILE=asm
SET OSDKDISK=TapeRipper
SET OSDKINIST=CLS:MENU
SET OSDKTAP2DSKPARAMS=build\menu.tap
SET OSDKTAPNAME=RIPTAP

