#AFLAGS  = /m2 /mx /z /zi /t /jMASM51 /jQUIRKS
#LFLAGS = SYSTEM dos4g OPTION CASEEXACT OPTION QUIET DEBUG ALL OPTION SYMFILE=$(EXE).SYM OPTION MAP=$(EXE).MAP
#LFLAGS = /l=dos4g /x /zq /4s /k4000 /d2

!ifdef %NT
CC = $(%WATCOM)\binnt\wcc386
WL = $(%WATCOM)\binnt\wlink
!else
CC = $(%WATCOM)\binw\wcc386
WL = $(%WATCOM)\binw\wlink
!endif

!ifdef %MASM
ASM = $(%MASM)\bin\ml
!else
ASM = c:\compil\masm611\bin\ml
!endif

CFLAGS = /oaxt /zp2 /5s /zq /s /w3 /v /d2
AFLAGS = /Cx /Zm /c /W0 /Sa /DNoLanguage=SYSCALL /nologo /Djumps=;
LFLAGS = OPTION ST=16000 SYSTEM dos4g OPTION CASEEXACT OPTION QUIET DEBUG ALL OPTION MAP=$(EXE).MAP


.SILENT

OBJETS1  = convert.obj

EXE	 = convert

$(EXE).exe: $(OBJETS1) $(OBJETS2) $(OBJETS3) $(OBJETS4) $(OBJETS5) $(OBJETS6)
	E:\WLINK $(LFLAGS) NAME $(EXE).exe FILE *.obj
	E:\PRNTITRE M "$(EXE) OK"

.c.obj :
	E:\PRNTITRE M "$*.C"
	E:\WCC386 $^& $(CFLAGS)

.asm.obj :
	E:\PRNTITRE M "$*.ASM"
	E:\ML $(AFLAGS) $^&.ASM
