; Events generated by Arkos Tracker 2.

Events
	.word 769	; Wait for 768 frames.
	.byt 0

Events_Loop
	.word 769	; Wait for 768 frames.
	.byt 0

	.word 0	; End of sequence.
	.word Events_Loop	; Loops here.
