






typedef enum 
{
	DEVICE_FORMAT_BASIC_TAPE,
	DEVICE_FORMAT_TAPE,
	DEVICE_FORMAT_RAW,
	DEVICE_FORMAT_SOURCE_C,
	DEVICE_FORMAT_SOURCE_S,
	DEVICE_FORMAT_PICTURE,
	DEVICE_FORMAT_RAW_XY,
	DEVICE_FORMAT_RAW_PALETTE,
	DEVICE_FORMAT_SOURCE_BASIC,
	_DEVICE_FORMAT_MAX_
}DEVICE_FORMAT;


typedef enum 
{						// BGR
	ORIC_COLOR_BLACK,	// 000
	ORIC_COLOR_RED,		// 001
	ORIC_COLOR_GREEN,	// 010
	ORIC_COLOR_YELLOW,	// 011
	ORIC_COLOR_BLUE,	// 100
	ORIC_COLOR_MAGENTA,	// 101
	ORIC_COLOR_CYAN,	// 110
	ORIC_COLOR_WHITE,	// 111
	_ORIC_COLOR_LAST_
}ORIC_COLOR;


