;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Generated by OASIS compiler
; (c) Chema 2016
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


; Script 201
.(
.byt RESOURCE_SCRIPT|$80
.word (res_end-res_start +4)
.byt 201
res_start
+script_201_start
.byt SC_STOP_SCRIPT
res_end
.)

; String pack 200
.(
.byt RESOURCE_STRING|$80
.word (res_end-res_start +4)
.byt 200
res_start
.asc "I have a meeting with Ravella.",0 ; String 0
.asc "She has some information...",0 ; String 1
res_end
.)

; String pack 201
.(
.byt RESOURCE_STRING|$80
.word (res_end-res_start +4)
.byt 201
res_start
.asc "There's nothing of interest.",0 ; String 0
.asc "It reminds me of something...",0 ; String 1
.asc "A Brave New World...",0 ; String 2
.asc "Ravella ordered it for me.",0 ; String 3
.asc "Just another lamp.",0 ; String 4
.asc "My family...",0 ; String 5
.asc "Nothing interesting at the moment.",0 ; String 6
.asc "My room's exit door.",0 ; String 7
.asc "The only food I can eat.",0 ; String 8
.asc "I promised Ravella.",0 ; String 9
.asc "But I hate cheese.",0 ; String 10
.asc "The mug I bought last month.",0 ; String 11
.asc "It is empty.",0 ; String 12
.asc "I prefer it here.",0 ; String 13
.asc "I'd like to keep it in my room.",0 ; String 14
.asc "I don't see the use of moving that.",0 ; String 15
.asc "Why would I pick that up?",0 ; String 16
.asc "No time for reading now. Pity.",0 ; String 17
.asc "I could turn it on, but why?",0 ; String 18
.asc "No time for watching TV now.",0 ; String 19
.asc "I have not even started it yet.",0 ; String 20
.asc "There is a dog-ear on page 172.",0 ; String 21
res_end
.)

; Object Code 202
.(
.byt RESOURCE_OBJECTCODE|$80
.word (res_end-res_start +4)
.byt 202
res_start
; Response table
.byt VERB_OPEN
.word (l_Open-res_start)
.byt VERB_LOOKAT
.word (l_LookAt-res_start)
.byt $ff ; End of response table
l_Open
l_LookAt
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 201
.byt 0
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_STOP_SCRIPT
.byt SC_STOP_SCRIPT
res_end
.)

; Object Code 203
.(
.byt RESOURCE_OBJECTCODE|$80
.word (res_end-res_start +4)
.byt 203
res_start
; Response table
.byt VERB_PICKUP
.word (l_PickUp-res_start)
.byt VERB_USE
.word (l_Use-res_start)
.byt VERB_LOOKAT
.word (l_LookAt-res_start)
.byt $ff ; End of response table
l_PickUp
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 201
.byt SF_GETRANDINT
.byt 13
.byt 16
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_STOP_SCRIPT
l_Use
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_NOT, SF_EQ
.byt SF_GET_ACTIONOBJ2
.byt 64, 255
.byt 11
; then part
.byt SC_SPAWN_SCRIPT
.byt 1
.byt SC_STOP_SCRIPT
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 201
.byt 18
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_STOP_SCRIPT
l_LookAt
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 201
.byt 1
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_STOP_SCRIPT
.byt SC_STOP_SCRIPT
res_end
.)

; Object Code 204
.(
.byt RESOURCE_OBJECTCODE|$80
.word (res_end-res_start +4)
.byt 204
res_start
; Response table
.byt VERB_PICKUP
.word (l_PickUp-res_start)
.byt VERB_USE
.word (l_Use-res_start)
.byt VERB_OPEN
.word (l_Open-res_start)
.byt VERB_LOOKAT
.word (l_LookAt-res_start)
.byt $ff ; End of response table
l_PickUp
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 201
.byt SF_GETRANDINT
.byt 13
.byt 16
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_STOP_SCRIPT
l_Use
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_NOT, SF_EQ
.byt SF_GET_ACTIONOBJ2
.byt 64, 255
.byt 11
; then part
.byt SC_SPAWN_SCRIPT
.byt 1
.byt SC_STOP_SCRIPT
l_Open
.byt SC_CURSOR_ON
.byt 0
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 201
.byt 17
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 201
.byt 20
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 201
.byt 21
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_CURSOR_ON
.byt 1
.byt SC_STOP_SCRIPT
l_LookAt
.byt SC_CURSOR_ON
.byt 0
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 201
.byt 2
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 201
.byt 3
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_CURSOR_ON
.byt 1
.byt SC_STOP_SCRIPT
.byt SC_STOP_SCRIPT
res_end
.)

; Object Code 205
.(
.byt RESOURCE_OBJECTCODE|$80
.word (res_end-res_start +4)
.byt 205
res_start
; Response table
.byt VERB_USE
.word (l_Use-res_start)
.byt VERB_PICKUP
.word (l_PickUp-res_start)
.byt VERB_LOOKAT
.word (l_LookAt-res_start)
.byt $ff ; End of response table
l_Use
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_NOT, SF_EQ
.byt SF_GET_ACTIONOBJ2
.byt 64, 255
.byt 11
; then part
.byt SC_SPAWN_SCRIPT
.byt 1
.byt SC_STOP_SCRIPT
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 201
.byt 18
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_STOP_SCRIPT
l_PickUp
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 201
.byt SF_GETRANDINT
.byt 13
.byt 16
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_STOP_SCRIPT
l_LookAt
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 201
.byt 4
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_STOP_SCRIPT
.byt SC_STOP_SCRIPT
res_end
.)

; Object Code 206
.(
.byt RESOURCE_OBJECTCODE|$80
.word (res_end-res_start +4)
.byt 206
res_start
; Response table
.byt VERB_PICKUP
.word (l_PickUp-res_start)
.byt VERB_LOOKAT
.word (l_LookAt-res_start)
.byt $ff ; End of response table
l_PickUp
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 201
.byt SF_GETRANDINT
.byt 13
.byt 16
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_STOP_SCRIPT
l_LookAt
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 201
.byt 5
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_STOP_SCRIPT
.byt SC_STOP_SCRIPT
res_end
.)

; Object Code 207
.(
.byt RESOURCE_OBJECTCODE|$80
.word (res_end-res_start +4)
.byt 207
res_start
; Response table
.byt VERB_USE
.word (l_Use-res_start)
.byt VERB_LOOKAT
.word (l_LookAt-res_start)
.byt $ff ; End of response table
l_Use
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_NOT, SF_EQ
.byt SF_GET_ACTIONOBJ2
.byt 64, 255
.byt 11
; then part
.byt SC_SPAWN_SCRIPT
.byt 1
.byt SC_STOP_SCRIPT
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 201
.byt 19
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_STOP_SCRIPT
l_LookAt
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 201
.byt 6
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_STOP_SCRIPT
.byt SC_STOP_SCRIPT
res_end
.)

; Script 251
.(
.byt RESOURCE_SCRIPT|$80
.word (res_end-res_start +4)
.byt 251
res_start
+script_251_start
.byt SC_PLAYSFX
.byt 3
.byt SC_SET_ANIMSTATE
.byt 64, 200
.byt 2
.byt SC_SET_ANIMSTATE
.byt SF_ADD
.byt 64, 200
.byt 1
.byt 5
.byt SC_DELAY
.byt 5
.byt SC_SET_ANIMSTATE
.byt 64, 200
.byt 1
.byt SC_SET_ANIMSTATE
.byt SF_ADD
.byt 64, 200
.byt 1
.byt 4
.byt SC_DELAY
.byt 5
.byt SC_SET_ANIMSTATE
.byt 64, 200
.byt 0
.byt SC_SET_ANIMSTATE
.byt SF_ADD
.byt 64, 200
.byt 1
.byt 0
.byt SC_STOP_SCRIPT
res_end
.)

; Script 252
.(
.byt RESOURCE_SCRIPT|$80
.word (res_end-res_start +4)
.byt 252
res_start
+script_252_start
.byt SC_DELAY
.byt 64, 200
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GET_ANIMSTATE
.byt 64, 200
.byt 3
.byt 11
; then part
.byt SC_CHAIN_SCRIPT
.byt 64, 251
.byt SC_STOP_SCRIPT
res_end
.)

; Object Code 200
.(
.byt RESOURCE_OBJECTCODE|$80
.word (res_end-res_start +4)
.byt 200
res_start
; Response table
.byt VERB_LOOKAT
.word (l_LookAt-res_start)
.byt VERB_OPEN
.word (l_Open-res_start)
.byt VERB_CLOSE
.word (l_Close-res_start)
.byt VERB_USE
.word (l_Use-res_start)
.byt VERB_WALKTO
.word (l_WalkTo-res_start)
.byt $ff ; End of response table
l_LookAt
.byt SC_ACTOR_TALK
.byt SF_GET_ACTIONACTOR
.byt 64, 201
.byt 7
.byt SC_STOP_SCRIPT
l_Open
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_NOT, SF_EQ
.byt SF_GET_ANIMSTATE
.byt 64, 200
.byt 0
.byt 10
; then part
.byt SC_STOP_SCRIPT
.byt SC_PLAYSFX
.byt 3
.byt SC_SET_ANIMSTATE
.byt 64, 200
.byt 1
.byt SC_SET_ANIMSTATE
.byt SF_ADD
.byt 64, 200
.byt 1
.byt 4
.byt SC_DELAY
.byt 5
.byt SC_SET_ANIMSTATE
.byt 64, 200
.byt 2
.byt SC_SET_ANIMSTATE
.byt SF_ADD
.byt 64, 200
.byt 1
.byt 5
.byt SC_DELAY
.byt 5
.byt SC_SET_ANIMSTATE
.byt 64, 200
.byt 3
.byt SC_SET_ANIMSTATE
.byt SF_ADD
.byt 64, 200
.byt 1
.byt 6
.byt SC_SPAWN_SCRIPT
.byt 64, 252
.byt SC_STOP_SCRIPT
l_Close
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_NOT, SF_EQ
.byt SF_GET_ANIMSTATE
.byt 64, 200
.byt 3
.byt 10
; then part
.byt SC_STOP_SCRIPT
.byt SC_CHAIN_SCRIPT
.byt 64, 251
.byt SC_STOP_SCRIPT
l_Use
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_NOT, SF_EQ
.byt SF_GET_ACTIONOBJ2
.byt 64, 255
.byt 11
; then part
.byt SC_SPAWN_SCRIPT
.byt 1
.byt SC_STOP_SCRIPT
l_WalkTo
.byt SC_ASSIGN, 64, 200	; actor=sfGetActorExecutingAction()
.byt SF_GET_ACTIONACTOR
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GETVAL,64, 200	; actor
.byt SF_GET_EGO
.byt 10
; then part
.byt SC_CURSOR_ON
.byt 0
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GET_ANIMSTATE
.byt 64, 200
.byt 0
.byt 14
; then part
.byt SC_RUN_OBJECT_CODE
.byt 3
.byt 64, 200
.byt 64, 255
.byt SC_SET_WBASWALKABLE
.byt 3
.byt 1
.byt SC_ACTOR_WALKTO
.byt SF_GETVAL,64, 200	; actor
.byt 14
.byt 11
.byt SC_WAIT_FOR_ACTOR
.byt SF_GETVAL,64, 200	; actor
.byt SC_LOOK_DIRECTION
.byt SF_GETVAL,64, 200	; actor
.byt 2
.byt SC_BREAK_HERE
.byt SC_SET_OBJECT_POS
.byt SF_GETVAL,64, 200	; actor
.byt 3
.byt 12
.byt 6
.byt SC_LOOK_DIRECTION
.byt SF_GETVAL,64, 200	; actor
.byt 3
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GETVAL,64, 200	; actor
.byt SF_GET_EGO
.byt 12
; then part
.byt SC_CURSOR_ON
.byt 1
.byt SC_CHANGE_ROOM_AND_STOP
.byt 3
.byt SC_STOP_SCRIPT
res_end
.)
