;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Generated by OASIS compiler
; (c) Chema 2016
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


; String pack 200
.(
.byt RESOURCE_STRING|$80
.word (res_end-res_start +4)
.byt 200
res_start
.asc "La cuerda para volver arriba.",0 ; String 0
.asc "La entrada a una cueva.",0 ; String 1
.asc "Est",91," demasiado oscuro para ver.",0 ; String 2
res_end
.)

; Object Code 200
.(
.byt RESOURCE_OBJECTCODE|$80
.word (res_end-res_start +4)
.byt 200
res_start
; Response table
.byt VERB_LOOKAT
.word (l_LookAt-res_start)
.byt VERB_USE
.word (l_Use-res_start)
.byt VERB_WALKTO
.word (l_WalkTo-res_start)
.byt $ff ; End of response table
l_LookAt
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 1
.byt SC_STOP_SCRIPT
l_Use
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_NOT, SF_EQ
.byt SF_GET_ACTIONOBJ2
.byt 64, 255
.byt 11
; then part
.byt SC_SPAWN_SCRIPT
.byt 1
.byt SC_STOP_SCRIPT
l_WalkTo
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_NOT
.byt SF_IS_OBJINVENTORY
.byt 44
.byt 16
; then part
.byt SC_LOOK_DIRECTION
.byt 0
.byt 3
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 2
.byt SC_JUMP_REL, 24
; else part
.byt SC_SET_OBJECT_POS
.byt 0
.byt 33
.byt 12
.byt 50
.byt SC_LOOK_DIRECTION
.byt 0
.byt 1
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_GETFLAG,44	; bCrusaderCutscene
.byt 9
; then part
.byt SC_CHANGE_ROOM_AND_STOP
.byt 33
.byt SC_JUMP_REL, 7
; else part
.byt SC_SETFLAG, 44	; bCrusaderCutscene=true
.byt 1
.byt SC_SPAWN_SCRIPT
.byt 9
.byt SC_STOP_SCRIPT
res_end
.)

; Object Code 201
.(
.byt RESOURCE_OBJECTCODE|$80
.word (res_end-res_start +4)
.byt 201
res_start
; Response table
.byt VERB_LOOKAT
.word (l_LookAt-res_start)
.byt VERB_USE
.word (l_Use-res_start)
.byt VERB_WALKTO
.word (l_WalkTo-res_start)
.byt $ff ; End of response table
l_LookAt
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 0
.byt SC_STOP_SCRIPT
l_Use
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_NOT, SF_EQ
.byt SF_GET_ACTIONOBJ2
.byt 64, 255
.byt 11
; then part
.byt SC_SPAWN_SCRIPT
.byt 1
.byt SC_STOP_SCRIPT
l_WalkTo
.byt SC_SET_OBJECT_POS
.byt 0
.byt 31
.byt 16
.byt 14
.byt SC_LOOK_DIRECTION
.byt 0
.byt 1
.byt SC_CHANGE_ROOM_AND_STOP
.byt 31
.byt SC_STOP_SCRIPT
res_end
.)
