;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Generated by OASIS compiler
; (c) Chema 2016
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


; String pack 200
.(
.byt RESOURCE_STRING|$80
.word (res_end-res_start +4)
.byt 200
res_start
.asc "His blessings are upon you.",0 ; String 0
.asc "Speak and He will hear you.",0 ; String 1
.asc "I am thy true servant.",0 ; String 2
.asc "The souls from the outer darkness",0 ; String 3
.asc "are amongst us?",0 ; String 4
.asc "They are in the place of the novices.",0 ; String 5
.asc "Good. Come and pray with me.",0 ; String 6
.asc "Only from His hand comes life...",0 ; String 7
.asc "And from His wrath comes death.",0 ; String 8
.asc "With other souls to do His work...",0 ; String 9
.asc "there will be a chance for me ...",0 ; String 10
.asc "... for the faithful...",0 ; String 11
.asc "to rise to the priesthood.",0 ; String 12
.asc "He will not fail you.",0 ; String 13
.asc "You will be rewarded.",0 ; String 14
.asc "Master. I've found something...",0 ; String 15
.asc "I think there is an intruder.",0 ; String 16
.asc "Can't be. The prisoners were observed",0 ; String 17
.asc "from the moment they landed.",0 ; String 18
.asc "Maybe someone else came in his own",0 ; String 19
.asc "spaceship... Show us.",0 ; String 20
res_end
.)

; Script 200
.(
.byt RESOURCE_SCRIPT|$80
.word (res_end-res_start +4)
.byt 200
res_start
+script_200_start
.byt SC_STOP_SCRIPT
.byt SC_STOP_SCRIPT
res_end
.)
