;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Generated by OASIS compiler
; (c) Chema 2016
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


; Script 200
.(
.byt RESOURCE_SCRIPT|$80
.word (res_end-res_start +4)
.byt 200
res_start
+script_200_start
.byt SC_ASSIGN, 0	; tmpParam1=206
.byt 64, 206
.byt SC_CLEAR_EVENTS
.byt 1
.byt SC_SPAWN_SCRIPT
.byt 64, 201
.byt SC_WAIT_EVENT
.byt 1
.byt SC_ASSIGN, 0	; tmpParam1=207
.byt 64, 207
.byt SC_CLEAR_EVENTS
.byt 1
.byt SC_SPAWN_SCRIPT
.byt 64, 201
.byt SC_WAIT_EVENT
.byt 1
.byt SC_ASSIGN, 0	; tmpParam1=208
.byt 64, 208
.byt SC_CLEAR_EVENTS
.byt 1
.byt SC_SPAWN_SCRIPT
.byt 64, 201
.byt SC_WAIT_EVENT
.byt 1
.byt SC_ASSIGN, 0	; tmpParam1=209
.byt 64, 209
.byt SC_CLEAR_EVENTS
.byt 1
.byt SC_SPAWN_SCRIPT
.byt 64, 201
.byt SC_STOP_SCRIPT
res_end
.)

; Script 201
.(
.byt RESOURCE_SCRIPT|$80
.word (res_end-res_start +4)
.byt 201
res_start
+script_201_start
.byt SC_ASSIGN, 64, 200	; scid=tmpParam1
.byt SF_GETVAL,0	; tmpParam1
.byt SC_SET_EVENTS
.byt 1
l_loop
.byt SC_DELAY
.byt SF_GETRAND
.byt SC_DELAY
.byt SF_GETRANDINT
.byt 64, 100
.byt 64, 200
.byt SC_DELAY
.byt SF_GETRANDINT
.byt 64, 100
.byt 64, 200
.byt SC_DELAY
.byt SF_GETRAND
.byt SC_ASSIGN, 64, 201	; i=sfGetRandInt(0,4)
.byt SF_GETRANDINT
.byt 0
.byt 4
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_LT
.byt SF_GETVAL,64, 201	; i
.byt 2
.byt 44
; then part
; for
; Init part
.byt SC_ASSIGN, 64, 201	; i=12
.byt 12
; Condition
.byt SC_JUMP_IF, SF_NOT
.byt SF_LE
.byt SF_GETVAL,64, 201	; i
.byt 15
.word 70
; for body
.byt SC_SET_ANIMSTATE
.byt SF_GETVAL,64, 200	; scid
.byt SF_GETVAL,64, 201	; i
.byt SC_DELAY
.byt 30
; Increment expression
.byt SC_ASSIGN, 64, 201	; i=i+1
.byt SF_ADD
.byt SF_GETVAL,64, 201	; i
.byt 1
; end for
.byt SC_JUMP, 41, 0	; jump to 41
.byt SC_JUMP_REL, 64, 93
; else part
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GETVAL,64, 201	; i
.byt 2
.byt 43
; then part
; for
; Init part
.byt SC_ASSIGN, 64, 201	; i=1
.byt 1
; Condition
.byt SC_JUMP_IF, SF_NOT
.byt SF_LE
.byt SF_GETVAL,64, 201	; i
.byt 3
.word 114
; for body
.byt SC_SET_ANIMSTATE
.byt SF_GETVAL,64, 200	; scid
.byt SF_GETVAL,64, 201	; i
.byt SC_DELAY
.byt 60
; Increment expression
.byt SC_ASSIGN, 64, 201	; i=i+1
.byt SF_ADD
.byt SF_GETVAL,64, 201	; i
.byt 1
; end for
.byt SC_JUMP, 85, 0	; jump to 85
.byt SC_JUMP_REL, 49
; else part
.byt SC_SET_ANIMSTATE
.byt SF_GETVAL,64, 200	; scid
.byt 10
.byt SC_DELAY
.byt 30
; for
; Init part
.byt SC_ASSIGN, 64, 201	; i=4
.byt 4
; Condition
.byt SC_JUMP_IF, SF_NOT
.byt SF_LE
.byt SF_GETVAL,64, 201	; i
.byt 10
.word 156
; for body
.byt SC_SET_ANIMSTATE
.byt SF_GETVAL,64, 200	; scid
.byt SF_GETVAL,64, 201	; i
.byt SC_DELAY
.byt 10
; Increment expression
.byt SC_ASSIGN, 64, 201	; i=i+1
.byt SF_ADD
.byt SF_GETVAL,64, 201	; i
.byt 1
; end for
.byt SC_JUMP, 127, 0	; jump to 127
.byt SC_DELAY
.byt 20
.byt SC_SET_ANIMSTATE
.byt SF_GETVAL,64, 200	; scid
.byt 11
.byt SC_DELAY
.byt 50
.byt SC_SET_ANIMSTATE
.byt SF_GETVAL,64, 200	; scid
.byt 0
.byt SC_JUMP
.word (l_loop-res_start)
.byt SC_STOP_SCRIPT
res_end
.)

; Object Code 206
.(
.byt RESOURCE_OBJECTCODE|$80
.word (res_end-res_start +4)
.byt 206
res_start
; Response table
.byt VERB_LOOKAT
.word (l_LookAt-res_start)
.byt $ff ; End of response table
l_LookAt
.byt SC_ACTOR_TALK
.byt SF_GET_EGO
.byt 64, 200
.byt 2
.byt SC_STOP_SCRIPT
res_end
.)

; Object Code 207
.(
.byt RESOURCE_OBJECTCODE|$80
.word (res_end-res_start +4)
.byt 207
res_start
; Response table
.byt VERB_LOOKAT
.word (l_LookAt-res_start)
.byt $ff ; End of response table
l_LookAt
.byt SC_ACTOR_TALK
.byt SF_GET_EGO
.byt 64, 200
.byt 2
.byt SC_STOP_SCRIPT
res_end
.)

; Object Code 208
.(
.byt RESOURCE_OBJECTCODE|$80
.word (res_end-res_start +4)
.byt 208
res_start
; Response table
.byt VERB_LOOKAT
.word (l_LookAt-res_start)
.byt $ff ; End of response table
l_LookAt
.byt SC_ACTOR_TALK
.byt SF_GET_EGO
.byt 64, 200
.byt 2
.byt SC_STOP_SCRIPT
res_end
.)

; Object Code 209
.(
.byt RESOURCE_OBJECTCODE|$80
.word (res_end-res_start +4)
.byt 209
res_start
; Response table
.byt VERB_LOOKAT
.word (l_LookAt-res_start)
.byt $ff ; End of response table
l_LookAt
.byt SC_ACTOR_TALK
.byt SF_GET_EGO
.byt 64, 200
.byt 2
.byt SC_STOP_SCRIPT
res_end
.)

; Script 250
.(
.byt RESOURCE_SCRIPT|$80
.word (res_end-res_start +4)
.byt 250
res_start
+script_250_start
.byt SC_ASSIGN, 64, 200	; door=tmpParam1
.byt SF_GETVAL,0	; tmpParam1
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_NOT, SF_EQ
.byt SF_GET_ANIMSTATE
.byt SF_GETVAL,64, 200	; door
.byt 0
.byt 11
; then part
.byt SC_STOP_SCRIPT
.byt SC_SPAWN_SCRIPT
.byt 64, 252
.byt SC_BREAK_HERE
.byt SC_PLAYSFX
.byt 3
; for
; Init part
.byt SC_ASSIGN, 64, 201	; i=1
.byt 1
; Condition
.byt SC_JUMP_IF, SF_NOT
.byt SF_LE
.byt SF_GETVAL,64, 201	; i
.byt 5
.word 55
; for body
.byt SC_SET_ANIMSTATE
.byt SF_GETVAL,64, 200	; door
.byt SF_GETVAL,64, 201	; i
.byt SC_DELAY
.byt 5
; Increment expression
.byt SC_ASSIGN, 64, 201	; i=i+1
.byt SF_ADD
.byt SF_GETVAL,64, 201	; i
.byt 1
; end for
.byt SC_JUMP, 26, 0	; jump to 26
.byt SC_STOP_SCRIPT
res_end
.)

; Script 251
.(
.byt RESOURCE_SCRIPT|$80
.word (res_end-res_start +4)
.byt 251
res_start
+script_251_start
.byt SC_ASSIGN, 64, 200	; door=tmpParam1
.byt SF_GETVAL,0	; tmpParam1
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_NOT, SF_EQ
.byt SF_GET_ANIMSTATE
.byt SF_GETVAL,64, 200	; door
.byt 5
.byt 11
; then part
.byt SC_STOP_SCRIPT
.byt SC_PLAYSFX
.byt 3
; for
; Init part
.byt SC_ASSIGN, 64, 201	; i=4
.byt 4
; Condition
.byt SC_JUMP_IF, SF_NOT
.byt SF_LT
.byt SF_GETVAL,64, 201	; i
.byt 64, 255
.word 52
; for body
.byt SC_SET_ANIMSTATE
.byt SF_GETVAL,64, 200	; door
.byt SF_GETVAL,64, 201	; i
.byt SC_DELAY
.byt 5
; Increment expression
.byt SC_ASSIGN, 64, 201	; i=i-1
.byt SF_SUB
.byt SF_GETVAL,64, 201	; i
.byt 1
; end for
.byt SC_JUMP, 22, 0	; jump to 22
.byt SC_STOP_SCRIPT
res_end
.)

; Script 252
.(
.byt RESOURCE_SCRIPT|$80
.word (res_end-res_start +4)
.byt 252
res_start
+script_252_start
.byt SC_ASSIGN, 64, 200	; door=tmpParam1
.byt SF_GETVAL,0	; tmpParam1
.byt SC_DELAY
.byt 64, 200
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_NOT, SF_EQ
.byt SF_GET_ANIMSTATE
.byt SF_GETVAL,64, 200	; door
.byt 0
.byt 18
; then part
.byt SC_ASSIGN, 0	; tmpParam1=door
.byt SF_GETVAL,64, 200	; door
.byt SC_CHAIN_SCRIPT
.byt 64, 251
.byt SC_STOP_SCRIPT
res_end
.)

; Object Code 200
.(
.byt RESOURCE_OBJECTCODE|$80
.word (res_end-res_start +4)
.byt 200
res_start
; Response table
.byt VERB_LOOKAT
.word (l_LookAt-res_start)
.byt VERB_OPEN
.word (l_Open-res_start)
.byt VERB_CLOSE
.word (l_Close-res_start)
.byt VERB_USE
.word (l_Use-res_start)
.byt VERB_WALKTO
.word (l_WalkTo-res_start)
.byt $ff ; End of response table
l_LookAt
.byt SC_ACTOR_TALK
.byt SF_GET_ACTIONACTOR
.byt 64, 200
.byt 0
.byt SC_STOP_SCRIPT
l_Open
.byt SC_ASSIGN, 0	; tmpParam1=200
.byt 64, 200
.byt SC_CHAIN_SCRIPT
.byt 64, 250
.byt SC_STOP_SCRIPT
l_Close
.byt SC_ASSIGN, 0	; tmpParam1=200
.byt 64, 200
.byt SC_CHAIN_SCRIPT
.byt 64, 251
.byt SC_STOP_SCRIPT
l_Use
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_NOT, SF_EQ
.byt SF_GET_ACTIONOBJ2
.byt 64, 255
.byt 11
; then part
.byt SC_SPAWN_SCRIPT
.byt 1
.byt SC_STOP_SCRIPT
l_WalkTo
.byt SC_ASSIGN, 64, 200	; actor=sfGetActorExecutingAction()
.byt SF_GET_ACTIONACTOR
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GETVAL,64, 200	; actor
.byt SF_GET_EGO
.byt 10
; then part
.byt SC_CURSOR_ON
.byt 0
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GET_ANIMSTATE
.byt 64, 200
.byt 0
.byt 14
; then part
.byt SC_RUN_OBJECT_CODE
.byt 3
.byt 64, 200
.byt 64, 255
.byt SC_SET_OBJECT_POS
.byt SF_GETVAL,64, 200	; actor
.byt 49
.byt 16
.byt 16
.byt SC_LOOK_DIRECTION
.byt SF_GETVAL,64, 200	; actor
.byt 2
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GETVAL,64, 200	; actor
.byt SF_GET_EGO
.byt 12
; then part
.byt SC_CURSOR_ON
.byt 1
.byt SC_CHANGE_ROOM_AND_STOP
.byt 49
.byt SC_STOP_SCRIPT
res_end
.)

; Object Code 201
.(
.byt RESOURCE_OBJECTCODE|$80
.word (res_end-res_start +4)
.byt 201
res_start
; Response table
.byt VERB_LOOKAT
.word (l_LookAt-res_start)
.byt VERB_OPEN
.word (l_Open-res_start)
.byt VERB_CLOSE
.word (l_Close-res_start)
.byt VERB_USE
.word (l_Use-res_start)
.byt VERB_WALKTO
.word (l_WalkTo-res_start)
.byt $ff ; End of response table
l_LookAt
.byt SC_ACTOR_TALK
.byt SF_GET_ACTIONACTOR
.byt 64, 200
.byt 0
.byt SC_STOP_SCRIPT
l_Open
.byt SC_ASSIGN, 0	; tmpParam1=201
.byt 64, 201
.byt SC_CHAIN_SCRIPT
.byt 64, 250
.byt SC_STOP_SCRIPT
l_Close
.byt SC_ASSIGN, 0	; tmpParam1=201
.byt 64, 201
.byt SC_CHAIN_SCRIPT
.byt 64, 251
.byt SC_STOP_SCRIPT
l_Use
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_NOT, SF_EQ
.byt SF_GET_ACTIONOBJ2
.byt 64, 255
.byt 11
; then part
.byt SC_SPAWN_SCRIPT
.byt 1
.byt SC_STOP_SCRIPT
l_WalkTo
.byt SC_ASSIGN, 64, 200	; actor=sfGetActorExecutingAction()
.byt SF_GET_ACTIONACTOR
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GETVAL,64, 200	; actor
.byt SF_GET_EGO
.byt 10
; then part
.byt SC_CURSOR_ON
.byt 0
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GET_ANIMSTATE
.byt 64, 201
.byt 0
.byt 14
; then part
.byt SC_RUN_OBJECT_CODE
.byt 3
.byt 64, 201
.byt 64, 255
.byt SC_SET_OBJECT_POS
.byt SF_GETVAL,64, 200	; actor
.byt 50
.byt 16
.byt 16
.byt SC_LOOK_DIRECTION
.byt SF_GETVAL,64, 200	; actor
.byt 2
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GETVAL,64, 200	; actor
.byt SF_GET_EGO
.byt 12
; then part
.byt SC_CURSOR_ON
.byt 1
.byt SC_CHANGE_ROOM_AND_STOP
.byt 50
.byt SC_STOP_SCRIPT
res_end
.)

; Object Code 202
.(
.byt RESOURCE_OBJECTCODE|$80
.word (res_end-res_start +4)
.byt 202
res_start
; Response table
.byt VERB_LOOKAT
.word (l_LookAt-res_start)
.byt VERB_OPEN
.word (l_Open-res_start)
.byt VERB_CLOSE
.word (l_Close-res_start)
.byt VERB_USE
.word (l_Use-res_start)
.byt VERB_WALKTO
.word (l_WalkTo-res_start)
.byt $ff ; End of response table
l_LookAt
.byt SC_ACTOR_TALK
.byt SF_GET_ACTIONACTOR
.byt 64, 200
.byt 0
.byt SC_STOP_SCRIPT
l_Open
.byt SC_ASSIGN, 0	; tmpParam1=202
.byt 64, 202
.byt SC_CHAIN_SCRIPT
.byt 64, 250
.byt SC_STOP_SCRIPT
l_Close
.byt SC_ASSIGN, 0	; tmpParam1=202
.byt 64, 202
.byt SC_CHAIN_SCRIPT
.byt 64, 251
.byt SC_STOP_SCRIPT
l_Use
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_NOT, SF_EQ
.byt SF_GET_ACTIONOBJ2
.byt 64, 255
.byt 11
; then part
.byt SC_SPAWN_SCRIPT
.byt 1
.byt SC_STOP_SCRIPT
l_WalkTo
.byt SC_ASSIGN, 64, 200	; actor=sfGetActorExecutingAction()
.byt SF_GET_ACTIONACTOR
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GETVAL,64, 200	; actor
.byt SF_GET_EGO
.byt 10
; then part
.byt SC_CURSOR_ON
.byt 0
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GET_ANIMSTATE
.byt 64, 202
.byt 0
.byt 14
; then part
.byt SC_RUN_OBJECT_CODE
.byt 3
.byt 64, 202
.byt 64, 255
.byt SC_SET_OBJECT_POS
.byt SF_GETVAL,64, 200	; actor
.byt 51
.byt 16
.byt 16
.byt SC_LOOK_DIRECTION
.byt SF_GETVAL,64, 200	; actor
.byt 2
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GETVAL,64, 200	; actor
.byt SF_GET_EGO
.byt 12
; then part
.byt SC_CURSOR_ON
.byt 1
.byt SC_CHANGE_ROOM_AND_STOP
.byt 51
.byt SC_STOP_SCRIPT
res_end
.)

; Object Code 203
.(
.byt RESOURCE_OBJECTCODE|$80
.word (res_end-res_start +4)
.byt 203
res_start
; Response table
.byt VERB_LOOKAT
.word (l_LookAt-res_start)
.byt VERB_OPEN
.word (l_Open-res_start)
.byt VERB_CLOSE
.word (l_Close-res_start)
.byt VERB_USE
.word (l_Use-res_start)
.byt VERB_WALKTO
.word (l_WalkTo-res_start)
.byt $ff ; End of response table
l_LookAt
.byt SC_ACTOR_TALK
.byt SF_GET_ACTIONACTOR
.byt 64, 200
.byt 0
.byt SC_STOP_SCRIPT
l_Open
.byt SC_ASSIGN, 0	; tmpParam1=203
.byt 64, 203
.byt SC_CHAIN_SCRIPT
.byt 64, 250
.byt SC_STOP_SCRIPT
l_Close
.byt SC_ASSIGN, 0	; tmpParam1=203
.byt 64, 203
.byt SC_CHAIN_SCRIPT
.byt 64, 251
.byt SC_STOP_SCRIPT
l_Use
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_NOT, SF_EQ
.byt SF_GET_ACTIONOBJ2
.byt 64, 255
.byt 11
; then part
.byt SC_SPAWN_SCRIPT
.byt 1
.byt SC_STOP_SCRIPT
l_WalkTo
.byt SC_ASSIGN, 64, 200	; actor=sfGetActorExecutingAction()
.byt SF_GET_ACTIONACTOR
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GETVAL,64, 200	; actor
.byt SF_GET_EGO
.byt 10
; then part
.byt SC_CURSOR_ON
.byt 0
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GET_ANIMSTATE
.byt 64, 203
.byt 0
.byt 14
; then part
.byt SC_RUN_OBJECT_CODE
.byt 3
.byt 64, 203
.byt 64, 255
.byt SC_SET_OBJECT_POS
.byt SF_GETVAL,64, 200	; actor
.byt 52
.byt 16
.byt 16
.byt SC_LOOK_DIRECTION
.byt SF_GETVAL,64, 200	; actor
.byt 2
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GETVAL,64, 200	; actor
.byt SF_GET_EGO
.byt 12
; then part
.byt SC_CURSOR_ON
.byt 1
.byt SC_CHANGE_ROOM_AND_STOP
.byt 52
.byt SC_STOP_SCRIPT
res_end
.)

; Object Code 205
.(
.byt RESOURCE_OBJECTCODE|$80
.word (res_end-res_start +4)
.byt 205
res_start
; Response table
.byt VERB_WALKTO
.word (l_WalkTo-res_start)
.byt VERB_OPEN
.word (l_Open-res_start)
.byt $ff ; End of response table
l_WalkTo
l_Open
.byt SC_ACTOR_TALK
.byt SF_GET_EGO
.byt 64, 200
.byt 1
.byt SC_STOP_SCRIPT
res_end
.)

; Object Code 204
.(
.byt RESOURCE_OBJECTCODE|$80
.word (res_end-res_start +4)
.byt 204
res_start
; Response table
.byt VERB_WALKTO
.word (l_WalkTo-res_start)
.byt $ff ; End of response table
l_WalkTo
.byt SC_ASSIGN, 64, 200	; actor=sfGetEgo()
.byt SF_GET_EGO
.byt SC_SET_OBJECT_POS
.byt SF_GETVAL,64, 200	; actor
.byt 47
.byt 14
.byt 0
.byt SC_LOOK_DIRECTION
.byt SF_GETVAL,64, 200	; actor
.byt 0
.byt SC_CHANGE_ROOM_AND_STOP
.byt 47
.byt SC_STOP_SCRIPT
res_end
.)

; String pack 200
.(
.byt RESOURCE_STRING|$80
.word (res_end-res_start +4)
.byt 200
res_start
.asc "Solo es una puerta autom",91,"tica.",0 ; String 0
.asc "No es momento de volver.",0 ; String 1
.asc "Parece que est",91,"n echando anuncios.",0 ; String 2
res_end
.)
