;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Generated by OASIS compiler
; (c) Chema 2016
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


; Script 200
.(
.byt RESOURCE_SCRIPT|$80
.word (res_end-res_start +4)
.byt 200
res_start
+script_200_start
.byt SC_LOAD_OBJECT
.byt 26
.byt SC_LOAD_OBJECT
.byt 25
.byt SC_SET_OBJECT_POS
.byt 25
.byt 55
.byt 15
.byt 20
.byt SC_SET_OBJECT_POS
.byt 26
.byt 55
.byt 15
.byt 37
.byt SC_LOOK_DIRECTION
.byt 25
.byt 1
.byt SC_LOOK_DIRECTION
.byt 26
.byt 1
.byt SC_BREAK_HERE
.byt SC_ACTOR_WALKTO
.byt 26
.byt 32
.byt 15
.byt SC_WAIT_FOR_ACTOR
.byt 26
.byt SC_DELAY
.byt 50
.byt SC_LOOK_DIRECTION
.byt 25
.byt 0
.byt SC_BREAK_HERE
; for
; Init part
.byt SC_ASSIGN, 64, 200	; i=0
.byt 0
; Condition
.byt SC_JUMP_IF, SF_NOT
.byt SF_LE
.byt SF_GETVAL,64, 200	; i
.byt 18
.word 124
; for body
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_OR
.byt SF_OR
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 4
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 8
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 16
.byt 26
; then part
.byt SC_ASSIGN, 64, 201	; a=26
.byt 26
.byt SC_JUMP_REL, 6
; else part
.byt SC_ASSIGN, 64, 201	; a=25
.byt 25
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 2
.byt 13
; then part
.byt SC_LOOK_DIRECTION
.byt 25
.byt 1
.byt SC_DELAY
.byt 50
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 5
.byt 11
; then part
.byt SC_LOOK_DIRECTION
.byt 25
.byt 0
.byt SC_ACTOR_TALK
.byt SF_GETVAL,64, 201	; a
.byt 64, 200
.byt SF_GETVAL,64, 200	; i
.byt SC_WAIT_FOR_ACTOR
.byt SF_GETVAL,64, 201	; a
; Increment expression
.byt SC_ASSIGN, 64, 200	; i=i+1
.byt SF_ADD
.byt SF_GETVAL,64, 200	; i
.byt 1
; end for
.byt SC_JUMP, 37, 0	; jump to 37
.byt SC_DELAY
.byt 64, 100
.byt SC_BWPALETTE
.byt SC_PLAY_TUNE
.byt 1
.byt SC_WAIT_FOR_TUNE
.byt SC_CLEAR_ROOMAREA
l_here2
.byt SC_SET_OVERRIDE
.word (l_end-res_start)
l_here
.byt SC_JUMP
.word (l_here-res_start)
l_end
.byt SC_JUMP
.word (l_here2-res_start)
.byt SC_STOP_SCRIPT
res_end
.)

; String pack 200
.(
.byt RESOURCE_STRING|$80
.word (res_end-res_start +4)
.byt 200
res_start
.asc "Ah, Travis.",0 ; String 0
.asc "Everyone's heard about your fiasco...",0 ; String 1
.asc "You've heard, of course, that there",0 ; String 2
.asc "have been two attempts on my life.",0 ; String 3
.asc "I have. I was very concerned.",0 ; String 4
.asc "I consider YOU responsible.",0 ; String 5
.asc "Your incompetence has put my life and",0 ; String 6
.asc "my position at risk.",0 ; String 7
.asc "Yes, but this WILL change. I have...",0 ; String 8
.asc "Stop it!",0 ; String 9
.asc "We will capture Blake and his ship",0 ; String 10
.asc "sooner or later, but for now I want",0 ; String 11
.asc "to put all our resources in something",0 ; String 12
.asc "else... something that will put me in",0 ; String 13
.asc "a much more powerful position inside",0 ; String 14
.asc "the Federation High-Command.",0 ; String 15
.asc "Yes?",0 ; String 16
.asc "I want to show you Project ORAC.",0 ; String 17
.asc "I'll debrief you on the details...",0 ; String 18
res_end
.)
