;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Generated by OASIS compiler
; (c) Chema 2016
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


; Script 200
.(
.byt RESOURCE_SCRIPT|$80
.word (res_end-res_start +4)
.byt 200
res_start
+script_200_start
.byt SC_REMOVE_FROM_INVENTORY
.byt 6
.byt SC_REMOVE_FROM_INVENTORY
.byt 9
.byt SC_SPAWN_SCRIPT
.byt 64, 201
.byt SC_STOP_SCRIPT
res_end
.)

; Script 201
.(
.byt RESOURCE_SCRIPT|$80
.word (res_end-res_start +4)
.byt 201
res_start
+script_201_start
.byt SC_REMOVE_OBJECT
.byt 25
.byt SC_REMOVE_OBJECT
.byt 26
.byt SC_DELAY
.byt 50
; for
; Init part
.byt SC_ASSIGN, 64, 200	; i=0
.byt 0
; Condition
.byt SC_JUMP_IF, SF_NOT
.byt SF_LT
.byt SF_GETVAL,64, 200	; i
.byt 15
.word 88
; for body
.byt SC_PRINT_AT
.byt 64, 200
.byt SF_GETVAL,64, 200	; i
.byt 0
.byt 64, 112
.byt SC_PRINT_AT
.byt 64, 200
.byt SF_ADD
.byt SF_GETVAL,64, 200	; i
.byt 1
.byt 0
.byt 64, 120
.byt SC_PRINT_AT
.byt 64, 200
.byt SF_ADD
.byt SF_GETVAL,64, 200	; i
.byt 2
.byt 0
.byt 64, 128
.byt SC_DELAY
.byt 64, 200
.byt SC_DELAY
.byt 64, 200
.byt SC_PRINT_AT
.byt 64, 200
.byt 20
.byt 0
.byt 64, 112
.byt SC_PRINT_AT
.byt 64, 200
.byt 20
.byt 0
.byt 64, 120
.byt SC_PRINT_AT
.byt 64, 200
.byt 20
.byt 0
.byt 64, 128
; Increment expression
.byt SC_ASSIGN, 64, 200	; i=i+3
.byt SF_ADD
.byt SF_GETVAL,64, 200	; i
.byt 3
; end for
.byt SC_JUMP, 10, 0	; jump to 10
.byt SC_DELAY
.byt 30
.byt SC_PRINT_AT
.byt 64, 200
.byt 15
.byt 0
.byt 64, 112
.byt SC_PRINT_AT
.byt 64, 200
.byt 16
.byt 0
.byt 64, 120
.byt SC_DELAY
.byt 64, 200
.byt SC_DELAY
.byt 64, 100
.byt SC_PRINT_AT
.byt 64, 200
.byt 20
.byt 0
.byt 64, 112
.byt SC_PRINT_AT
.byt 64, 200
.byt 20
.byt 0
.byt 64, 120
.byt SC_PRINT_AT
.byt 64, 200
.byt 17
.byt 0
.byt 64, 112
.byt SC_PRINT_AT
.byt 64, 200
.byt 18
.byt 0
.byt 64, 120
.byt SC_DELAY
.byt 64, 200
.byt SC_DELAY
.byt 64, 100
.byt SC_PRINT_AT
.byt 64, 200
.byt 20
.byt 0
.byt 64, 112
.byt SC_PRINT_AT
.byt 64, 200
.byt 20
.byt 0
.byt 64, 120
.byt SC_PRINT_AT
.byt 64, 200
.byt 19
.byt 0
.byt 64, 112
.byt SC_DELAY
.byt 64, 200
.byt SC_PLAYSFX
.byt 7
.byt SC_WAIT_FOR_TUNE
.byt SC_PRINT_AT
.byt 64, 200
.byt 20
.byt 0
.byt 64, 112
.byt SC_PLAY_TUNE
.byt 1
.byt SC_WAIT_FOR_TUNE
.byt SC_FADETOBLACK
.byt SC_SPAWN_SCRIPT
.byt 3
.byt SC_SAVEGAME
.byt SC_STOP_SCRIPT
res_end
.)

; String pack 200
.(
.byt RESOURCE_STRING|$80
.word (res_end-res_start +4)
.byt 200
res_start
.asc "By the authority of the Terran",0 ; String 0
.asc "Federation the accused has been found",0 ; String 1
.asc "guilty on the following charges:",0 ; String 2
.asc "Kidnapping, Assault on a Minor, ",0 ; String 3
.asc "Attempting to Corrupt Minors, ",0 ; String 4
.asc "and Child Abuse.",0 ; String 5
.asc "His crimes have been accorded a",0 ; String 6
.asc "Category Nine rating, and as such are",0 ; String 7
.asc "adjudged most grave. Roj Blake...",0 ; String 8
.asc "it is the sentence of this tribunal",0 ; String 9
.asc "that you be transported to the penal",0 ; String 10
.asc "colony on the planet Cygnus Alpha,",0 ; String 11
.asc "where you will remain for the rest of",0 ; String 12
.asc "your natural life.",0 ; String 13
.asc " ",0 ; String 14
.asc "",A_FWYELLOW,"But the evidence is false!",0 ; String 15
.asc "",A_FWYELLOW,"These charges are lies!",0 ; String 16
.asc "Take a long look at this planet. It's",0 ; String 17
.asc "the last time you'll ever see it.",0 ; String 18
.asc "",A_FWYELLOW,"No, I'm coming back.",0 ; String 19
.asc "                                        ",0 ; String 20
res_end
.)
