;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Generated by OASIS compiler
; (c) Chema 2016
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


; Script 200
.(
.byt RESOURCE_SCRIPT|$80
.word (res_end-res_start +4)
.byt 200
res_start
+script_200_start
.byt SC_SPAWN_SCRIPT
.byt 64, 210
.byt SC_SPAWN_SCRIPT
.byt 64, 202
.byt SC_STOP_SCRIPT
res_end
.)

; Script 210
.(
.byt RESOURCE_SCRIPT|$80
.word (res_end-res_start +4)
.byt 210
res_start
+script_210_start
.byt SC_DELAY
.byt SF_GETRANDINT
.byt 64, 80
.byt 64, 110
.byt SC_SET_ANIMSTATE
.byt 64, 201
.byt 1
.byt SC_DELAY
.byt 5
.byt SC_SET_ANIMSTATE
.byt 64, 201
.byt 2
.byt SC_DELAY
.byt 5
.byt SC_SET_ANIMSTATE
.byt 64, 201
.byt 3
.byt SC_DELAY
.byt SF_GETRANDINT
.byt 64, 80
.byt 64, 110
.byt SC_SET_ANIMSTATE
.byt 64, 201
.byt 2
.byt SC_DELAY
.byt 5
.byt SC_SET_ANIMSTATE
.byt 64, 201
.byt 1
.byt SC_DELAY
.byt 5
.byt SC_SET_ANIMSTATE
.byt 64, 201
.byt 0
.byt SC_RESTART_SCRIPT
.byt SC_STOP_SCRIPT
res_end
.)

; Script 202
.(
.byt RESOURCE_SCRIPT|$80
.word (res_end-res_start +4)
.byt 202
res_start
+script_202_start
.byt SC_DELAY
.byt SF_GETRANDINT
.byt 64, 150
.byt 64, 250
.byt SC_LOOK_DIRECTION
.byt 11
.byt 3
.byt SC_DELAY
.byt SF_GETRANDINT
.byt 64, 150
.byt 64, 250
.byt SC_LOOK_DIRECTION
.byt 11
.byt 1
.byt SC_DELAY
.byt SF_GETRANDINT
.byt 64, 150
.byt 64, 250
.byt SC_LOOK_DIRECTION
.byt 11
.byt 3
.byt SC_DELAY
.byt SF_GETRANDINT
.byt 64, 150
.byt 64, 250
.byt SC_LOOK_DIRECTION
.byt 11
.byt 0
.byt SC_RESTART_SCRIPT
.byt SC_STOP_SCRIPT
res_end
.)

; Object Code 200
.(
.byt RESOURCE_OBJECTCODE|$80
.word (res_end-res_start +4)
.byt 200
res_start
; Response table
.byt VERB_WALKTO
.word (l_WalkTo-res_start)
.byt $ff ; End of response table
l_WalkTo
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_AND
.byt SF_GETFLAG,3	; bMapContactGiven
.byt SF_NOT, SF_EQ
.byt SF_GET_ROOM
.byt 11
.byt 5
.byt 22
; then part
.byt SC_TERMINATE_SCRIPT
.byt 64, 202
.byt SC_LOOK_DIRECTION
.byt 11
.byt 0
.byt SC_SET_OBJECT_POS
.byt 11
.byt 5
.byt 14
.byt 5
.byt SC_SET_OBJECT_POS
.byt 0
.byt 3
.byt 13
.byt 1
.byt SC_CHANGE_ROOM_AND_STOP
.byt 3
.byt SC_STOP_SCRIPT
res_end
.)

; Object Code 201
.(
.byt RESOURCE_OBJECTCODE|$80
.word (res_end-res_start +4)
.byt 201
res_start
; Response table
.byt VERB_LOOKAT
.word (l_LookAt-res_start)
.byt $ff ; End of response table
l_LookAt
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 0
.byt SC_STOP_SCRIPT
res_end
.)

; Object Code 202
.(
.byt RESOURCE_OBJECTCODE|$80
.word (res_end-res_start +4)
.byt 202
res_start
; Response table
.byt VERB_LOOKAT
.word (l_LookAt-res_start)
.byt $ff ; End of response table
l_LookAt
.byt SC_CURSOR_ON
.byt 0
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 1
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_LOOK_DIRECTION
.byt 0
.byt 3
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 2
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 3
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 4
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_CURSOR_ON
.byt 1
.byt SC_STOP_SCRIPT
res_end
.)

; Object Code 203
.(
.byt RESOURCE_OBJECTCODE|$80
.word (res_end-res_start +4)
.byt 203
res_start
; Response table
.byt VERB_LOOKAT
.word (l_LookAt-res_start)
.byt $ff ; End of response table
l_LookAt
.byt SC_CURSOR_ON
.byt 0
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 5
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_LOOK_DIRECTION
.byt 0
.byt 3
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 6
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_CURSOR_ON
.byt 1
.byt SC_STOP_SCRIPT
res_end
.)

; String pack 200
.(
.byt RESOURCE_STRING|$80
.word (res_end-res_start +4)
.byt 200
res_start
.asc "S",93,". Otra c",91,"mara de seguridad.",0 ; String 0
.asc "Salva tu planeta.",0 ; String 1
.asc "Todos trabajamos con un fin:",0 ; String 2
.asc "Hacer la Tierra habitable de nuevo.",0 ; String 3
.asc "Ese es el plan de la Federaci",94,"n.",0 ; String 4
.asc "Al",93,"state en el Cuerpo de Seguridad.",0 ; String 5
.asc "No, gracias.",0 ; String 6
res_end
.)

; Dialog 200
.(
.byt RESOURCE_DIALOG|$80
.word (res_end-res_start +4)
.byt 200
res_start
.byt 202	; Stringpack with options
.byt 201	; Script with response actions
.byt 0,0,1,$ff	; Active flags
.word (l_map-script_201_start),(l_exits-script_201_start),(l_bye-script_201_start)	; Jump labels
res_end
.)
; String pack for dialog 200
.(
.byt RESOURCE_STRING|$80
.word (res_end-res_start +4)
.byt 202
res_start
.asc "Necesito un mapa del complejo.",0 ; String 0
.asc "Necesito las salidas de la ciudad.",0 ; String 1
.asc "Nada, gracias.",0 ; String 2
res_end
.)

; Script 201
.(
.byt RESOURCE_SCRIPT|$80
.word (res_end-res_start +4)
.byt 201
res_start
+script_201_start
+l_map
; for
; Init part
.byt SC_ASSIGN, 64, 200	; i=9
.byt 9
; Condition
.byt SC_JUMP_IF, SF_NOT
.byt SF_LT
.byt SF_GETVAL,64, 200	; i
.byt 12
.word 33
; for body
.byt SC_ACTOR_TALK
.byt 11
.byt 64, 201
.byt SF_GETVAL,64, 200	; i
.byt SC_WAIT_FOR_ACTOR
.byt 11
; Increment expression
.byt SC_ASSIGN, 64, 200	; i=i+1
.byt SF_ADD
.byt SF_GETVAL,64, 200	; i
.byt 1
; end for
.byt SC_JUMP, 4, 0	; jump to 4
.byt SC_ACTIVATE_DLGOPT
.byt 0
.byt 0
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_GETFLAG,2	; bMetRavella
.byt 8
; then part
.byt SC_ACTIVATE_DLGOPT
.byt 1
.byt 1
.byt SC_START_DIALOG
.byt SC_STOP_SCRIPT
+l_exits
; for
; Init part
.byt SC_ASSIGN, 64, 200	; i=12
.byt 12
; Condition
.byt SC_JUMP_IF, SF_NOT
.byt SF_LE
.byt SF_GETVAL,64, 200	; i
.byt 16
.word 79
; for body
.byt SC_ACTOR_TALK
.byt 11
.byt 64, 201
.byt SF_GETVAL,64, 200	; i
.byt SC_WAIT_FOR_ACTOR
.byt 11
; Increment expression
.byt SC_ASSIGN, 64, 200	; i=i+1
.byt SF_ADD
.byt SF_GETVAL,64, 200	; i
.byt 1
; end for
.byt SC_JUMP, 50, 0	; jump to 50
.byt SC_SETFLAG, 3	; bMapContactGiven=true
.byt 1
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 201
.byt 17
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_SAVEGAME
+l_bye
.byt SC_ACTOR_TALK
.byt 11
.byt 64, 201
.byt 2
.byt SC_WAIT_FOR_ACTOR
.byt 11
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_NOT
.byt SF_GETFLAG,1	; bManTalkedBoutCoffee
.byt 64, 66
; then part
.byt SC_SETFLAG, 1	; bManTalkedBoutCoffee=true
.byt 1
.byt SC_DELAY
.byt 25
; for
; Init part
.byt SC_ASSIGN, 64, 200	; i=3
.byt 3
; Condition
.byt SC_JUMP_IF, SF_NOT
.byt SF_LT
.byt SF_GETVAL,64, 200	; i
.byt 6
.word 142
; for body
.byt SC_ACTOR_TALK
.byt 11
.byt 64, 201
.byt SF_GETVAL,64, 200	; i
.byt SC_WAIT_FOR_ACTOR
.byt 11
; Increment expression
.byt SC_ASSIGN, 64, 200	; i=i+1
.byt SF_ADD
.byt SF_GETVAL,64, 200	; i
.byt 1
; end for
.byt SC_JUMP, 113, 0	; jump to 113
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 201
.byt 6
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_ACTOR_TALK
.byt 11
.byt 64, 201
.byt 7
.byt SC_WAIT_FOR_ACTOR
.byt 11
.byt SC_ACTOR_TALK
.byt 11
.byt 64, 201
.byt 8
.byt SC_WAIT_FOR_ACTOR
.byt 11
.byt SC_FREEZE_SCRIPT
.byt 64, 202
.byt 0
.byt SC_END_DIALOG
.byt SC_STOP_SCRIPT
res_end
.)

; String pack 201
.(
.byt RESOURCE_STRING|$80
.word (res_end-res_start +4)
.byt 201
res_start
.asc "Parece encantado de ayudar.",0 ; String 0
.asc "Buenas, ",126,"qu",92," puedo hacer por usted?",0 ; String 1
.asc "Ning",95,"n problema. Tenga un buen d",93,"a.",0 ; String 2
.asc "Ah, por cierto, ",126,"sabe por casualidad",0 ; String 3
.asc "si han rellenado por fin la m",91,"quina",0 ; String 4
.asc "de caf",92," del pasillo?",0 ; String 5
.asc "No, lo siento.",0 ; String 6
.asc "Vaya. Mi turno acaba enseguida, pero",0 ; String 7
.asc "necesitaba una taza de caf",92,".",0 ; String 8
.asc "Lo siento, pero se me han acabado.",0 ; String 9
.asc "Me llegan m",91,"s ma",35,"ana.",0 ; String 10
.asc "",126,"Buscaba algo en particular?",0 ; String 11
.asc "Uy, eso no aparece en los mapas.",0 ; String 12
.asc "Son ",91,"reas de mantenimiento y est",91,"n",0 ; String 13
.asc "prohibidas para ciudadanos regulares.",0 ; String 14
.asc "Mmmm, pero conozco a alguien...",0 ; String 15
.asc "Pregunte en la puerta 4 del pasillo.",0 ; String 16
.asc "Vale. Gracias por todo.",0 ; String 17
.asc "No puedo aceptar regalos, se",35,"or.",0 ; String 18
res_end
.)
