;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Generated by OASIS compiler
; (c) Chema 2016
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


; Script 200
.(
.byt RESOURCE_SCRIPT|$80
.word (res_end-res_start +4)
.byt 200
res_start
+script_200_start
.byt SC_STOP_SCRIPT
res_end
.)

; Object Code 200
.(
.byt RESOURCE_OBJECTCODE|$80
.word (res_end-res_start +4)
.byt 200
res_start
; Response table
.byt VERB_WALKTO
.word (l_WalkTo-res_start)
.byt $ff ; End of response table
l_WalkTo
.byt SC_SET_OBJECT_POS
.byt SF_GET_ACTIONACTOR
.byt 45
.byt 14
.byt 64, 67
.byt SC_LOOK_DIRECTION
.byt SF_GET_ACTIONACTOR
.byt 3
.byt SC_CHANGE_ROOM_AND_STOP
.byt 45
.byt SC_STOP_SCRIPT
res_end
.)

; Object Code 201
.(
.byt RESOURCE_OBJECTCODE|$80
.word (res_end-res_start +4)
.byt 201
res_start
; Response table
.byt VERB_LOOKAT
.word (l_LookAt-res_start)
.byt VERB_TALKTO
.word (l_TalkTo-res_start)
.byt $ff ; End of response table
l_LookAt
.byt SC_ACTOR_TALK
.byt SF_GET_EGO
.byt 64, 200
.byt 0
.byt SC_STOP_SCRIPT
l_TalkTo
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_GETFLAG,64, 66	; bUniformTaken
.byt 12
; then part
.byt SC_ACTOR_TALK
.byt SF_GET_EGO
.byt 64, 200
.byt 10
.byt SC_STOP_SCRIPT
.byt SC_CURSOR_ON
.byt 0
.byt SC_SPAWN_SCRIPT
.byt 64, 201
.byt SC_PRINT
.byt 64, 200
.byt 2
.byt SC_DELAY
.byt 64, 120
.byt SC_PRINT
.byt 64, 200
.byt 3
.byt SC_DELAY
.byt 64, 120
.byt SC_PRINT
.byt 64, 200
.byt 1
.byt SC_TERMINATE_SCRIPT
.byt 64, 201
.byt SC_SET_ANIMSTATE
.byt 64, 201
.byt 0
.byt SC_CURSOR_ON
.byt 1
.byt SC_LOAD_DIALOG
.byt 64, 200
.byt SC_START_DIALOG
.byt SC_STOP_SCRIPT
res_end
.)

; Dialog 200
.(
.byt RESOURCE_DIALOG|$80
.word (res_end-res_start +4)
.byt 200
res_start
.byt 220	; Stringpack with options
.byt 220	; Script with response actions
.byt 1,0,0,1,$ff	; Active flags
.word (l_pickup-script_220_start),(l_nocode-script_220_start),(l_code-script_220_start),(l_bye-script_220_start)	; Jump labels
res_end
.)
; String pack for dialog 200
.(
.byt RESOURCE_STRING|$80
.word (res_end-res_start +4)
.byt 220
res_start
.asc "I want to pick up my clothes.",0 ; String 0
.asc "No. Is there anything I could do?",0 ; String 1
.asc "Yes, code is SP-1999-CH.",0 ; String 2
.asc "That's all, thank you. Bye.",0 ; String 3
res_end
.)

; Script 220
.(
.byt RESOURCE_SCRIPT|$80
.word (res_end-res_start +4)
.byt 220
res_start
+script_220_start
+l_pickup
.byt SC_WAIT_FOR_ACTOR
.byt SF_GET_EGO
.byt SC_SPAWN_SCRIPT
.byt 64, 201
.byt SC_PRINT
.byt 64, 200
.byt 5
.byt SC_DELAY
.byt 64, 120
.byt SC_PRINT
.byt 64, 200
.byt 1
.byt SC_TERMINATE_SCRIPT
.byt 64, 201
.byt SC_SET_ANIMSTATE
.byt 64, 201
.byt 0
.byt SC_ACTIVATE_DLGOPT
.byt 0
.byt 0
.byt SC_ACTIVATE_DLGOPT
.byt 1
.byt 1
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_GETFLAG,64, 65	; bLaundryMesgSeen
.byt 9
; then part
.byt SC_ACTIVATE_DLGOPT
.byt 2
.byt 1
l_common
.byt SC_START_DIALOG
.byt SC_STOP_SCRIPT
+l_nocode
.byt SC_WAIT_FOR_ACTOR
.byt SF_GET_EGO
.byt SC_SPAWN_SCRIPT
.byt 64, 201
.byt SC_PRINT
.byt 64, 200
.byt 6
.byt SC_DELAY
.byt 64, 120
.byt SC_PRINT
.byt 64, 200
.byt 7
.byt SC_DELAY
.byt 64, 120
.byt SC_PRINT
.byt 64, 200
.byt 8
.byt SC_DELAY
.byt 64, 120
.byt SC_PRINT
.byt 64, 200
.byt 1
.byt SC_TERMINATE_SCRIPT
.byt 64, 201
.byt SC_SET_ANIMSTATE
.byt 64, 201
.byt 0
.byt SC_JUMP
.word (l_bye1-res_start)
+l_code
.byt SC_WAIT_FOR_ACTOR
.byt SF_GET_EGO
.byt SC_SPAWN_SCRIPT
.byt 64, 201
.byt SC_PRINT
.byt 64, 200
.byt 9
.byt SC_DELAY
.byt 64, 120
.byt SC_TERMINATE_SCRIPT
.byt 64, 201
.byt SC_SETFLAG, 64, 66	; bUniformTaken=true
.byt 1
.byt SC_PUT_IN_INVENTORY
.byt 50
.byt SC_SAVEGAME
+l_bye
l_bye1
.byt SC_WAIT_FOR_ACTOR
.byt SF_GET_EGO
.byt SC_SPAWN_SCRIPT
.byt 64, 201
.byt SC_PRINT
.byt 64, 200
.byt 4
.byt SC_DELAY
.byt 64, 120
.byt SC_PRINT
.byt 64, 200
.byt 1
.byt SC_TERMINATE_SCRIPT
.byt 64, 201
.byt SC_SET_ANIMSTATE
.byt 64, 201
.byt 0
.byt SC_END_DIALOG
.byt SC_STOP_SCRIPT
res_end
.)

; Script 201
.(
.byt RESOURCE_SCRIPT|$80
.word (res_end-res_start +4)
.byt 201
res_start
+script_201_start
.byt SC_SET_ANIMSTATE
.byt 64, 201
.byt 1
.byt SC_DELAY
.byt SF_GETRANDINT
.byt 1
.byt 6
.byt SC_SET_ANIMSTATE
.byt 64, 201
.byt 0
.byt SC_DELAY
.byt SF_GETRANDINT
.byt 1
.byt 6
.byt SC_RESTART_SCRIPT
.byt SC_STOP_SCRIPT
res_end
.)

; String pack 200
.(
.byt RESOURCE_STRING|$80
.word (res_end-res_start +4)
.byt 200
res_start
.asc "A strange robot is at the counter.",0 ; String 0
.asc " ",0 ; String 1
.asc " Welcome to Fresh Laundry, sir.",0 ; String 2
.asc " What can I do for you?",0 ; String 3
.asc " At your service. Have a nice day.",0 ; String 4
.asc " Sure, do you have the code?",0 ; String 5
.asc " Sorry.",0 ; String 6
.asc " Check your personnal messages,",0 ; String 7
.asc " you should have received the code.",0 ; String 8
.asc " Sure, sir. Here it is.",0 ; String 9
.asc "I don't need anything from him.",0 ; String 10
res_end
.)
