;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Generated by OASIS compiler
; (c) Chema 2016
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


; Script 200
.(
.byt RESOURCE_SCRIPT|$80
.word (res_end-res_start +4)
.byt 200
res_start
+script_200_start
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_NOT
.byt SF_GETFLAG,64, 72	; bDroneTaken
.byt 9
; then part
.byt SC_LOAD_OBJECT
.byt 28
.byt SC_STOP_SCRIPT
res_end
.)

; Script 201
.(
.byt RESOURCE_SCRIPT|$80
.word (res_end-res_start +4)
.byt 201
res_start
+script_201_start
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_NOT
.byt SF_GETFLAG,64, 72	; bDroneTaken
.byt 9
; then part
.byt SC_REMOVE_OBJECT
.byt 28
.byt SC_STOP_SCRIPT
res_end
.)

; Object Code 200
.(
.byt RESOURCE_OBJECTCODE|$80
.word (res_end-res_start +4)
.byt 200
res_start
; Response table
.byt VERB_USE
.word (l_Use-res_start)
.byt VERB_WALKTO
.word (l_WalkTo-res_start)
.byt $ff ; End of response table
l_Use
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_NOT, SF_EQ
.byt SF_GET_ACTIONOBJ2
.byt 64, 255
.byt 11
; then part
.byt SC_SPAWN_SCRIPT
.byt 1
.byt SC_STOP_SCRIPT
l_WalkTo
.byt SC_SET_OBJECT_POS
.byt SF_GET_ACTIONACTOR
.byt 20
.byt 12
.byt 34
.byt SC_LOOK_DIRECTION
.byt SF_GET_ACTIONACTOR
.byt 1
.byt SC_CHANGE_ROOM_AND_STOP
.byt 20
.byt SC_STOP_SCRIPT
res_end
.)

; String pack 200
.(
.byt RESOURCE_STRING|$80
.word (res_end-res_start +4)
.byt 200
res_start
.asc "An elastic tie down strap.",0 ; String 0
.asc "It is used to hold down the cargo.",0 ; String 1
.asc "Let me see if I can cut a piece...",0 ; String 2
.asc "How do you want me to use it?",0 ; String 3
.asc "The strap is fastened and I can't break",0 ; String 4
.asc "it with my bare hands",0 ; String 5
.asc "A compartment with spare energy cells.",0 ; String 6
.asc "Okay, I'll take one.",0 ; String 7
.asc "I don't need it.",0 ; String 8
res_end
.)

; Object Code 201
.(
.byt RESOURCE_OBJECTCODE|$80
.word (res_end-res_start +4)
.byt 201
res_start
; Response table
.byt VERB_LOOKAT
.word (l_LookAt-res_start)
.byt VERB_PICKUP
.word (l_PickUp-res_start)
.byt VERB_USE
.word (l_Use-res_start)
.byt $ff ; End of response table
l_LookAt
.byt SC_ASSIGN, 64, 200	; a=sfGetActorExecutingAction()
.byt SF_GET_ACTIONACTOR
.byt SC_CURSOR_ON
.byt 0
.byt SC_ACTOR_TALK
.byt SF_GETVAL,64, 200	; a
.byt 64, 200
.byt 0
.byt SC_WAIT_FOR_ACTOR
.byt SF_GETVAL,64, 200	; a
.byt SC_ACTOR_TALK
.byt SF_GETVAL,64, 200	; a
.byt 64, 200
.byt 1
.byt SC_WAIT_FOR_ACTOR
.byt SF_GETVAL,64, 200	; a
.byt SC_CURSOR_ON
.byt 1
.byt SC_STOP_SCRIPT
l_PickUp
.byt SC_ASSIGN, 64, 200	; a=sfGetActorExecutingAction()
.byt SF_GET_ACTIONACTOR
.byt SC_CURSOR_ON
.byt 0
.byt SC_ACTOR_TALK
.byt SF_GETVAL,64, 200	; a
.byt 64, 200
.byt 4
.byt SC_WAIT_FOR_ACTOR
.byt SF_GETVAL,64, 200	; a
.byt SC_ACTOR_TALK
.byt SF_GETVAL,64, 200	; a
.byt 64, 200
.byt 5
.byt SC_WAIT_FOR_ACTOR
.byt SF_GETVAL,64, 200	; a
.byt SC_CURSOR_ON
.byt 1
.byt SC_STOP_SCRIPT
l_Use
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_AND
.byt SF_EQ
.byt SF_GET_ACTIONOBJ1
.byt 38
.byt SF_NOT
.byt SF_GETFLAG,33	; bBandCut
.byt 25
; then part
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 2
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_PUT_IN_INVENTORY
.byt 33
.byt SC_SETFLAG, 33	; bBandCut=true
.byt 1
.byt SC_SAVEGAME
.byt SC_JUMP_REL, 10
; else part
.byt SC_LOOK_DIRECTION
.byt SF_GET_ACTIONACTOR
.byt 3
.byt SC_ACTOR_TALK
.byt SF_GET_ACTIONACTOR
.byt 64, 200
.byt 3
.byt SC_STOP_SCRIPT
res_end
.)

; Object Code 202
.(
.byt RESOURCE_OBJECTCODE|$80
.word (res_end-res_start +4)
.byt 202
res_start
; Response table
.byt VERB_LOOKAT
.word (l_LookAt-res_start)
.byt VERB_USE
.word (l_Use-res_start)
.byt VERB_OPEN
.word (l_Open-res_start)
.byt VERB_PICKUP
.word (l_PickUp-res_start)
.byt $ff ; End of response table
l_LookAt
.byt SC_ACTOR_TALK
.byt SF_GET_ACTIONACTOR
.byt 64, 200
.byt 6
.byt SC_WAIT_FOR_ACTOR
.byt SF_GET_ACTIONACTOR
.byt SC_SETFLAG, 47	; bEnergyCellSeen=true
.byt 1
.byt SC_STOP_SCRIPT
l_Use
l_Open
l_PickUp
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_NOT
.byt SF_GETFLAG,47	; bEnergyCellSeen
.byt 16
; then part
.byt SC_ACTOR_TALK
.byt SF_GET_ACTIONACTOR
.byt 64, 200
.byt 6
.byt SC_WAIT_FOR_ACTOR
.byt SF_GET_ACTIONACTOR
.byt SC_SETFLAG, 47	; bEnergyCellSeen=true
.byt 1
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_GETFLAG,48	; bEnergyCellTaken
.byt 14
; then part
.byt SC_ACTOR_TALK
.byt SF_GET_ACTIONACTOR
.byt 64, 200
.byt 8
.byt SC_WAIT_FOR_ACTOR
.byt SF_GET_ACTIONACTOR
.byt SC_JUMP_REL, 15
; else part
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 7
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_PUT_IN_INVENTORY
.byt 52
.byt SC_SETFLAG, 48	; bEnergyCellTaken=true
.byt 1
.byt SC_SAVEGAME
.byt SC_STOP_SCRIPT
res_end
.)
