;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Generated by OASIS compiler
; (c) Chema 2016
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


; Object Code 200
.(
.byt RESOURCE_OBJECTCODE|$80
.word (res_end-res_start +4)
.byt 200
res_start
; Response table
.byt VERB_WALKTO
.word (l_WalkTo-res_start)
.byt $ff ; End of response table
l_WalkTo
.byt SC_SET_OBJECT_POS
.byt SF_GET_ACTIONACTOR
.byt 21
.byt 15
.byt 34
.byt SC_LOOK_DIRECTION
.byt SF_GET_ACTIONACTOR
.byt 1
.byt SC_CHANGE_ROOM_AND_STOP
.byt 21
.byt SC_STOP_SCRIPT
res_end
.)

; Object Code 201
.(
.byt RESOURCE_OBJECTCODE|$80
.word (res_end-res_start +4)
.byt 201
res_start
; Response table
.byt VERB_WALKTO
.word (l_WalkTo-res_start)
.byt $ff ; End of response table
l_WalkTo
.byt SC_SET_OBJECT_POS
.byt SF_GET_ACTIONACTOR
.byt 25
.byt 15
.byt 1
.byt SC_CHANGE_ROOM_AND_STOP
.byt 25
.byt SC_STOP_SCRIPT
res_end
.)

; Object Code 202
.(
.byt RESOURCE_OBJECTCODE|$80
.word (res_end-res_start +4)
.byt 202
res_start
; Response table
.byt VERB_WALKTO
.word (l_WalkTo-res_start)
.byt $ff ; End of response table
l_WalkTo
.byt SC_SET_OBJECT_POS
.byt SF_GET_ACTIONACTOR
.byt 22
.byt 14
.byt 2
.byt SC_LOOK_DIRECTION
.byt SF_GET_ACTIONACTOR
.byt 0
.byt SC_CHANGE_ROOM_AND_STOP
.byt 22
.byt SC_STOP_SCRIPT
res_end
.)

; String pack 200
.(
.byt RESOURCE_STRING|$80
.word (res_end-res_start +4)
.byt 200
res_start
.asc "Strange interior... Impressive.",0 ; String 0
.asc "Could we refuse to do this?",0 ; String 1
.asc "The alternative is summary execution.",0 ; String 2
.asc "I've had worse offers...",0 ; String 3
.asc "Execution may have some appeal.",0 ; String 4
.asc "Okay, let's go",0 ; String 5
res_end
.)
