;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Generated by OASIS compiler
; (c) Chema 2016
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


; Script 200
.(
.byt RESOURCE_SCRIPT|$80
.word (res_end-res_start +4)
.byt 200
res_start
+script_200_start
.byt SC_LOAD_OBJECT
.byt 22
.byt SC_SET_OBJECT_POS
.byt 0
.byt 17
.byt 14
.byt 7
.byt SC_SET_OBJECT_POS
.byt 22
.byt 17
.byt 15
.byt 4
.byt SC_LOOK_DIRECTION
.byt 22
.byt 0
.byt SC_LOOK_DIRECTION
.byt 0
.byt 0
.byt SC_SPAWN_SCRIPT
.byt 64, 201
.byt SC_STOP_SCRIPT
res_end
.)

; Script 201
.(
.byt RESOURCE_SCRIPT|$80
.word (res_end-res_start +4)
.byt 201
res_start
+script_201_start
.byt SC_DELAY
.byt 20
; for
; Init part
.byt SC_ASSIGN, 64, 200	; i=0
.byt 0
; Condition
.byt SC_JUMP_IF, SF_NOT
.byt SF_LT
.byt SF_GETVAL,64, 200	; i
.byt 6
.word 114
; for body
.byt SC_ACTOR_TALK
.byt 22
.byt 64, 200
.byt SF_GETVAL,64, 200	; i
.byt SC_WAIT_FOR_ACTOR
.byt 22
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 0
.byt 17
; then part
.byt SC_ACTOR_WALKTO
.byt 22
.byt 19
.byt 14
.byt SC_WAIT_FOR_ACTOR
.byt 22
.byt SC_LOOK_DIRECTION
.byt 22
.byt 2
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt SF_ADD
.byt SF_GETVAL,64, 200	; i
.byt 1
.byt SC_WAIT_FOR_ACTOR
.byt 0
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 0
.byt 19
; then part
.byt SC_LOAD_OBJECT
.byt 64, 201
.byt SC_PLAYSFX
.byt 3
.byt SC_DELAY
.byt 10
.byt SC_SET_ANIMSTATE
.byt 64, 201
.byt 1
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 2
.byt 32
; then part
.byt SC_DELAY
.byt 50
.byt SC_PLAYSFX
.byt 5
.byt SC_DELAY
.byt 5
.byt SC_PLAYSFX
.byt 5
.byt SC_ACTOR_WALKTO
.byt 22
.byt 23
.byt 15
.byt SC_WAIT_FOR_ACTOR
.byt 22
.byt SC_LOOK_DIRECTION
.byt 22
.byt 0
.byt SC_DELAY
.byt 50
.byt SC_LOOK_DIRECTION
.byt 22
.byt 1
.byt SC_PLAYSFX
.byt 6
; Increment expression
.byt SC_ASSIGN, 64, 200	; i=i+2
.byt SF_ADD
.byt SF_GETVAL,64, 200	; i
.byt 2
; end for
.byt SC_JUMP, 6, 0	; jump to 6
.byt SC_DELAY
.byt 30
.byt SC_PLAYSFX
.byt 4
.byt SC_LOAD_OBJECT
.byt 64, 200
.byt SC_SET_ANIMSTATE
.byt 64, 200
.byt 0
.byt SC_SPAWN_SCRIPT
.byt 64, 210
; for
; Init part
.byt SC_ASSIGN, 64, 200	; i=6
.byt 6
; Condition
.byt SC_JUMP_IF, SF_NOT
.byt SF_LT
.byt SF_GETVAL,64, 200	; i
.byt 10
.word 177
; for body
.byt SC_PRINT
.byt 64, 200
.byt SF_GETVAL,64, 200	; i
.byt SC_DELAY
.byt 64, 120
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 6
.byt 16
; then part
.byt SC_ACTOR_WALKTO
.byt 0
.byt 8
.byt 14
.byt SC_ACTOR_WALKTO
.byt 22
.byt 18
.byt 15
; Increment expression
.byt SC_ASSIGN, 64, 200	; i=i+1
.byt SF_ADD
.byt SF_GETVAL,64, 200	; i
.byt 1
; end for
.byt SC_JUMP, 132, 0	; jump to 132
.byt SC_TERMINATE_SCRIPT
.byt 64, 210
.byt SC_SET_ANIMSTATE
.byt 64, 200
.byt 0
.byt SC_DELAY
.byt 30
; for
; Init part
.byt SC_ASSIGN, 64, 200	; i=10
.byt 10
; Condition
.byt SC_JUMP_IF, SF_NOT
.byt SF_LT
.byt SF_GETVAL,64, 200	; i
.byt 20
.word 241
; for body
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt SF_GETVAL,64, 200	; i
.byt SC_WAIT_FOR_ACTOR
.byt 0
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_OR
.byt SF_OR
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 13
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 14
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 10
.byt 22
; then part
.byt SC_DELAY
.byt 50
; Increment expression
.byt SC_ASSIGN, 64, 200	; i=i+1
.byt SF_ADD
.byt SF_GETVAL,64, 200	; i
.byt 1
; end for
.byt SC_JUMP, 190, 0	; jump to 190
.byt SC_DELAY
.byt 50
.byt SC_SPAWN_SCRIPT
.byt 64, 210
; for
; Init part
.byt SC_ASSIGN, 64, 200	; i=20
.byt 20
; Condition
.byt SC_JUMP_IF, SF_NOT
.byt SF_LT
.byt SF_GETVAL,64, 200	; i
.byt 26
.word 279
; for body
.byt SC_PRINT
.byt 64, 200
.byt SF_GETVAL,64, 200	; i
.byt SC_DELAY
.byt 64, 120
; Increment expression
.byt SC_ASSIGN, 64, 200	; i=i+1
.byt SF_ADD
.byt SF_GETVAL,64, 200	; i
.byt 1
; end for
.byt SC_JUMP, 250, 0	; jump to 250
.byt SC_TERMINATE_SCRIPT
.byt 64, 210
.byt SC_SET_ANIMSTATE
.byt 64, 200
.byt 0
.byt SC_REMOVE_OBJECT
.byt 64, 200
.byt SC_PLAYSFX
.byt 4
.byt SC_DELAY
.byt 30
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 26
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_DELAY
.byt 20
.byt SC_LOOK_DIRECTION
.byt 0
.byt 1
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 27
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_ACTOR_TALK
.byt 22
.byt 64, 200
.byt 28
.byt SC_WAIT_FOR_ACTOR
.byt 22
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 29
.byt SC_WAIT_FOR_ACTOR
.byt 0
; for
; Init part
.byt SC_ASSIGN, 64, 200	; i=30
.byt 30
; Condition
.byt SC_JUMP_IF, SF_NOT
.byt SF_LT
.byt SF_GETVAL,64, 200	; i
.byt 36
.word 359
; for body
.byt SC_ACTOR_TALK
.byt 22
.byt 64, 200
.byt SF_GETVAL,64, 200	; i
.byt SC_WAIT_FOR_ACTOR
.byt 22
; Increment expression
.byt SC_ASSIGN, 64, 200	; i=i+1
.byt SF_ADD
.byt SF_GETVAL,64, 200	; i
.byt 1
; end for
.byt SC_JUMP, 74, 1	; jump to 330
.byt SC_LOOK_DIRECTION
.byt 0
.byt 0
.byt SC_DELAY
.byt 20
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 36
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_ACTOR_TALK
.byt 22
.byt 64, 200
.byt 37
.byt SC_WAIT_FOR_ACTOR
.byt 22
.byt SC_ACTOR_TALK
.byt 22
.byt 64, 200
.byt 38
.byt SC_WAIT_FOR_ACTOR
.byt 22
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 39
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_ACTOR_TALK
.byt 22
.byt 64, 200
.byt 40
.byt SC_WAIT_FOR_ACTOR
.byt 22
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 41
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_PLAYSFX
.byt 8
.byt SC_DELAY
.byt 64, 70
.byt SC_BWPALETTE
.byt SC_DELAY
.byt 64, 70
.byt SC_CLEAR_ROOMAREA
.byt SC_CHANGE_ROOM_AND_STOP
.byt 18
.byt SC_STOP_SCRIPT
res_end
.)

; String pack 200
.(
.byt RESOURCE_STRING|$80
.word (res_end-res_start +4)
.byt 200
res_start
.asc "Okay, let's do it.",0 ; String 0
.asc "Lock the door!",0 ; String 1
.asc "Sure. Done.",0 ; String 2
.asc "Hurry up!",0 ; String 3
.asc "The computer is under our control.",0 ; String 4
.asc "Let's wait for news from the others.",0 ; String 5
.asc " Blake, this is Commander Leylan.",0 ; String 6
.asc " We have arrested your gang.",0 ; String 7
.asc " Your plan is a failure. Surrender now,",0 ; String 8
.asc " and you'll be treated leniently.",0 ; String 9
.asc "Those are your terms?            ",0 ; String 10
.asc "These are mine. You will hand over all",0 ; String 11
.asc "your weapons to my men. Whilst we hold",0 ; String 12
.asc "the computer, the ship is helpless.",0 ; String 13
.asc "It'll remain that way until you agree.",0 ; String 14
.asc "You will then fly this ship to the",0 ; String 15
.asc "nearest habitable planet where we will",0 ; String 16
.asc "disembark. Any attempt by your men to",0 ; String 17
.asc "break into this room and we'll destroy",0 ; String 18
.asc "the computer. Totally. That's all.",0 ; String 19
.asc " Nice try. But listen.",0 ; String 20
.asc " I'm going to kill one of your friends",0 ; String 21
.asc " every thirty seconds starting now.",0 ; String 22
.asc " I'll stop when you give yourselves up,",0 ; String 23
.asc " or I run out of prisoners.",0 ; String 24
.asc " The talking's over, Blake.",0 ; String 25
.asc "You can't do that! Leylan!",0 ; String 26
.asc "I've failed. Let's open the door.",0 ; String 27
.asc "You're throwing away our only chance.",0 ; String 28
.asc "Open the door!",0 ; String 29
.asc "What a fiasco. You could take over the",0 ; String 30
.asc "ship, you said, if I did my bit.",0 ; String 31
.asc "Well, I did my bit, and what happened?",0 ; String 32
.asc "Your troops bumble around looking for",0 ; String 33
.asc "someone to surrender to, and when",0 ; String 34
.asc "they've succeeded, you follow suit.",0 ; String 35
.asc "I'll try and do better next time.",0 ; String 36
.asc "We had one chance. You wasted it.",0 ; String 37
.asc "There won't be a next time.",0 ; String 38
.asc "In which case, you can die content.",0 ; String 39
.asc "Content...",0 ; String 40
.asc "Knowing you were right.",0 ; String 41
res_end
.)

; Script 210
.(
.byt RESOURCE_SCRIPT|$80
.word (res_end-res_start +4)
.byt 210
res_start
+script_210_start
.byt SC_DELAY
.byt 5
.byt SC_SET_ANIMSTATE
.byt 64, 200
.byt SF_GETRANDINT
.byt 0
.byt 2
.byt SC_DELAY
.byt 3
.byt SC_DELAY
.byt SF_GETRANDINT
.byt 1
.byt 3
.byt SC_SET_ANIMSTATE
.byt 64, 200
.byt 0
.byt SC_RESTART_SCRIPT
.byt SC_STOP_SCRIPT
res_end
.)
