;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Generated by OASIS compiler
; (c) Chema 2016
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


; Script 200
.(
.byt RESOURCE_SCRIPT|$80
.word (res_end-res_start +4)
.byt 200
res_start
+script_200_start
.byt SC_LOAD_OBJECT
.byt 22
.byt SC_SET_OBJECT_POS
.byt 0
.byt 17
.byt 14
.byt 7
.byt SC_SET_OBJECT_POS
.byt 22
.byt 17
.byt 15
.byt 4
.byt SC_LOOK_DIRECTION
.byt 22
.byt 0
.byt SC_LOOK_DIRECTION
.byt 0
.byt 0
.byt SC_SPAWN_SCRIPT
.byt 64, 201
.byt SC_STOP_SCRIPT
res_end
.)

; Script 201
.(
.byt RESOURCE_SCRIPT|$80
.word (res_end-res_start +4)
.byt 201
res_start
+script_201_start
.byt SC_DELAY
.byt 20
; for
; Init part
.byt SC_ASSIGN, 64, 200	; i=0
.byt 0
; Condition
.byt SC_JUMP_IF, SF_NOT
.byt SF_LT
.byt SF_GETVAL,64, 200	; i
.byt 6
.word 114
; for body
.byt SC_ACTOR_TALK
.byt 22
.byt 64, 200
.byt SF_GETVAL,64, 200	; i
.byt SC_WAIT_FOR_ACTOR
.byt 22
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 0
.byt 17
; then part
.byt SC_ACTOR_WALKTO
.byt 22
.byt 19
.byt 14
.byt SC_WAIT_FOR_ACTOR
.byt 22
.byt SC_LOOK_DIRECTION
.byt 22
.byt 2
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt SF_ADD
.byt SF_GETVAL,64, 200	; i
.byt 1
.byt SC_WAIT_FOR_ACTOR
.byt 0
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 0
.byt 19
; then part
.byt SC_LOAD_OBJECT
.byt 64, 201
.byt SC_PLAYSFX
.byt 3
.byt SC_DELAY
.byt 10
.byt SC_SET_ANIMSTATE
.byt 64, 201
.byt 1
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 2
.byt 32
; then part
.byt SC_DELAY
.byt 50
.byt SC_PLAYSFX
.byt 5
.byt SC_DELAY
.byt 5
.byt SC_PLAYSFX
.byt 5
.byt SC_ACTOR_WALKTO
.byt 22
.byt 23
.byt 15
.byt SC_WAIT_FOR_ACTOR
.byt 22
.byt SC_LOOK_DIRECTION
.byt 22
.byt 0
.byt SC_DELAY
.byt 50
.byt SC_LOOK_DIRECTION
.byt 22
.byt 1
.byt SC_PLAYSFX
.byt 6
; Increment expression
.byt SC_ASSIGN, 64, 200	; i=i+2
.byt SF_ADD
.byt SF_GETVAL,64, 200	; i
.byt 2
; end for
.byt SC_JUMP, 6, 0	; jump to 6
.byt SC_DELAY
.byt 30
.byt SC_PLAYSFX
.byt 4
.byt SC_LOAD_OBJECT
.byt 64, 200
.byt SC_SET_ANIMSTATE
.byt 64, 200
.byt 0
.byt SC_SPAWN_SCRIPT
.byt 64, 210
; for
; Init part
.byt SC_ASSIGN, 64, 200	; i=6
.byt 6
; Condition
.byt SC_JUMP_IF, SF_NOT
.byt SF_LT
.byt SF_GETVAL,64, 200	; i
.byt 10
.word 177
; for body
.byt SC_PRINT
.byt 64, 200
.byt SF_GETVAL,64, 200	; i
.byt SC_DELAY
.byt 64, 120
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 6
.byt 16
; then part
.byt SC_ACTOR_WALKTO
.byt 0
.byt 8
.byt 14
.byt SC_ACTOR_WALKTO
.byt 22
.byt 18
.byt 15
; Increment expression
.byt SC_ASSIGN, 64, 200	; i=i+1
.byt SF_ADD
.byt SF_GETVAL,64, 200	; i
.byt 1
; end for
.byt SC_JUMP, 132, 0	; jump to 132
.byt SC_TERMINATE_SCRIPT
.byt 64, 210
.byt SC_SET_ANIMSTATE
.byt 64, 200
.byt 0
.byt SC_DELAY
.byt 30
; for
; Init part
.byt SC_ASSIGN, 64, 200	; i=10
.byt 10
; Condition
.byt SC_JUMP_IF, SF_NOT
.byt SF_LT
.byt SF_GETVAL,64, 200	; i
.byt 20
.word 241
; for body
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt SF_GETVAL,64, 200	; i
.byt SC_WAIT_FOR_ACTOR
.byt 0
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_OR
.byt SF_OR
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 13
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 14
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 10
.byt 22
; then part
.byt SC_DELAY
.byt 50
; Increment expression
.byt SC_ASSIGN, 64, 200	; i=i+1
.byt SF_ADD
.byt SF_GETVAL,64, 200	; i
.byt 1
; end for
.byt SC_JUMP, 190, 0	; jump to 190
.byt SC_DELAY
.byt 50
.byt SC_SPAWN_SCRIPT
.byt 64, 210
; for
; Init part
.byt SC_ASSIGN, 64, 200	; i=20
.byt 20
; Condition
.byt SC_JUMP_IF, SF_NOT
.byt SF_LT
.byt SF_GETVAL,64, 200	; i
.byt 26
.word 279
; for body
.byt SC_PRINT
.byt 64, 200
.byt SF_GETVAL,64, 200	; i
.byt SC_DELAY
.byt 64, 120
; Increment expression
.byt SC_ASSIGN, 64, 200	; i=i+1
.byt SF_ADD
.byt SF_GETVAL,64, 200	; i
.byt 1
; end for
.byt SC_JUMP, 250, 0	; jump to 250
.byt SC_TERMINATE_SCRIPT
.byt 64, 210
.byt SC_SET_ANIMSTATE
.byt 64, 200
.byt 0
.byt SC_REMOVE_OBJECT
.byt 64, 200
.byt SC_PLAYSFX
.byt 4
.byt SC_DELAY
.byt 30
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 26
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_DELAY
.byt 20
.byt SC_LOOK_DIRECTION
.byt 0
.byt 1
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 27
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_ACTOR_TALK
.byt 22
.byt 64, 200
.byt 28
.byt SC_WAIT_FOR_ACTOR
.byt 22
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 29
.byt SC_WAIT_FOR_ACTOR
.byt 0
; for
; Init part
.byt SC_ASSIGN, 64, 200	; i=30
.byt 30
; Condition
.byt SC_JUMP_IF, SF_NOT
.byt SF_LT
.byt SF_GETVAL,64, 200	; i
.byt 36
.word 359
; for body
.byt SC_ACTOR_TALK
.byt 22
.byt 64, 200
.byt SF_GETVAL,64, 200	; i
.byt SC_WAIT_FOR_ACTOR
.byt 22
; Increment expression
.byt SC_ASSIGN, 64, 200	; i=i+1
.byt SF_ADD
.byt SF_GETVAL,64, 200	; i
.byt 1
; end for
.byt SC_JUMP, 74, 1	; jump to 330
.byt SC_LOOK_DIRECTION
.byt 0
.byt 0
.byt SC_DELAY
.byt 20
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 36
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_ACTOR_TALK
.byt 22
.byt 64, 200
.byt 37
.byt SC_WAIT_FOR_ACTOR
.byt 22
.byt SC_ACTOR_TALK
.byt 22
.byt 64, 200
.byt 38
.byt SC_WAIT_FOR_ACTOR
.byt 22
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 39
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_ACTOR_TALK
.byt 22
.byt 64, 200
.byt 40
.byt SC_WAIT_FOR_ACTOR
.byt 22
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 41
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_PLAYSFX
.byt 8
.byt SC_DELAY
.byt 64, 70
.byt SC_BWPALETTE
.byt SC_DELAY
.byt 64, 70
.byt SC_CLEAR_ROOMAREA
.byt SC_CHANGE_ROOM_AND_STOP
.byt 18
.byt SC_STOP_SCRIPT
res_end
.)

; String pack 200
.(
.byt RESOURCE_STRING|$80
.word (res_end-res_start +4)
.byt 200
res_start
.asc "Venga. Vamos a hacerlo.",0 ; String 0
.asc "",125,"Cierra la puerta!",0 ; String 1
.asc "Listo.",0 ; String 2
.asc "",125,"Deprisa!",0 ; String 3
.asc "La computadora es nuestra.",0 ; String 4
.asc "Esperemos noticias del resto.",0 ; String 5
.asc " Blake, soy el Comandante Leylan.",0 ; String 6
.asc " Hemos arrestado a tu banda.",0 ; String 7
.asc " Tu plan es un fracaso, r",93,"ndete",0 ; String 8
.asc " y ser",91,"s tratado con indulgencia.",0 ; String 9
.asc "Esos son tus t",92,"rminos?           ",0 ; String 10
.asc "Estos los m",93,"os. Entregar",91,"s las armas",0 ; String 11
.asc "a mis hombres. Mientras controlemos la",0 ; String 12
.asc "computadora, la nave est",91," perdida.",0 ; String 13
.asc "Y as",93," estar",91," hasta que cedas.",0 ; String 14
.asc "Luego nos llevar",91,"s al planeta m",91,"s",0 ; String 15
.asc "cercano donde podamos desembarcar.",0 ; String 16
.asc "Si intentan entrar tus hombres aqu",93,",",0 ; String 17
.asc "destruiremos la computadora.",0 ; String 18
.asc "Totalmente. Eso es todo.",0 ; String 19
.asc " Buen intento. Pero escucha.",0 ; String 20
.asc " Voy a matar a uno de tus amigos cada",0 ; String 21
.asc " treinta segundos desde ahora.",0 ; String 22
.asc " Parar",92," cuando os rind",91,"is o me quede,",0 ; String 23
.asc " sin prisioneros.",0 ; String 24
.asc " Se acab",94," la conversaci",94,"n, Blake.",0 ; String 25
.asc "",125,"No puedes hacer eso! Leylan!    ",0 ; String 26
.asc "He fallado. Abre.",0 ; String 27
.asc "",126,"Y perder nuestra ",95,"nica oportunidad?",0 ; String 28
.asc "",125,"Abre la puerta!",0 ; String 29
.asc "Qu",92," fiasco. Pod",93,"as hacerte con la nave",0 ; String 30
.asc "dijiste, si hac",93,"a mi parte.",0 ; String 31
.asc "Lo hice y ",126,"qu",92," pas",94,"?",0 ; String 32
.asc "Tus tropas van de ac",91," para all",91,"",0 ; String 33
.asc "buscando alguien a quien rendirse y",0 ; String 34
.asc "cuando lo consiguen, tu vas detr",91,"s.",0 ; String 35
.asc "Intentar",92," hacerlo mejor a la pr",94,"xima.",0 ; String 36
.asc "Hubo una oportunidad. Desperdiciada.",0 ; String 37
.asc "No habr",91," otra.",0 ; String 38
.asc "En ese caso podr",91,"s morir contento.",0 ; String 39
.asc "Contento...",0 ; String 40
.asc "Sabiendo que ten",93,"as raz",94,"n.",0 ; String 41
res_end
.)

; Script 210
.(
.byt RESOURCE_SCRIPT|$80
.word (res_end-res_start +4)
.byt 210
res_start
+script_210_start
.byt SC_DELAY
.byt 5
.byt SC_SET_ANIMSTATE
.byt 64, 200
.byt SF_GETRANDINT
.byt 0
.byt 2
.byt SC_DELAY
.byt 3
.byt SC_DELAY
.byt SF_GETRANDINT
.byt 1
.byt 3
.byt SC_SET_ANIMSTATE
.byt 64, 200
.byt 0
.byt SC_RESTART_SCRIPT
.byt SC_STOP_SCRIPT
res_end
.)
