;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Generated by OASIS compiler
; (c) Chema 2016
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


; Dialog 200
.(
.byt RESOURCE_DIALOG|$80
.word (res_end-res_start +4)
.byt 200
res_start
.byt 220	; Stringpack with options
.byt 220	; Script with response actions
.byt 1,1,1,1,0,0,0,0,$ff	; Active flags
.word (l_family-script_220_start),(l_food-script_220_start),(l_book-script_220_start),(l_exit1-script_220_start),(l_skeptic-script_220_start),(l_skeptic-script_220_start),(l_air-script_220_start),(l_bye-script_220_start)	; Jump labels
res_end
.)
; String pack for dialog 200
.(
.byt RESOURCE_STRING|$80
.word (res_end-res_start +4)
.byt 220
res_start
.asc "Dijiste que sab",93,"as algo de mi familia.",0 ; String 0
.asc "No he comido nada en 36 horas.",0 ; String 1
.asc "Recib",93," el libro que me enviaste.",0 ; String 2
.asc "Un segundo. Vengo ahora.",0 ; String 3
.asc "",126,"Es esto alg",95,"n tipo de broma pesada?",0 ; String 4
.asc "Otra vez no...",0 ; String 5
.asc "",125,"Pero el aire fuera es letal!",0 ; String 6
.asc "Entoces nos vemos luego.",0 ; String 7
res_end
.)

; Script 220
.(
.byt RESOURCE_SCRIPT|$80
.word (res_end-res_start +4)
.byt 220
res_start
+script_220_start
+l_family
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_ACTOR_TALK
.byt 64, 250
.byt 64, 221
.byt 7
.byt SC_WAIT_FOR_ACTOR
.byt 64, 250
.byt SC_ACTOR_TALK
.byt 64, 250
.byt 64, 221
.byt 8
.byt SC_WAIT_FOR_ACTOR
.byt 64, 250
.byt SC_ACTIVATE_DLGOPT
.byt 0
.byt 0
.byt SC_JUMP
.word (l_common-res_start)
+l_food
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_ACTOR_TALK
.byt 64, 250
.byt 64, 221
.byt 4
.byt SC_WAIT_FOR_ACTOR
.byt 64, 250
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 221
.byt 3
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_ACTOR_TALK
.byt 64, 250
.byt 64, 221
.byt 5
.byt SC_WAIT_FOR_ACTOR
.byt 64, 250
.byt SC_ACTOR_TALK
.byt 64, 250
.byt 64, 221
.byt 6
.byt SC_WAIT_FOR_ACTOR
.byt 64, 250
.byt SC_ACTIVATE_DLGOPT
.byt 1
.byt 0
l_act_skeptic
.byt SC_ACTIVATE_DLGOPT
.byt 4
.byt 1
.byt SC_ACTIVATE_DLGOPT
.byt 5
.byt 1
.byt SC_JUMP
.word (l_common-res_start)
+l_book
.byt SC_ACTOR_TALK
.byt 64, 250
.byt 64, 221
.byt 11
.byt SC_WAIT_FOR_ACTOR
.byt 64, 250
.byt SC_ACTOR_TALK
.byt 64, 250
.byt 64, 221
.byt 12
.byt SC_WAIT_FOR_ACTOR
.byt 64, 250
.byt SC_ACTOR_TALK
.byt 64, 250
.byt 64, 221
.byt 13
.byt SC_WAIT_FOR_ACTOR
.byt 64, 250
.byt SC_ACTIVATE_DLGOPT
.byt 6
.byt 1
.byt SC_ACTIVATE_DLGOPT
.byt 2
.byt 0
.byt SC_ACTIVATE_DLGOPT
.byt 3
.byt 0
.byt SC_ACTIVATE_DLGOPT
.byt 7
.byt 1
.byt SC_JUMP
.word (l_act_skeptic-res_start)
+l_skeptic
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_GT
.byt SF_GETRAND
.byt 64, 128
.byt 27
; then part
.byt SC_ACTOR_TALK
.byt 64, 250
.byt 64, 221
.byt 9
.byt SC_WAIT_FOR_ACTOR
.byt 64, 250
.byt SC_ACTOR_TALK
.byt 64, 250
.byt 64, 221
.byt 10
.byt SC_WAIT_FOR_ACTOR
.byt 64, 250
.byt SC_JUMP_REL, 29
; else part
.byt SC_ACTOR_TALK
.byt 64, 250
.byt 64, 221
.byt 17
.byt SC_WAIT_FOR_ACTOR
.byt 64, 250
.byt SC_ACTOR_TALK
.byt 64, 250
.byt 64, 221
.byt 18
.byt SC_WAIT_FOR_ACTOR
.byt 64, 250
.byt SC_ACTOR_TALK
.byt 64, 250
.byt 64, 221
.byt 19
.byt SC_WAIT_FOR_ACTOR
.byt 64, 250
.byt SC_ACTIVATE_DLGOPT
.byt 4
.byt 0
.byt SC_ACTIVATE_DLGOPT
.byt 5
.byt 0
.byt SC_JUMP
.word (l_common-res_start)
+l_air
.byt SC_ACTOR_TALK
.byt 64, 250
.byt 64, 221
.byt 14
.byt SC_WAIT_FOR_ACTOR
.byt 64, 250
.byt SC_ACTIVATE_DLGOPT
.byt 6
.byt 0
l_common
.byt SC_START_DIALOG
.byt SC_STOP_SCRIPT
+l_bye
.byt SC_ACTOR_TALK
.byt 64, 250
.byt 64, 221
.byt 15
.byt SC_WAIT_FOR_ACTOR
.byt 64, 250
.byt SC_ACTOR_TALK
.byt 64, 250
.byt 64, 221
.byt 20
.byt SC_WAIT_FOR_ACTOR
.byt 64, 250
.byt SC_ACTOR_TALK
.byt 64, 250
.byt 64, 221
.byt 21
.byt SC_WAIT_FOR_ACTOR
.byt 64, 250
.byt SC_ACTOR_TALK
.byt 64, 250
.byt 64, 221
.byt 22
.byt SC_WAIT_FOR_ACTOR
.byt 64, 250
.byt SC_PUT_IN_INVENTORY
.byt 8
.byt SC_SETFLAG, 2	; bMetRavella=true
.byt 1
.byt SC_SAVEGAME
+l_exit1
.byt SC_WAIT_FOR_ACTOR
.byt SF_GET_EGO
.byt SC_LOOK_DIRECTION
.byt 64, 250
.byt 0
.byt SC_END_DIALOG
.byt SC_STOP_SCRIPT
res_end
.)

; String pack 221
.(
.byt RESOURCE_STRING|$80
.word (res_end-res_start +4)
.byt 221
res_start
.asc "Hola Ravella.",0 ; String 0
.asc "",126,"Tuviste problemas?",0 ; String 1
.asc "No. Nada extra",35,"o.",0 ; String 2
.asc "",125,"Muerto de hambre, claro!",0 ; String 3
.asc "",126,"Y c",94,"mo te encuentras?",0 ; String 4
.asc "Bien hecho.",0 ; String 5
.asc "La comida est",91," llena de supresores.",0 ; String 6
.asc "Yo no.",0 ; String 7
.asc "El hombre al que conocer",91,"s hoy.",0 ; String 8
.asc "Tenemos que tener cuidado.",0 ; String 9
.asc "La Federaci",94,"n tiene mil ojos.",0 ; String 10
.asc "Bien. Esconde informaci",94,"n vital.",0 ; String 11
.asc "Nos dicen la puerta que hay que usar",0 ; String 12
.asc "para salir de la ciudad de ese modo.",0 ; String 13
.asc "Eso es lo que quieren que creas.",0 ; String 14
.asc "Una ",95,"ltima cosa.",0 ; String 15
.asc "Esa es Ravella.",0 ; String 16
.asc "",126,"No te preocupa pasar tu vida en un",0 ; String 17
.asc "estado de tranquilidad inducido a",0 ; String 18
.asc "trav",92,"s de drogas?",0 ; String 19
.asc "Ten esto. Puerta 2, taquilla 3B.",0 ; String 20
.asc "Hay algo para t",93," dentro.",0 ; String 21
.asc "Yo te espero aqu",93,".",0 ; String 22
.asc "Ya he hablado con ella.",0 ; String 23
.asc "Ahora tengo que hacer.",0 ; String 24
res_end
.)

; Object Code 250
.(
.byt RESOURCE_OBJECTCODE|$80
.word (res_end-res_start +4)
.byt 250
res_start
; Response table
.byt VERB_LOOKAT
.word (l_LookAt-res_start)
.byt VERB_TALKTO
.word (l_TalkTo-res_start)
.byt $ff ; End of response table
l_LookAt
.byt SC_ASSIGN, 64, 200	; actor=sfGetActorExecutingAction()
.byt SF_GET_ACTIONACTOR
.byt SC_ACTOR_TALK
.byt SF_GETVAL,64, 200	; actor
.byt 64, 221
.byt 16
.byt SC_WAIT_FOR_ACTOR
.byt SF_GETVAL,64, 200	; actor
.byt SC_STOP_SCRIPT
l_TalkTo
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_GETFLAG,2	; bMetRavella
.byt 36
; then part
.byt SC_CURSOR_ON
.byt 0
.byt SC_ASSIGN, 64, 200	; actor=sfGetActorExecutingAction()
.byt SF_GET_ACTIONACTOR
.byt SC_ACTOR_TALK
.byt SF_GETVAL,64, 200	; actor
.byt 64, 221
.byt 23
.byt SC_WAIT_FOR_ACTOR
.byt SF_GETVAL,64, 200	; actor
.byt SC_ACTOR_TALK
.byt SF_GETVAL,64, 200	; actor
.byt 64, 221
.byt 24
.byt SC_WAIT_FOR_ACTOR
.byt SF_GETVAL,64, 200	; actor
.byt SC_CURSOR_ON
.byt 1
.byt SC_STOP_SCRIPT
.byt SC_CURSOR_ON
.byt 0
.byt SC_ASSIGN, 64, 200	; actor=sfGetActorExecutingAction()
.byt SF_GET_ACTIONACTOR
.byt SC_ACTOR_TALK
.byt SF_GETVAL,64, 200	; actor
.byt 64, 221
.byt 0
.byt SC_WAIT_FOR_ACTOR
.byt SF_GETVAL,64, 200	; actor
.byt SC_LOOK_DIRECTION
.byt 64, 250
.byt 1
.byt SC_ACTOR_TALK
.byt 64, 250
.byt 64, 221
.byt 1
.byt SC_WAIT_FOR_ACTOR
.byt 64, 250
.byt SC_ACTOR_TALK
.byt SF_GETVAL,64, 200	; actor
.byt 64, 221
.byt 2
.byt SC_WAIT_FOR_ACTOR
.byt SF_GETVAL,64, 200	; actor
.byt SC_CURSOR_ON
.byt 1
.byt SC_LOAD_DIALOG
.byt 64, 200
.byt SC_START_DIALOG
.byt SC_STOP_SCRIPT
res_end
.)

; Object Code 201
.(
.byt RESOURCE_OBJECTCODE|$80
.word (res_end-res_start +4)
.byt 201
res_start
; Response table
.byt VERB_LOOKAT
.word (l_LookAt-res_start)
.byt $ff ; End of response table
l_LookAt
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 0
.byt SC_STOP_SCRIPT
.byt SC_STOP_SCRIPT
res_end
.)

; Object Code 202
.(
.byt RESOURCE_OBJECTCODE|$80
.word (res_end-res_start +4)
.byt 202
res_start
; Response table
.byt VERB_LOOKAT
.word (l_LookAt-res_start)
.byt $ff ; End of response table
l_LookAt
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 1
.byt SC_WAIT_FOR_ACTOR
.byt 0
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_NOT
.byt SF_GETFLAG,21	; bCamCodeSeen
.byt 10
; then part
.byt SC_SAVEGAME
.byt SC_SETFLAG, 21	; bCamCodeSeen=true
.byt 1
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_GETFLAG,20	; bCamDeactivated
.byt 12
; then part
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 9
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_STOP_SCRIPT
.byt SC_STOP_SCRIPT
res_end
.)

; String pack 200
.(
.byt RESOURCE_STRING|$80
.word (res_end-res_start +4)
.byt 200
res_start
.asc "Omnipresentes.",0 ; String 0
.asc "El c",94,"digo de la c",91,"mara es CH-1337.",0 ; String 1
.asc "Una puerta al ",91,"rea de servicio.",0 ; String 2
.asc "Parece confortable...",0 ; String 3
.asc "No es momento para descansar.",0 ; String 4
.asc "Me duele la espalda. Mejor lo dejo.",0 ; String 5
.asc "Es muy pesado, pero lo intentar",92,"...",0 ; String 6
.asc "Nada. Demasiado pesado para moverlo.",0 ; String 7
.asc "",125,"Eh! ",125,"Mira lo que hay aqu",93," debajo!",0 ; String 8
.asc "Esta c",91,"mara parece apagada.",0 ; String 9
.asc "No es buena idea.",0 ; String 10
.asc "La c",91,"mara me captar",91," y el sistema de",0 ; String 11
.asc "detecci",94,"n autom",91,"tico de intrusos",0 ; String 12
.asc "lanzar",91," una alarma.",0 ; String 13
.asc "",126,"Por? S",94,"lo es un corredor de servicio.",0 ; String 14
.asc "Y pesado tambi",92,"n.",0 ; String 15
.asc "Fijo que nadie limpia debajo.",0 ; String 16
res_end
.)

; Object Code 203
.(
.byt RESOURCE_OBJECTCODE|$80
.word (res_end-res_start +4)
.byt 203
res_start
; Response table
.byt VERB_LOOKAT
.word (l_LookAt-res_start)
.byt VERB_USE
.word (l_Use-res_start)
.byt VERB_OPEN
.word (l_Open-res_start)
.byt VERB_WALKTO
.word (l_WalkTo-res_start)
.byt $ff ; End of response table
l_LookAt
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 2
.byt SC_STOP_SCRIPT
l_Use
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_NOT, SF_EQ
.byt SF_GET_ACTIONOBJ2
.byt 64, 255
.byt 11
; then part
.byt SC_SPAWN_SCRIPT
.byt 1
.byt SC_STOP_SCRIPT
l_Open
l_WalkTo
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_NOT
.byt SF_GETFLAG,8	; bGotMap
.byt 14
; then part
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 14
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_STOP_SCRIPT
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_GETFLAG,20	; bCamDeactivated
.byt 15
; then part
.byt SC_SET_OBJECT_POS
.byt 0
.byt 7
.byt 14
.byt 64, 67
.byt SC_CHANGE_ROOM_AND_STOP
.byt 7
.byt SC_JUMP_REL, 34
; else part
.byt SC_CURSOR_ON
.byt 0
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 10
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 11
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 12
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 13
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_CURSOR_ON
.byt 1
.byt SC_STOP_SCRIPT
res_end
.)

; Object Code 200
.(
.byt RESOURCE_OBJECTCODE|$80
.word (res_end-res_start +4)
.byt 200
res_start
; Response table
.byt VERB_WALKTO
.word (l_WalkTo-res_start)
.byt $ff ; End of response table
l_WalkTo
.byt SC_SET_OBJECT_POS
.byt 0
.byt 3
.byt 13
.byt 64, 124
.byt SC_CHANGE_ROOM_AND_STOP
.byt 3
.byt SC_STOP_SCRIPT
res_end
.)

; Object Code 204
.(
.byt RESOURCE_OBJECTCODE|$80
.word (res_end-res_start +4)
.byt 204
res_start
; Response table
.byt VERB_LOOKAT
.word (l_LookAt-res_start)
.byt VERB_USE
.word (l_Use-res_start)
.byt VERB_PUSH
.word (l_Push-res_start)
.byt $ff ; End of response table
l_LookAt
.byt SC_CURSOR_ON
.byt 0
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 3
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 15
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 16
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_CURSOR_ON
.byt 1
.byt SC_STOP_SCRIPT
l_Use
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_NOT, SF_EQ
.byt SF_GET_ACTIONOBJ2
.byt 64, 255
.byt 11
; then part
.byt SC_SPAWN_SCRIPT
.byt 1
.byt SC_STOP_SCRIPT
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 4
.byt SC_STOP_SCRIPT
l_Push
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_GETFLAG,11	; bCouchPushed
.byt 13
; then part
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 5
.byt SC_JUMP_REL, 64, 65
; else part
.byt SC_CURSOR_ON
.byt 0
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 6
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_ASSIGN, 64, 200	; tmpanimstate=sfGetAnimstate(0)
.byt SF_GET_ANIMSTATE
.byt 0
.byt SC_SET_ANIMSTATE
.byt 0
.byt 3
.byt SC_DELAY
.byt 10
.byt SC_SET_ANIMSTATE
.byt 0
.byt SF_GETVAL,64, 200	; tmpanimstate
.byt SC_DELAY
.byt 20
.byt SC_SET_ANIMSTATE
.byt 0
.byt 3
.byt SC_DELAY
.byt 10
.byt SC_SET_ANIMSTATE
.byt 0
.byt SF_GETVAL,64, 200	; tmpanimstate
.byt SC_DELAY
.byt 5
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 7
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_DELAY
.byt 5
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 8
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_PUT_IN_INVENTORY
.byt 6
.byt SC_SETFLAG, 11	; bCouchPushed=true
.byt 1
.byt SC_SAVEGAME
.byt SC_CURSOR_ON
.byt 1
.byt SC_STOP_SCRIPT
res_end
.)

; Script 200
.(
.byt RESOURCE_SCRIPT|$80
.word (res_end-res_start +4)
.byt 200
res_start
+script_200_start
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_NOT
.byt SF_GETFLAG,2	; bMetRavella
.byt 9
; then part
.byt SC_LOAD_OBJECT
.byt 64, 250
.byt SC_ASSIGN, 0	; tmpParam1=201
.byt 64, 201
.byt SC_CLEAR_EVENTS
.byt 1
.byt SC_SPAWN_SCRIPT
.byt 64, 201
.byt SC_WAIT_EVENT
.byt 1
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_NOT
.byt SF_GETFLAG,20	; bCamDeactivated
.byt 13
; then part
.byt SC_ASSIGN, 0	; tmpParam1=202
.byt 64, 202
.byt SC_SPAWN_SCRIPT
.byt 64, 201
.byt SC_STOP_SCRIPT
.byt SC_STOP_SCRIPT
res_end
.)

; Script 201
.(
.byt RESOURCE_SCRIPT|$80
.word (res_end-res_start +4)
.byt 201
res_start
+script_201_start
.byt SC_ASSIGN, 64, 200	; CameraID=tmpParam1
.byt SF_GETVAL,0	; tmpParam1
.byt SC_SET_EVENTS
.byt 1
.byt SC_ASSIGN, 64, 202	; cc=sfGetCol(CameraID)
.byt SF_GET_COL
.byt SF_GETVAL,64, 200	; CameraID
l_loop
.byt SC_DELAY
.byt SF_GETRANDINT
.byt 64, 80
.byt 64, 110
.byt SC_ASSIGN, 64, 201	; bc=sfGetCol(0)
.byt SF_GET_COL
.byt 0
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_OR
.byt SF_AND
.byt SF_GT
.byt SF_GETVAL,64, 201	; bc
.byt SF_GETVAL,64, 202	; cc
.byt SF_LT
.byt SF_SUB
.byt SF_GETVAL,64, 201	; bc
.byt SF_GETVAL,64, 202	; cc
.byt 18
.byt SF_AND
.byt SF_LT
.byt SF_GETVAL,64, 201	; bc
.byt SF_GETVAL,64, 202	; cc
.byt SF_LT
.byt SF_SUB
.byt SF_GETVAL,64, 202	; cc
.byt SF_GETVAL,64, 201	; bc
.byt 18
.byt 40
; then part
.byt SC_PLAYSFX
.byt 17
.byt SC_SET_ANIMSTATE
.byt SF_GETVAL,64, 200	; CameraID
.byt 1
.byt SC_DELAY
.byt 5
.byt SC_SET_ANIMSTATE
.byt SF_GETVAL,64, 200	; CameraID
.byt 2
.byt SC_DELAY
.byt 5
.byt SC_SET_ANIMSTATE
.byt SF_GETVAL,64, 200	; CameraID
.byt 3
.byt SC_DELAY
.byt SF_GETRANDINT
.byt 64, 80
.byt 64, 110
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_OR
.byt SF_AND
.byt SF_GT
.byt SF_GETVAL,64, 201	; bc
.byt SF_GETVAL,64, 202	; cc
.byt SF_LT
.byt SF_SUB
.byt SF_GETVAL,64, 201	; bc
.byt SF_GETVAL,64, 202	; cc
.byt 38
.byt SF_AND
.byt SF_LT
.byt SF_GETVAL,64, 201	; bc
.byt SF_GETVAL,64, 202	; cc
.byt SF_LT
.byt SF_SUB
.byt SF_GETVAL,64, 202	; cc
.byt SF_GETVAL,64, 201	; bc
.byt 38
.byt 40
; then part
.byt SC_PLAYSFX
.byt 17
.byt SC_SET_ANIMSTATE
.byt SF_GETVAL,64, 200	; CameraID
.byt 2
.byt SC_DELAY
.byt 5
.byt SC_SET_ANIMSTATE
.byt SF_GETVAL,64, 200	; CameraID
.byt 1
.byt SC_DELAY
.byt 5
.byt SC_SET_ANIMSTATE
.byt SF_GETVAL,64, 200	; CameraID
.byt 0
.byt SC_JUMP
.word (l_loop-res_start)
.byt SC_STOP_SCRIPT
res_end
.)
