;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Generated by OASIS compiler
; (c) Chema 2016
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


; Object Code 6
.(
.byt RESOURCE_OBJECTCODE
.word (res_end-res_start +4)
.byt 6
res_start
; Response table
.byt VERB_LOOKAT
.word (l_LookAt-res_start)
.byt VERB_USE
.word (l_Use-res_start)
.byt $ff ; End of response table
l_LookAt
.byt SC_CURSOR_ON
.byt 0
.byt SC_ACTOR_TALK
.byt 0
.byt 6
.byt 0
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_ACTOR_TALK
.byt 0
.byt 6
.byt 1
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_CURSOR_ON
.byt 1
.byt SC_STOP_SCRIPT
l_Use
.byt SC_ACTOR_TALK
.byt 0
.byt 6
.byt 2
.byt SC_STOP_SCRIPT
res_end
.)

; String pack 6
.(
.byt RESOURCE_STRING
.word (res_end-res_start +4)
.byt 6
res_start
.asc "Un c",92,"ntimo de cr",92,"dito.",0 ; String 0
.asc "Una moneda fina, peque",35,"a e in",95,"til.",0 ; String 1
.asc "No es ",95,"til para esto.",0 ; String 2
res_end
.)
