;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Generated by OASIS compiler
; (c) Chema 2016
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


; String pack 48
.(
.byt RESOURCE_STRING
.word (res_end-res_start +4)
.byt 48
res_start
.asc "Seems resistant, despite its weight.",0 ; String 0
.asc "I can't use the log with that.",0 ; String 1
.asc "I'd better keep it there.",0 ; String 2
res_end
.)

; Object Code 48
.(
.byt RESOURCE_OBJECTCODE
.word (res_end-res_start +4)
.byt 48
res_start
; Response table
.byt VERB_LOOKAT
.word (l_LookAt-res_start)
.byt VERB_USE
.word (l_Use-res_start)
.byt VERB_PICKUP
.word (l_PickUp-res_start)
.byt $ff ; End of response table
l_LookAt
.byt SC_ACTOR_TALK
.byt SF_GET_ACTIONACTOR
.byt 48
.byt 0
.byt SC_STOP_SCRIPT
l_Use
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_IS_OBJINVENTORY
.byt 48
.byt 10
; then part
.byt SC_ACTOR_TALK
.byt 0
.byt 48
.byt 1
.byt SC_STOP_SCRIPT
l_PickUp
.byt SC_ACTOR_TALK
.byt SF_GET_ACTIONACTOR
.byt 48
.byt 2
.byt SC_STOP_SCRIPT
res_end
.)
