;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Generated by OASIS compiler
; (c) Chema 2016
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


; Object Code 10
.(
.byt RESOURCE_OBJECTCODE
.word (res_end-res_start +4)
.byt 10
res_start
; Response table
.byt VERB_USE
.word (l_Use-res_start)
.byt VERB_GIVE
.word (l_Give-res_start)
.byt VERB_TALKTO
.word (l_TalkTo-res_start)
.byt VERB_LOOKAT
.word (l_LookAt-res_start)
.byt $ff ; End of response table
l_Use
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GET_ACTIONOBJ2
.byt 10
.byt 11
; then part
.byt SC_JUMP
.word (l_Give-res_start)
.byt SC_JUMP_REL, 12
; else part
.byt SC_CURSOR_ON
.byt 0
.byt SC_ACTOR_TALK
.byt 0
.byt 10
.byt 3
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_CURSOR_ON
.byt 1
.byt SC_STOP_SCRIPT
l_Give
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GET_ACTIONOBJ1
.byt 3
.byt 26
; then part
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GET_STATE
.byt 3
.byt 1
.byt 12
; then part
.byt SC_JUMP
.word (l_TalkTo-res_start)
.byt SC_JUMP_REL, 8
; else part
.byt SC_ACTOR_TALK
.byt 0
.byt 10
.byt 5
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_JUMP_REL, 18
; else part
.byt SC_CURSOR_ON
.byt 0
.byt SC_LOOK_DIRECTION
.byt 10
.byt 1
.byt SC_ACTOR_TALK
.byt 10
.byt 10
.byt 4
.byt SC_WAIT_FOR_ACTOR
.byt 10
.byt SC_LOOK_DIRECTION
.byt 10
.byt 0
.byt SC_CURSOR_ON
.byt 1
.byt SC_STOP_SCRIPT
l_TalkTo
.byt SC_CURSOR_ON
.byt 0
.byt SC_LOOK_DIRECTION
.byt 10
.byt 1
.byt SC_ACTOR_TALK
.byt 10
.byt 10
.byt 6
.byt SC_WAIT_FOR_ACTOR
.byt 10
.byt SC_ACTOR_TALK
.byt 10
.byt 10
.byt 7
.byt SC_WAIT_FOR_ACTOR
.byt 10
.byt SC_CURSOR_ON
.byt 1
.byt SC_LOAD_DIALOG
.byt 64, 200
.byt SC_START_DIALOG
.byt SC_STOP_SCRIPT
l_LookAt
.byt SC_CURSOR_ON
.byt 0
.byt SC_ACTOR_TALK
.byt 0
.byt 10
.byt 0
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_ACTOR_TALK
.byt 0
.byt 10
.byt 1
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_ACTOR_TALK
.byt 0
.byt 10
.byt 2
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_CURSOR_ON
.byt 1
.byt SC_STOP_SCRIPT
.byt SC_STOP_SCRIPT
res_end
.)

; String pack 10
.(
.byt RESOURCE_STRING
.word (res_end-res_start +4)
.byt 10
res_start
.asc "Seems to be in charge of the control",0 ; String 0
.asc "of the systems in this area.",0 ; String 1
.asc "He could get me arrested.",0 ; String 2
.asc "I don't see what you want to do.",0 ; String 3
.asc "What? What would I do with that?",0 ; String 4
.asc "How can that be of any help?",0 ; String 5
.asc "Ah! are you from the kitchen service?",0 ; String 6
.asc "I've been waiting for ages!",0 ; String 7
res_end
.)
