;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Generated by OASIS compiler
; (c) Chema 2016
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


; String pack 21
.(
.byt RESOURCE_STRING
.word (res_end-res_start +4)
.byt 21
res_start
.asc "Un hombre curioso...",0 ; String 0
.asc "No hay cierre que no pueda abrir...",0 ; String 1
.asc "si estoy suficientemente asustado.",0 ; String 2
.asc "No me encuentro bien.",0 ; String 3
.asc "Voy a ser un gran handicap.",0 ; String 4
.asc "Tengo un s",93,"ndrome - miedo a los",0 ; String 5
.asc "espacios cerrados.",0 ; String 6
.asc "Tiene un nombre...",0 ; String 7
.asc "",126,"Cobard",93,"a?",0 ; String 8
res_end
.)

; Object Code 21
.(
.byt RESOURCE_OBJECTCODE
.word (res_end-res_start +4)
.byt 21
res_start
; Response table
.byt VERB_LOOKAT
.word (l_LookAt-res_start)
.byt VERB_TALKTO
.word (l_TalkTo-res_start)
.byt $ff ; End of response table
l_LookAt
.byt SC_ACTOR_TALK
.byt 0
.byt 21
.byt 0
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_STOP_SCRIPT
l_TalkTo
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GET_CURROOM
.byt 15
.byt 24
; then part
.byt SC_LOAD_DIALOG
.byt 64, 207
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_AND
.byt SF_GETFLAG,28	; bAskedAvonForLock
.byt SF_NOT
.byt SF_IS_OBJINVENTORY
.byt 64, 205
.byt 13
; then part
.byt SC_ACTIVATE_DLGOPT
.byt 1
.byt 1
.byt SC_START_DIALOG
.byt SC_STOP_SCRIPT
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_AND
.byt SF_AND
.byt SF_EQ
.byt SF_GET_CURROOM
.byt 49
.byt SF_EQ
.byt SF_GET_ROOM
.byt 20
.byt 49
.byt SF_GT
.byt SF_GETRAND
.byt 50
.byt 50
; then part
.byt SC_CURSOR_ON
.byt 0
.byt SC_ACTOR_TALK
.byt 21
.byt 21
.byt 4
.byt SC_WAIT_FOR_ACTOR
.byt 21
.byt SC_ACTOR_TALK
.byt 21
.byt 21
.byt 5
.byt SC_WAIT_FOR_ACTOR
.byt 21
.byt SC_ACTOR_TALK
.byt 21
.byt 21
.byt 6
.byt SC_WAIT_FOR_ACTOR
.byt 21
.byt SC_ACTOR_TALK
.byt 21
.byt 21
.byt 7
.byt SC_WAIT_FOR_ACTOR
.byt 21
.byt SC_ACTOR_TALK
.byt 20
.byt 21
.byt 8
.byt SC_WAIT_FOR_ACTOR
.byt 20
.byt SC_CURSOR_ON
.byt 1
.byt SC_STOP_SCRIPT
.byt SC_CURSOR_ON
.byt 0
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_GT
.byt SF_GETRAND
.byt 64, 127
.byt 19
; then part
.byt SC_ACTOR_TALK
.byt 21
.byt 21
.byt 1
.byt SC_WAIT_FOR_ACTOR
.byt 21
.byt SC_ACTOR_TALK
.byt 21
.byt 21
.byt 2
.byt SC_JUMP_REL, 12
; else part
.byt SC_ACTOR_TALK
.byt 21
.byt 21
.byt 3
.byt SC_WAIT_FOR_ACTOR
.byt 21
.byt SC_ACTOR_TALK
.byt 21
.byt 21
.byt 4
.byt SC_CURSOR_ON
.byt 1
.byt SC_STOP_SCRIPT
.byt SC_STOP_SCRIPT
res_end
.)
