;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Generated by OASIS compiler
; (c) Chema 2016
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


; String pack 43
.(
.byt RESOURCE_STRING
.word (res_end-res_start +4)
.byt 43
res_start
.asc "Looks like a strong rope.",0 ; String 0
.asc "I can't use the rope with that.",0 ; String 1
res_end
.)

; Object Code 43
.(
.byt RESOURCE_OBJECTCODE
.word (res_end-res_start +4)
.byt 43
res_start
; Response table
.byt VERB_LOOKAT
.word (l_LookAt-res_start)
.byt VERB_USE
.word (l_Use-res_start)
.byt $ff ; End of response table
l_LookAt
.byt SC_ACTOR_TALK
.byt 0
.byt 43
.byt 0
.byt SC_STOP_SCRIPT
l_Use
.byt SC_ACTOR_TALK
.byt 0
.byt 43
.byt 1
.byt SC_STOP_SCRIPT
res_end
.)
