;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Generated by OASIS compiler
; (c) Chema 2016
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


; Object Code 11
.(
.byt RESOURCE_OBJECTCODE
.word (res_end-res_start +4)
.byt 11
res_start
; Response table
.byt VERB_LOOKAT
.word (l_LookAt-res_start)
.byt VERB_TALKTO
.word (l_TalkTo-res_start)
.byt VERB_GIVE
.word (l_Give-res_start)
.byt $ff ; End of response table
l_LookAt
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 201
.byt 0
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_STOP_SCRIPT
l_TalkTo
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_GETFLAG,7	; bMapPrinted
.byt 13
; then part
.byt SC_ACTOR_TALK
.byt 11
.byt 64, 201
.byt 22
.byt SC_WAIT_FOR_ACTOR
.byt 11
.byt SC_STOP_SCRIPT
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_NOT, SF_EQ
.byt SF_GET_CURROOM
.byt 5
.byt 14
; then part
.byt SC_FREEZE_SCRIPT
.byt 64, 202
.byt 1
.byt SC_LOOK_DIRECTION
.byt 11
.byt 0
.byt SC_CURSOR_ON
.byt 0
.byt SC_ACTOR_TALK
.byt 11
.byt 64, 201
.byt 1
.byt SC_WAIT_FOR_ACTOR
.byt 11
.byt SC_CURSOR_ON
.byt 1
.byt SC_LOAD_DIALOG
.byt 64, 200
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_OR
.byt SF_GETFLAG,2	; bMetRavella
.byt SF_GETFLAG,0	; bReadMapPoster
.byt 11
; then part
.byt SC_ACTIVATE_DLGOPT
.byt 0
.byt 1
.byt SC_START_DIALOG
.byt SC_STOP_SCRIPT
l_Give
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_NOT, SF_EQ
.byt SF_GET_CURROOM
.byt 5
.byt 27
; then part
.byt SC_LOOK_DIRECTION
.byt 11
.byt 0
.byt SC_FREEZE_SCRIPT
.byt 64, 202
.byt 1
.byt SC_ACTOR_TALK
.byt 11
.byt 64, 201
.byt 18
.byt SC_WAIT_FOR_ACTOR
.byt 11
.byt SC_FREEZE_SCRIPT
.byt 64, 202
.byt 0
.byt SC_JUMP_REL, 5
; else part
.byt SC_CHAIN_SCRIPT
.byt 64, 250
.byt SC_STOP_SCRIPT
.byt SC_STOP_SCRIPT
res_end
.)
