;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Generated by OASIS compiler
; (c) Chema 2016
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


; Object Code 28
.(
.byt RESOURCE_OBJECTCODE
.word (res_end-res_start +4)
.byt 28
res_start
; Response table
.byt VERB_LOOKAT
.word (l_LookAt-res_start)
.byt VERB_PICKUP
.word (l_PickUp-res_start)
.byt $ff ; End of response table
l_LookAt
.byt SC_CURSOR_ON
.byt 0
.byt SC_ASSIGN, 64, 200	; actor=sfGetEgo()
.byt SF_GET_EGO
.byt SC_ACTOR_TALK
.byt SF_GETVAL,64, 200	; actor
.byt 28
.byt 0
.byt SC_WAIT_FOR_ACTOR
.byt SF_GETVAL,64, 200	; actor
.byt SC_ACTOR_TALK
.byt SF_GETVAL,64, 200	; actor
.byt 28
.byt 1
.byt SC_WAIT_FOR_ACTOR
.byt SF_GETVAL,64, 200	; actor
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GETVAL,64, 200	; actor
.byt 22
.byt 28
; then part
.byt SC_ACTOR_TALK
.byt SF_GETVAL,64, 200	; actor
.byt 28
.byt 3
.byt SC_WAIT_FOR_ACTOR
.byt SF_GETVAL,64, 200	; actor
.byt SC_ACTOR_TALK
.byt SF_GETVAL,64, 200	; actor
.byt 28
.byt 4
.byt SC_WAIT_FOR_ACTOR
.byt SF_GETVAL,64, 200	; actor
.byt SC_CURSOR_ON
.byt 1
.byt SC_STOP_SCRIPT
l_PickUp
.byt SC_ASSIGN, 64, 200	; actor=sfGetEgo()
.byt SF_GET_EGO
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GETVAL,64, 200	; actor
.byt 0
.byt 16
; then part
.byt SC_ACTOR_TALK
.byt 0
.byt 28
.byt 2
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_JUMP_REL, 9
; else part
.byt SC_PUT_IN_INVENTORY
.byt 28
.byt SC_SETFLAG, 64, 72	; bDroneTaken=true
.byt 1
.byt SC_SAVEGAME
.byt SC_STOP_SCRIPT
res_end
.)

; String pack 28
.(
.byt RESOURCE_STRING
.word (res_end-res_start +4)
.byt 28
res_start
.asc "It looks like a small drone, but it",0 ; String 0
.asc "seems to be broken beyond repair.",0 ; String 1
.asc "I wouldn't know what to do with it.",0 ; String 2
.asc "I wonder if I can make use of that",0 ; String 3
.asc "transmitter and that receiver...",0 ; String 4
res_end
.)
