;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Generated by OASIS compiler
; (c) Chema 2016
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


; String pack 42
.(
.byt RESOURCE_STRING
.word (res_end-res_start +4)
.byt 42
res_start
.asc "Algunas pulseras de m",91,"s, para poder",0 ; String 0
.asc "traer al resto de mi tripulaci",94,"n.",0 ; String 1
.asc "Estas pulseras son para los dem",91,"s.",0 ; String 2
res_end
.)

; Object Code 42
.(
.byt RESOURCE_OBJECTCODE
.word (res_end-res_start +4)
.byt 42
res_start
; Response table
.byt VERB_LOOKAT
.word (l_LookAt-res_start)
.byt VERB_USE
.word (l_Use-res_start)
.byt $ff ; End of response table
l_LookAt
.byt SC_CURSOR_ON
.byt 0
.byt SC_ACTOR_TALK
.byt 0
.byt 42
.byt 0
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_ACTOR_TALK
.byt 0
.byt 42
.byt 1
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_CURSOR_ON
.byt 1
.byt SC_STOP_SCRIPT
l_Use
.byt SC_ACTOR_TALK
.byt 0
.byt 42
.byt 2
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_STOP_SCRIPT
.byt SC_STOP_SCRIPT
res_end
.)
