;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Generated by OASIS compiler
; (c) Chema 2016
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


; Object Code 9
.(
.byt RESOURCE_OBJECTCODE
.word (res_end-res_start +4)
.byt 9
res_start
; Response table
.byt VERB_LOOKAT
.word (l_LookAt-res_start)
.byt VERB_USE
.word (l_Use-res_start)
.byt $ff ; End of response table
l_LookAt
.byt SC_CURSOR_ON
.byt 0
.byt SC_ACTOR_TALK
.byt 0
.byt 9
.byt 0
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_ACTOR_TALK
.byt 0
.byt 9
.byt 1
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_DELAY
.byt 5
.byt SC_ACTOR_TALK
.byt 0
.byt 9
.byt 2
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_ACTOR_TALK
.byt 0
.byt 9
.byt 3
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_DELAY
.byt 10
.byt SC_ACTOR_TALK
.byt 0
.byt 9
.byt 4
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_ACTOR_TALK
.byt 0
.byt 9
.byt 5
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_CURSOR_ON
.byt 1
.byt SC_STOP_SCRIPT
l_Use
.byt SC_CURSOR_ON
.byt 0
.byt SC_ACTOR_TALK
.byt 0
.byt 9
.byt 6
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_ACTOR_TALK
.byt 0
.byt 9
.byt 7
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_CURSOR_ON
.byt 1
.byt SC_STOP_SCRIPT
.byt SC_STOP_SCRIPT
res_end
.)

; String pack 9
.(
.byt RESOURCE_STRING
.word (res_end-res_start +4)
.byt 9
res_start
.asc "A technical map showing exit 172.",0 ; String 0
.asc "Interesting....",0 ; String 1
.asc "It is possible to reach it from the",0 ; String 2
.asc "ventilation system in this level.",0 ; String 3
.asc "And there is an access inside the",0 ; String 4
.asc "service corridor.",0 ; String 5
.asc "I can use the map once I get inside",0 ; String 6
.asc "the ventilation system.",0 ; String 7
res_end
.)
