;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Generated by OASIS compiler
; (c) Chema 2016
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


; String pack 23
.(
.byt RESOURCE_STRING
.word (res_end-res_start +4)
.byt 23
res_start
.asc "Parece fuerte como una roca.",0 ; String 0
.asc "Estoy listo.",0 ; String 1
.asc "S",94,"lo dime qu",92," quieres que haga.",0 ; String 2
res_end
.)

; Object Code 23
.(
.byt RESOURCE_OBJECTCODE
.word (res_end-res_start +4)
.byt 23
res_start
; Response table
.byt VERB_LOOKAT
.word (l_LookAt-res_start)
.byt VERB_TALKTO
.word (l_TalkTo-res_start)
.byt $ff ; End of response table
l_LookAt
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_NOT
.byt SF_GETFLAG,26	; bGanIntroduced
.byt 10
; then part
.byt SC_SPAWN_SCRIPT
.byt 64, 201
.byt SC_STOP_SCRIPT
.byt SC_ACTOR_TALK
.byt 0
.byt 23
.byt 0
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_STOP_SCRIPT
l_TalkTo
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_NOT
.byt SF_GETFLAG,26	; bGanIntroduced
.byt 10
; then part
.byt SC_SPAWN_SCRIPT
.byt 64, 201
.byt SC_STOP_SCRIPT
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GET_CURROOM
.byt 15
.byt 11
; then part
.byt SC_LOAD_DIALOG
.byt 64, 208
.byt SC_START_DIALOG
.byt SC_STOP_SCRIPT
.byt SC_ACTOR_TALK
.byt 23
.byt 23
.byt SF_GETRANDINT
.byt 1
.byt 2
.byt SC_STOP_SCRIPT
res_end
.)
