;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Generated by OASIS compiler
; (c) Chema 2016
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


; String pack 35
.(
.byt RESOURCE_STRING
.word (res_end-res_start +4)
.byt 35
res_start
.asc "I can use it for teleporting and",0 ; String 0
.asc "communication with the Liberator.",0 ; String 1
.asc "Okay, put me down.",0 ; String 2
.asc "Bring me up.",0 ; String 3
.asc "I have to be in the teleport cabin.",0 ; String 4
.asc "I can't do that with the bracelet.",0 ; String 5
.asc "And who will operate the teleport?",0 ; String 6
.asc "I'd better not go unarmed.",0 ; String 7
.asc "Zen, turn the air conditioning off.",0 ; String 8
.asc "I don't need to get back now.",0 ; String 9
.asc "I can't without the transponder.",0 ; String 10
res_end
.)

; Object Code 35
.(
.byt RESOURCE_OBJECTCODE
.word (res_end-res_start +4)
.byt 35
res_start
; Response table
.byt VERB_LOOKAT
.word (l_LookAt-res_start)
.byt VERB_USE
.word (l_Use-res_start)
.byt $ff ; End of response table
l_LookAt
.byt SC_ASSIGN, 64, 201	; actor=sfGetActorExecutingAction()
.byt SF_GET_ACTIONACTOR
.byt SC_CURSOR_ON
.byt 0
.byt SC_ACTOR_TALK
.byt SF_GETVAL,64, 201	; actor
.byt 35
.byt 0
.byt SC_WAIT_FOR_ACTOR
.byt SF_GETVAL,64, 201	; actor
.byt SC_ACTOR_TALK
.byt SF_GETVAL,64, 201	; actor
.byt 35
.byt 1
.byt SC_WAIT_FOR_ACTOR
.byt SF_GETVAL,64, 201	; actor
.byt SC_CURSOR_ON
.byt 1
.byt SC_STOP_SCRIPT
l_Use
.byt SC_ASSIGN, 64, 201	; actor=sfGetActorExecutingAction()
.byt SF_GET_ACTIONACTOR
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_NOT, SF_EQ
.byt SF_GET_ACTIONOBJ1
.byt 35
.byt 19
; then part
.byt SC_LOOK_DIRECTION
.byt SF_GETVAL,64, 201	; actor
.byt 3
.byt SC_ACTOR_TALK
.byt SF_GETVAL,64, 201	; actor
.byt 35
.byt 5
.byt SC_STOP_SCRIPT
.byt SC_ASSIGN, 64, 200	; room=sfGetCurrentRoom()
.byt SF_GET_CURROOM
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GETVAL,64, 200	; room
.byt 37
.byt 11
; then part
.byt SC_SPAWN_SCRIPT
.byt 11
.byt SC_STOP_SCRIPT
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_OR
.byt SF_OR
.byt SF_OR
.byt SF_OR
.byt SF_EQ
.byt SF_GETVAL,64, 200	; room
.byt 22
.byt SF_EQ
.byt SF_GETVAL,64, 200	; room
.byt 20
.byt SF_EQ
.byt SF_GETVAL,64, 200	; room
.byt 21
.byt SF_EQ
.byt SF_GETVAL,64, 200	; room
.byt 23
.byt SF_EQ
.byt SF_GETVAL,64, 200	; room
.byt 25
.byt 43
; then part
.byt SC_ACTOR_TALK
.byt SF_GETVAL,64, 201	; actor
.byt 35
.byt 4
.byt SC_WAIT_FOR_ACTOR
.byt SF_GETVAL,64, 201	; actor
.byt SC_STOP_SCRIPT
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_NOT, SF_EQ
.byt SF_GETVAL,64, 200	; room
.byt 24
.byt 64, 127
; then part
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GETVAL,64, 201	; actor
.byt 22
.byt 19
; then part
.byt SC_ACTOR_TALK
.byt SF_GETVAL,64, 201	; actor
.byt 35
.byt 9
.byt SC_WAIT_FOR_ACTOR
.byt SF_GETVAL,64, 201	; actor
.byt SC_STOP_SCRIPT
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_AND
.byt SF_AND
.byt SF_AND
.byt SF_EQ
.byt SF_GETVAL,64, 201	; actor
.byt 0
.byt SF_GETFLAG,49	; bCenteroOrbit
.byt SF_GETFLAG,64, 68	; bClockTampered
.byt SF_NOT, SF_EQ
.byt SF_GETVAL,64, 200	; room
.byt 49
.byt 33
; then part
.byt SC_ACTOR_TALK
.byt SF_GETVAL,64, 201	; actor
.byt 35
.byt 10
.byt SC_WAIT_FOR_ACTOR
.byt SF_GETVAL,64, 201	; actor
.byt SC_STOP_SCRIPT
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_AND
.byt SF_GETFLAG,49	; bCenteroOrbit
.byt SF_GETFLAG,56	; bDoorPuzzleDone
.byt 19
; then part
.byt SC_ACTOR_TALK
.byt SF_GETVAL,64, 201	; actor
.byt 35
.byt 9
.byt SC_WAIT_FOR_ACTOR
.byt SF_GETVAL,64, 201	; actor
.byt SC_STOP_SCRIPT
.byt SC_CURSOR_ON
.byt 0
.byt SC_ACTOR_TALK
.byt SF_GETVAL,64, 201	; actor
.byt 35
.byt 3
.byt SC_WAIT_FOR_ACTOR
.byt SF_GETVAL,64, 201	; actor
.byt SC_CLEAR_EVENTS
.byt 1
.byt SC_PLAYSFX
.byt 9
.byt SC_ASSIGN, 0	; tmpParam1=actor
.byt SF_GETVAL,64, 201	; actor
.byt SC_CHAIN_SCRIPT
.byt 6
.byt SC_LOAD_ROOM
.byt 24
.byt SC_BREAK_HERE
.byt SC_CLEAR_EVENTS
.byt 1
.byt SC_PLAYSFX
.byt 9
.byt SC_ASSIGN, 0	; tmpParam1=actor
.byt SF_GETVAL,64, 201	; actor
.byt SC_ASSIGN, 1	; tmpParam2=13
.byt 13
.byt SC_ASSIGN, 2	; tmpParam3=1
.byt 1
.byt SC_CHAIN_SCRIPT
.byt 7
.byt SC_CURSOR_ON
.byt 1
.byt SC_STOP_SCRIPT
.byt SC_ASSIGN, 64, 200	; room=sfGetWalkbox(actor)
.byt SF_GET_WALKBOX
.byt SF_GETVAL,64, 201	; actor
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_OR
.byt SF_LT
.byt SF_GETVAL,64, 200	; room
.byt 3
.byt SF_GT
.byt SF_GETVAL,64, 200	; room
.byt 6
.byt 25
; then part
.byt SC_ACTOR_TALK
.byt SF_GETVAL,64, 201	; actor
.byt 35
.byt 4
.byt SC_WAIT_FOR_ACTOR
.byt SF_GETVAL,64, 201	; actor
.byt SC_STOP_SCRIPT
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GETVAL,64, 201	; actor
.byt 22
.byt 40
; then part
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_OR
.byt SF_NOT
.byt SF_GETFLAG,64, 73	; bSwitchInstalled
.byt SF_NOT
.byt SF_GETFLAG,64, 74	; bTransmitterInstalled
.byt 19
; then part
.byt SC_ACTOR_TALK
.byt SF_GETVAL,64, 201	; actor
.byt 35
.byt 6
.byt SC_STOP_SCRIPT
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_NOT
.byt SF_IS_OBJINVENTORY
.byt 36
.byt 13
; then part
.byt SC_ACTOR_TALK
.byt SF_GETVAL,64, 201	; actor
.byt 35
.byt 7
.byt SC_STOP_SCRIPT
.byt SC_CURSOR_ON
.byt 0
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_NOT, SF_EQ
.byt SF_GETVAL,64, 201	; actor
.byt 22
.byt 17
; then part
.byt SC_ACTOR_TALK
.byt SF_GETVAL,64, 201	; actor
.byt 35
.byt 2
.byt SC_JUMP_REL, 8
; else part
.byt SC_ACTOR_TALK
.byt SF_GETVAL,64, 201	; actor
.byt 35
.byt 8
.byt SC_WAIT_FOR_ACTOR
.byt SF_GETVAL,64, 201	; actor
.byt SC_CLEAR_EVENTS
.byt 1
.byt SC_PLAYSFX
.byt 9
.byt SC_ASSIGN, 0	; tmpParam1=actor
.byt SF_GETVAL,64, 201	; actor
.byt SC_CHAIN_SCRIPT
.byt 6
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_GETFLAG,39	; bCygnusOrbit
.byt 15
; then part
.byt SC_ASSIGN, 64, 200	; room=31
.byt 31
.byt SC_ASSIGN, 1	; tmpParam2=15
.byt 15
.byt SC_ASSIGN, 2	; tmpParam3=9
.byt 9
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_GETFLAG,49	; bCenteroOrbit
.byt 36
; then part
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_NOT, SF_EQ
.byt SF_GETVAL,64, 201	; actor
.byt 22
.byt 21
; then part
.byt SC_ASSIGN, 64, 200	; room=41
.byt 41
.byt SC_ASSIGN, 1	; tmpParam2=9
.byt 9
.byt SC_ASSIGN, 2	; tmpParam3=17
.byt 17
.byt SC_JUMP_REL, 12
; else part
.byt SC_ASSIGN, 64, 200	; room=49
.byt 49
.byt SC_ASSIGN, 1	; tmpParam2=15
.byt 15
.byt SC_ASSIGN, 2	; tmpParam3=14
.byt 14
.byt SC_LOCK_RESOURCE
.byt 4
.byt 35
.byt SC_LOAD_ROOM
.byt SF_GETVAL,64, 200	; room
.byt SC_BREAK_HERE
.byt SC_CLEAR_EVENTS
.byt 1
.byt SC_PLAYSFX
.byt 9
.byt SC_ASSIGN, 0	; tmpParam1=actor
.byt SF_GETVAL,64, 201	; actor
.byt SC_CHAIN_SCRIPT
.byt 7
.byt SC_CURSOR_ON
.byt 1
.byt SC_UNLOCK_RESOURCE
.byt 4
.byt 35
.byt SC_STOP_SCRIPT
.byt SC_STOP_SCRIPT
res_end
.)
