;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Generated by OASIS compiler
; (c) Chema 2016
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


; Script 17
.(
.byt RESOURCE_SCRIPT
.word (res_end-res_start +4)
.byt 17
res_start
+script_17_start
.byt SC_SHOW_VERBS
.byt 0
.byt SC_PLAYSFX
.byt 3
.byt SC_DELAY
.byt 5
.byt SC_PLAYSFX
.byt 3
.byt SC_SET_OBJECT_POS
.byt 20
.byt 43
.byt 16
.byt 55
.byt SC_SET_OBJECT_POS
.byt 0
.byt 43
.byt 14
.byt 64, 64
.byt SC_LOAD_ROOM
.byt 43
.byt SC_BREAK_HERE
.byt SC_LOOK_DIRECTION
.byt 20
.byt 0
; for
; Init part
.byt SC_ASSIGN, 64, 200	; i=7
.byt 7
; Condition
.byt SC_JUMP_IF, SF_NOT
.byt SF_LE
.byt SF_GETVAL,64, 200	; i
.byt 10
.word 72
; for body
.byt SC_ACTOR_TALK
.byt 20
.byt 64, 200
.byt SF_GETVAL,64, 200	; i
.byt SC_WAIT_FOR_ACTOR
.byt 20
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 9
.byt 14
; then part
.byt SC_ACTOR_WALKTO
.byt 20
.byt 56
.byt 11
.byt SC_WAIT_FOR_ACTOR
.byt 20
; Increment expression
.byt SC_ASSIGN, 64, 200	; i=i+1
.byt SF_ADD
.byt SF_GETVAL,64, 200	; i
.byt 1
; end for
.byt SC_JUMP, 29, 0	; jump to 29
.byt SC_ACTOR_WALKTO
.byt 0
.byt 60
.byt 12
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_SET_OBJECT_POS
.byt 20
.byt 44
.byt 15
.byt 14
.byt SC_SET_OBJECT_POS
.byt 0
.byt 44
.byt 16
.byt 21
.byt SC_LOOK_DIRECTION
.byt 0
.byt 2
.byt SC_LOOK_DIRECTION
.byt 20
.byt 0
.byt SC_LOAD_ROOM
.byt 44
.byt SC_SHOW_VERBS
.byt 1
.byt SC_SAVEGAME
.byt SC_STOP_SCRIPT
res_end
.)
