;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Generated by OASIS compiler
; (c) Chema 2016
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


; Script 9
.(
.byt RESOURCE_SCRIPT
.word (res_end-res_start +4)
.byt 9
res_start
+script_9_start
.byt SC_SHOW_VERBS
.byt 0
.byt SC_SET_OBJECT_POS
.byt 20
.byt 24
.byt 14
.byt 18
.byt SC_LOOK_DIRECTION
.byt 20
.byt 0
.byt SC_LOCK_RESOURCE
.byt 4
.byt 64, 100
.byt SC_LOAD_ROOM
.byt 24
.byt SC_UNLOCK_RESOURCE
.byt 4
.byt 64, 100
.byt SC_PRINT
.byt 64, 100
.byt 24
.byt SC_DELAY
.byt 64, 100
.byt SC_PRINT
.byt 64, 100
.byt 25
; for
; Init part
.byt SC_ASSIGN, 64, 200	; i=0
.byt 0
; Condition
.byt SC_JUMP_IF, SF_NOT
.byt SF_LT
.byt SF_GETVAL,64, 200	; i
.byt 14
.word 75
; for body
.byt SC_ACTOR_TALK
.byt 20
.byt 64, 100
.byt SF_GETVAL,64, 200	; i
.byt SC_WAIT_FOR_ACTOR
.byt 20
.byt SC_ACTOR_TALK
.byt 22
.byt 64, 100
.byt SF_ADD
.byt SF_GETVAL,64, 200	; i
.byt 1
.byt SC_WAIT_FOR_ACTOR
.byt 22
; Increment expression
.byt SC_ASSIGN, 64, 200	; i=i+2
.byt SF_ADD
.byt SF_GETVAL,64, 200	; i
.byt 2
; end for
.byt SC_JUMP, 35, 0	; jump to 35
; for
; Init part
.byt SC_ASSIGN, 64, 200	; i=14
.byt 14
; Condition
.byt SC_JUMP_IF, SF_NOT
.byt SF_LT
.byt SF_GETVAL,64, 200	; i
.byt 18
.word 108
; for body
.byt SC_ACTOR_TALK
.byt 22
.byt 64, 100
.byt SF_GETVAL,64, 200	; i
.byt SC_WAIT_FOR_ACTOR
.byt 22
; Increment expression
.byt SC_ASSIGN, 64, 200	; i=i+1
.byt SF_ADD
.byt SF_GETVAL,64, 200	; i
.byt 1
; end for
.byt SC_JUMP, 79, 0	; jump to 79
.byt SC_ACTOR_TALK
.byt 20
.byt 64, 100
.byt 18
.byt SC_WAIT_FOR_ACTOR
.byt 20
.byt SC_ACTOR_TALK
.byt 22
.byt 64, 100
.byt 19
.byt SC_WAIT_FOR_ACTOR
.byt 22
; for
; Init part
.byt SC_ASSIGN, 64, 200	; i=20
.byt 20
; Condition
.byt SC_JUMP_IF, SF_NOT
.byt SF_LT
.byt SF_GETVAL,64, 200	; i
.byt 23
.word 155
; for body
.byt SC_ACTOR_TALK
.byt 20
.byt 64, 100
.byt SF_GETVAL,64, 200	; i
.byt SC_WAIT_FOR_ACTOR
.byt 20
; Increment expression
.byt SC_ASSIGN, 64, 200	; i=i+1
.byt SF_ADD
.byt SF_GETVAL,64, 200	; i
.byt 1
; end for
.byt SC_JUMP, 126, 0	; jump to 126
.byt SC_ACTOR_TALK
.byt 22
.byt 64, 100
.byt 23
.byt SC_WAIT_FOR_ACTOR
.byt 22
.byt SC_DELAY
.byt 50
.byt SC_SET_OBJECT_POS
.byt 20
.byt 22
.byt 12
.byt 17
.byt SC_LOAD_ROOM
.byt 33
.byt SC_SET_CAMERA_AT
.byt 40
.byt SC_SHOW_VERBS
.byt 1
.byt SC_STOP_SCRIPT
res_end
.)

; String pack 100
.(
.byt RESOURCE_STRING
.word (res_end-res_start +4)
.byt 100
res_start
.asc "",126,"Encontr",94," Blake al resto?",0 ; String 0
.asc "Aun no. Apuesto a que acabar",91," muerto.",0 ; String 1
.asc "Para con eso.",0 ; String 2
.asc "Esta nave vale billones.",0 ; String 3
.asc "Fijo.",0 ; String 4
.asc "Podr",93,"as comprar lo que quisieses.",0 ; String 5
.asc "Probablemente...",0 ; String 6
.asc "Todo. Pi",92,"nsalo Jenna.",0 ; String 7
.asc "",126,"Y Blake?",0 ; String 8
.asc "Qu",92," pasa con ",92,"l.",0 ; String 9
.asc "No.",0 ; String 10
.asc "Podr",93,"amos tener un planeta propio.",0 ; String 11
.asc "No lo vamos a dejar aqu",93,".",0 ; String 12
.asc "Pero debemos. Es un cruzado.",0 ; String 13
.asc "Mirar",91," todo esto y s",94,"lo vera un arma",0 ; String 14
.asc "para utilizar contra la Federaci",94,"n.",0 ; String 15
.asc "Y no puede ganar. Sabes que no puede.",0 ; String 16
.asc "",126,"Prefieres ser rica o estar muerta?",0 ; String 17
.asc "Una hora. Esperaremos una hora.",0 ; String 18
.asc "",126,"Por qu",92,"? ",126,"para qu",92," esperar?",0 ; String 19
.asc "Para convencerme a m",93," misma de que le",0 ; String 20
.asc "dimos una oportunidad.",0 ; String 21
.asc "Si no ha vuelto para entonces...",0 ; String 22
.asc "Est",91," bien.",0 ; String 23
.asc " Mientras, en El Liberador...",0 ; String 24
.asc " ",0 ; String 25
res_end
.)
