;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Generated by OASIS compiler
; (c) Chema 2016
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


; Script 21
.(
.byt RESOURCE_SCRIPT
.word (res_end-res_start +4)
.byt 21
res_start
+script_21_start
.byt SC_SAVEGAME
.byt SC_LOCK_RESOURCE
.byt 4
.byt 2
.byt SC_SHOW_VERBS
.byt 0
.byt SC_SET_COSTUME
.byt 0
.byt 0
.byt 0
.byt SC_SET_COSTUME
.byt 20
.byt 1
.byt 0
.byt SC_SET_COSTUME
.byt 21
.byt 10
.byt 0
.byt SC_SET_COSTUME
.byt 23
.byt 12
.byt 0
.byt SC_SET_COSTUME
.byt 24
.byt 13
.byt 0
.byt SC_SET_OBJECT_POS
.byt 22
.byt 23
.byt 15
.byt 19
.byt SC_SET_ANIMSTATE
.byt 22
.byt 0
.byt SC_LOOK_DIRECTION
.byt 22
.byt 0
.byt SC_SET_OBJECT_POS
.byt 0
.byt 23
.byt 14
.byt 5
.byt SC_LOOK_DIRECTION
.byt 0
.byt 3
.byt SC_FOLLOW_ACTOR
.byt 0
.byt SC_ASSIGN, 0	; tmpParam1=0
.byt 0
.byt SC_LOAD_ROOM
.byt 23
.byt SC_BREAK_HERE
.byt SC_ACTOR_WALKTO
.byt 0
.byt 8
.byt 15
.byt SC_WAIT_FOR_ACTOR
.byt 0
; for
; Init part
.byt SC_ASSIGN, 64, 200	; i=0
.byt 0
; Condition
.byt SC_JUMP_IF, SF_NOT
.byt SF_LE
.byt SF_GETVAL,64, 200	; i
.byt 10
.word 225
; for body
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_OR
.byt SF_OR
.byt SF_OR
.byt SF_OR
.byt SF_OR
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 0
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 2
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 4
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 5
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 8
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 10
.byt 44
; then part
.byt SC_ASSIGN, 64, 201	; actor=0
.byt 0
.byt SC_JUMP_REL, 6
; else part
.byt SC_ASSIGN, 64, 201	; actor=22
.byt 22
.byt SC_ACTOR_TALK
.byt SF_GETVAL,64, 201	; actor
.byt 2
.byt SF_GETVAL,64, 200	; i
.byt SC_WAIT_FOR_ACTOR
.byt SF_GETVAL,64, 201	; actor
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_OR
.byt SF_OR
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 0
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 2
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 5
.byt 23
; then part
.byt SC_LOOK_DIRECTION
.byt 22
.byt 1
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 3
.byt 20
; then part
.byt SC_LOOK_DIRECTION
.byt 22
.byt 2
.byt SC_DELAY
.byt 20
.byt SC_ACTOR_WALKTO
.byt 0
.byt 10
.byt 15
.byt SC_LOOK_DIRECTION
.byt 0
.byt 0
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 7
.byt 11
; then part
.byt SC_LOOK_DIRECTION
.byt 22
.byt 0
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_OR
.byt SF_OR
.byt SF_OR
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 3
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 6
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 7
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 9
.byt 28
; then part
.byt SC_DELAY
.byt 30
; Increment expression
.byt SC_ASSIGN, 64, 200	; i=i+1
.byt SF_ADD
.byt SF_GETVAL,64, 200	; i
.byt 1
; end for
.byt SC_JUMP, 63, 0	; jump to 63
.byt SC_LOOK_DIRECTION
.byt 22
.byt 2
.byt SC_DELAY
.byt 20
.byt SC_ACTOR_TALK
.byt 0
.byt 2
.byt 11
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_LOOK_DIRECTION
.byt 22
.byt 0
.byt SC_BREAK_HERE
.byt SC_ACTOR_TALK
.byt 22
.byt 2
.byt 12
.byt SC_WAIT_FOR_ACTOR
.byt 22
.byt SC_ACTOR_TALK
.byt 0
.byt 2
.byt 13
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_DELAY
.byt 20
.byt SC_LOOK_DIRECTION
.byt 22
.byt 1
.byt SC_ACTOR_TALK
.byt 22
.byt 2
.byt 14
.byt SC_WAIT_FOR_ACTOR
.byt 22
.byt SC_ACTOR_TALK
.byt 22
.byt 2
.byt 15
.byt SC_WAIT_FOR_ACTOR
.byt 22
.byt SC_ACTOR_TALK
.byt 0
.byt 2
.byt 16
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_ASSIGN, 0	; tmpParam1=13
.byt 13
.byt SC_CHAIN_SCRIPT
.byt 64, 202
.byt SC_ACTOR_TALK
.byt 0
.byt 2
.byt 17
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_ACTOR_TALK
.byt 0
.byt 2
.byt 18
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_ASSIGN, 0	; tmpParam1=10
.byt 10
.byt SC_CHAIN_SCRIPT
.byt 64, 202
.byt SC_BWPALETTE
.byt SC_PLAY_TUNE
.byt 1
.byt SC_WAIT_FOR_TUNE
.byt SC_TERMINATE_SCRIPT
.byt 64, 201
.byt SC_DELAY
.byt 30
.byt SC_SET_OVERRIDE
.word (l_here-res_start)
l_here
.byt SC_CLEAR_ROOMAREA
.byt SC_BREAK_HERE
.byt SC_PLAY_TUNE
.byt 2
.byt SC_ASSIGN, 64, 201	; actor=8
.byt 8
; for
; Init part
.byt SC_ASSIGN, 64, 200	; i=19
.byt 19
; Condition
.byt SC_JUMP_IF, SF_NOT
.byt SF_LE
.byt SF_GETVAL,64, 200	; i
.byt 30
.word 360
; for body
.byt SC_PRINT_AT
.byt 2
.byt SF_GETVAL,64, 200	; i
.byt 42
.byt SF_GETVAL,64, 201	; actor
.byt SC_ASSIGN, 64, 201	; actor=actor+8
.byt SF_ADD
.byt SF_GETVAL,64, 201	; actor
.byt 8
; Increment expression
.byt SC_ASSIGN, 64, 200	; i=i+1
.byt SF_ADD
.byt SF_GETVAL,64, 200	; i
.byt 1
; end for
.byt SC_JUMP, 67, 1	; jump to 323
.byt SC_DELAY
.byt 64, 200
.byt SC_DELAY
.byt 64, 200
.byt SC_DELAY
.byt 64, 200
.byt SC_CLEAR_ROOMAREA
.byt SC_BREAK_HERE
.byt SC_ASSIGN, 64, 201	; actor=0
.byt 0
; for
; Init part
.byt SC_ASSIGN, 64, 200	; i=31
.byt 31
; Condition
.byt SC_JUMP_IF, SF_NOT
.byt SF_LE
.byt SF_GETVAL,64, 200	; i
.byt 54
.word 416
; for body
.byt SC_PRINT_AT
.byt 2
.byt SF_GETVAL,64, 200	; i
.byt 0
.byt SF_GETVAL,64, 201	; actor
.byt SC_ASSIGN, 64, 201	; actor=actor+8
.byt SF_ADD
.byt SF_GETVAL,64, 201	; actor
.byt 8
; Increment expression
.byt SC_ASSIGN, 64, 200	; i=i+1
.byt SF_ADD
.byt SF_GETVAL,64, 200	; i
.byt 1
; end for
.byt SC_JUMP, 123, 1	; jump to 379
.byt SC_WAIT_FOR_TUNE
.byt SC_DELAY
.byt 64, 200
.byt SC_DELAY
.byt 64, 200
.byt SC_REMOVE_OBJECT
.byt 0
.byt SC_REMOVE_OBJECT
.byt 21
.byt SC_REMOVE_OBJECT
.byt 20
.byt SC_REMOVE_OBJECT
.byt 22
.byt SC_REMOVE_OBJECT
.byt 23
.byt SC_REMOVE_OBJECT
.byt 24
.byt SC_UNLOCK_RESOURCE
.byt 4
.byt 2
.byt SC_CLEAR_ROOMAREA
.byt SC_SHOW_VERBS
.byt 0
.byt SC_LOAD_ROOM
.byt 55
.byt SC_STOP_SCRIPT
res_end
.)

; String pack 2
.(
.byt RESOURCE_STRING
.word (res_end-res_start +4)
.byt 2
res_start
.asc "Avon.",0 ; String 0
.asc "Yes?",0 ; String 1
.asc "Good shot.",0 ; String 2
.asc "I was aiming for his head.",0 ; String 3
.asc "Why did you risk your life for us?",0 ; String 4
.asc "With the Liberator you don't need us.",0 ; String 5
.asc "My odds where 2.5 to 3 on survival.",0 ; String 6
.asc "I checked.",0 ; String 7
.asc "Sounds like a good probability to me.",0 ; String 8
.asc "Yeah. I'm as surprised as you are.",0 ; String 9
.asc "I'm not surprised.",0 ; String 10
.asc "Seven of us can run this ship properly.",0 ; String 11
.asc "Six surely.",0 ; String 12
.asc "You forgot Zen.",0 ; String 13
.asc "You're not counting that machine as a",0 ; String 14
.asc "member of the crew...",0 ; String 15
.asc "Oh, what do you say to that Zen?",0 ; String 16
.asc "Very diplomatic. Set a course for",0 ; String 17
.asc "sector 5,0,2. Speed standard-by-two.",0 ; String 18
.asc "",A_FWYELLOW,"Original TV Series Cast",0 ; String 19
.asc " ",0 ; String 20
.asc "",A_FWCYAN,"Blake    ",A_FWWHITE,"Gareth Thomas",0 ; String 21
.asc "",A_FWCYAN,"Avon     ",A_FWWHITE,"Paul Darrow",0 ; String 22
.asc "",A_FWCYAN,"Vila     ",A_FWWHITE,"Michael Keating",0 ; String 23
.asc "",A_FWCYAN,"Jenna    ",A_FWWHITE,"Sally Knyvette",0 ; String 24
.asc "",A_FWCYAN,"Gan      ",A_FWWHITE,"David Jackson",0 ; String 25
.asc "",A_FWCYAN,"Cally    ",A_FWWHITE,"Jan Chapell",0 ; String 26
.asc "",A_FWCYAN,"Zen      ",A_FWWHITE,"Peter Tuddenham",0 ; String 27
.asc "",A_FWCYAN,"Servalan ",A_FWWHITE,"Jaqueline Pierce",0 ; String 28
.asc "",A_FWCYAN,"Travis   ",A_FWWHITE,"Stephen Greif",0 ; String 29
.asc "",A_FWCYAN,"         ",A_FWWHITE,"Brian Croucher",0 ; String 30
.asc "",A_FWYELLOW,"BLAKE'S 7: The Oric Game",0 ; String 31
.asc " ",0 ; String 32
.asc "",A_FWWHITE,"I hope you enjoyed playing this game",0 ; String 33
.asc "",A_FWWHITE,"as much as I enjoyed creating it.",0 ; String 34
.asc " ",0 ; String 35
.asc "",A_FWWHITE,"Many thanks to everyone who helped",0 ; String 36
.asc "",A_FWWHITE,"with suggestions, feedback, and",0 ; String 37
.asc "",A_FWWHITE,"encouragement during this process.",0 ; String 38
.asc " ",0 ; String 39
.asc "",A_FWWHITE,"Special thanks to the incredible",0 ; String 40
.asc "",A_FWWHITE,"people of RetroWiki, Defence-Force,",0 ; String 41
.asc "",A_FWWHITE,"and AmigaWave.",0 ; String 42
.asc " ",0 ; String 43
.asc "",A_FWWHITE,"Thanks to Greymagick, as usual, for",0 ; String 44
.asc "",A_FWWHITE,"his invaluable advice - and patience.",0 ; String 45
.asc " ",0 ; String 46
.asc "",A_FWWHITE,"Thanks to jojo073 for his incredible",0 ; String 47
.asc "",A_FWWHITE,"graphic designs.",0 ; String 48
.asc " ",0 ; String 49
.asc "",A_FWWHITE,"And thanks to the Oric community for",0 ; String 50
.asc "",A_FWWHITE,"being there. This time I wanted to",0 ; String 51
.asc "",A_FWWHITE,"create something really special.",0 ; String 52
.asc " ",0 ; String 53
.asc "",A_FWYELLOW,"(C)Chema (enguita AT gmail.com) 2017",0 ; String 54
res_end
.)
