;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Generated by OASIS compiler
; (c) Chema 2016
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


; Script 19
.(
.byt RESOURCE_SCRIPT
.word (res_end-res_start +4)
.byt 19
res_start
+script_19_start
.byt SC_SHOW_VERBS
.byt 0
.byt SC_LOCK_RESOURCE
.byt 4
.byt 2
.byt SC_ACTOR_TALK
.byt 0
.byt 2
.byt 17
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_ACTOR_TALK
.byt 0
.byt 2
.byt 18
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_ACTOR_TALK
.byt 20
.byt 2
.byt 19
.byt SC_WAIT_FOR_ACTOR
.byt 20
.byt SC_ACTOR_TALK
.byt 0
.byt 2
.byt 20
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_ACTOR_TALK
.byt 0
.byt 2
.byt 21
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_SET_OBJECT_POS
.byt 22
.byt 22
.byt 11
.byt 33
.byt SC_LOOK_DIRECTION
.byt 22
.byt 0
.byt SC_LOAD_ROOM
.byt 22
.byt SC_SET_CAMERA_AT
.byt 50
.byt SC_BREAK_HERE
.byt SC_ACTOR_TALK
.byt 23
.byt 2
.byt 0
.byt SC_WAIT_FOR_ACTOR
.byt 23
.byt SC_ACTOR_TALK
.byt 23
.byt 2
.byt 1
.byt SC_WAIT_FOR_ACTOR
.byt 23
.byt SC_ACTOR_TALK
.byt 21
.byt 2
.byt 2
.byt SC_WAIT_FOR_ACTOR
.byt 21
.byt SC_ACTOR_TALK
.byt 21
.byt 2
.byt 3
.byt SC_WAIT_FOR_ACTOR
.byt 21
.byt SC_ACTOR_TALK
.byt 21
.byt 2
.byt 4
.byt SC_WAIT_FOR_ACTOR
.byt 21
.byt SC_ACTOR_TALK
.byt 22
.byt 2
.byt 5
.byt SC_WAIT_FOR_ACTOR
.byt 22
.byt SC_ACTOR_TALK
.byt 21
.byt 2
.byt 6
.byt SC_WAIT_FOR_ACTOR
.byt 21
.byt SC_ACTOR_TALK
.byt 22
.byt 2
.byt 7
.byt SC_WAIT_FOR_ACTOR
.byt 22
.byt SC_ACTOR_TALK
.byt 21
.byt 2
.byt 8
.byt SC_WAIT_FOR_ACTOR
.byt 21
.byt SC_ACTOR_TALK
.byt 22
.byt 2
.byt 9
.byt SC_WAIT_FOR_ACTOR
.byt 22
.byt SC_ACTOR_TALK
.byt 22
.byt 2
.byt 10
.byt SC_WAIT_FOR_ACTOR
.byt 22
.byt SC_ACTOR_WALKTO
.byt 23
.byt 17
.byt 15
.byt SC_DELAY
.byt 50
.byt SC_LOOK_DIRECTION
.byt 22
.byt 1
.byt SC_ACTOR_TALK
.byt 22
.byt 2
.byt 11
.byt SC_WAIT_FOR_ACTOR
.byt 22
.byt SC_WAIT_FOR_ACTOR
.byt 23
.byt SC_LOOK_DIRECTION
.byt 23
.byt 0
.byt SC_ACTOR_TALK
.byt 23
.byt 2
.byt 12
.byt SC_WAIT_FOR_ACTOR
.byt 23
.byt SC_ACTOR_TALK
.byt 23
.byt 2
.byt 13
.byt SC_WAIT_FOR_ACTOR
.byt 23
.byt SC_ACTOR_TALK
.byt 22
.byt 2
.byt 14
.byt SC_WAIT_FOR_ACTOR
.byt 22
.byt SC_ACTOR_TALK
.byt 22
.byt 2
.byt 15
.byt SC_WAIT_FOR_ACTOR
.byt 22
.byt SC_ACTOR_TALK
.byt 23
.byt 2
.byt 16
.byt SC_WAIT_FOR_ACTOR
.byt 23
.byt SC_DELAY
.byt 50
.byt SC_LOAD_ROOM
.byt 49
.byt SC_BREAK_HERE
.byt SC_CLEAR_EVENTS
.byt 1
.byt SC_PLAYSFX
.byt 9
.byt SC_CLEAR_EVENTS
.byt 2
.byt SC_ASSIGN, 0	; tmpParam1=23
.byt 23
.byt SC_ASSIGN, 1	; tmpParam2=14
.byt 14
.byt SC_ASSIGN, 2	; tmpParam3=3
.byt 3
.byt SC_SPAWN_SCRIPT
.byt 7
.byt SC_WAIT_EVENT
.byt 2
.byt SC_ASSIGN, 0	; tmpParam1=21
.byt 21
.byt SC_ASSIGN, 1	; tmpParam2=16
.byt 16
.byt SC_ASSIGN, 2	; tmpParam3=8
.byt 8
.byt SC_CHAIN_SCRIPT
.byt 7
.byt SC_DELAY
.byt 20
.byt SC_LOOK_DIRECTION
.byt 0
.byt 1
.byt SC_ACTOR_TALK
.byt 0
.byt 2
.byt 22
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_LOOK_DIRECTION
.byt 20
.byt 1
.byt SC_ACTOR_TALK
.byt 20
.byt 2
.byt 23
.byt SC_WAIT_FOR_ACTOR
.byt 20
.byt SC_ACTOR_TALK
.byt 21
.byt 2
.byt 24
.byt SC_WAIT_FOR_ACTOR
.byt 21
.byt SC_ACTOR_WALKTO
.byt 21
.byt 8
.byt 13
.byt SC_WAIT_FOR_ACTOR
.byt 21
.byt SC_LOOK_DIRECTION
.byt 21
.byt 0
.byt SC_DELAY
.byt 30
.byt SC_ACTOR_TALK
.byt 21
.byt 2
.byt 25
.byt SC_WAIT_FOR_ACTOR
.byt 21
.byt SC_ACTOR_TALK
.byt 21
.byt 2
.byt 26
.byt SC_WAIT_FOR_ACTOR
.byt 21
.byt SC_DELAY
.byt 60
.byt SC_LOAD_OBJECT
.byt 51
.byt SC_SET_OBJECT_POS
.byt 51
.byt 49
.byt 10
.byt 12
.byt SC_SET_ANIMSTATE
.byt 51
.byt 0
.byt SC_ACTOR_TALK
.byt 21
.byt 2
.byt 27
.byt SC_WAIT_FOR_ACTOR
.byt 21
.byt SC_ACTOR_WALKTO
.byt 21
.byt 4
.byt 13
.byt SC_WAIT_FOR_ACTOR
.byt 21
.byt SC_LOOK_DIRECTION
.byt 21
.byt 0
.byt SC_ACTOR_TALK
.byt 0
.byt 2
.byt 28
.byt SC_LOOK_DIRECTION
.byt 20
.byt 3
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_ACTOR_TALK
.byt 20
.byt 2
.byt 29
.byt SC_WAIT_FOR_ACTOR
.byt 20
.byt SC_LOOK_DIRECTION
.byt 0
.byt 1
.byt SC_ACTOR_TALK
.byt 0
.byt 2
.byt 30
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_SETFLAG, 64, 68	; bClockTampered=true
.byt 1
.byt SC_UNLOCK_RESOURCE
.byt 4
.byt 2
.byt SC_SHOW_VERBS
.byt 1
.byt SC_SAVEGAME
.byt SC_STOP_SCRIPT
res_end
.)

; String pack 2
.(
.byt RESOURCE_STRING
.word (res_end-res_start +4)
.byt 2
res_start
.asc "Understood, Blake.",0 ; String 0
.asc "Vila and I will teleport down.",0 ; String 1
.asc "Me? No, wait a minute, it's cold out",0 ; String 2
.asc "there and I'm very susceptible to low",0 ; String 3
.asc "temperatures. I've got a weak chest!",0 ; String 4
.asc "The rest of you's not very impressive.",0 ; String 5
.asc "Why don't you go?",0 ; String 6
.asc "You are expendable.",0 ; String 7
.asc "And you're not?",0 ; String 8
.asc "No, I am not. I am not expendable,",0 ; String 9
.asc "I'm not stupid, and I'm not going.",0 ; String 10
.asc "I'm starting to smell a trap here.",0 ; String 11
.asc "It's not a very good one, then.",0 ; String 12
.asc "We're suspicious of it already.",0 ; String 13
.asc "The test is not whether you are",0 ; String 14
.asc "suspicious but whether you are caught.",0 ; String 15
.asc "Come on, Vila. Let's go.",0 ; String 16
.asc "Jenna, we need to hack the clock.",0 ; String 17
.asc "Could it be done from here?",0 ; String 18
.asc "Sure, but not by me. Vila or Avon can.",0 ; String 19
.asc "Okay. Liberator, do you hear me?",0 ; String 20
.asc "I need Avon or Vila to come down here.",0 ; String 21
.asc "I need to move the clock forward one",0 ; String 22
.asc "hour. Can you do it?",0 ; String 23
.asc "Let me check...",0 ; String 24
.asc "Yeah. But I need an emitter with...",0 ; String 25
.asc "One sec. Gimme the transponder.",0 ; String 26
.asc "See? Done!",0 ; String 27
.asc "Good. Now wait here for my signal.",0 ; String 28
.asc "Take care.",0 ; String 29
.asc "Will do.",0 ; String 30
res_end
.)
