;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Generated by OASIS compiler
; (c) Chema 2016
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


; Script 0
.(
.byt RESOURCE_SCRIPT
.word (res_end-res_start +4)
.byt 0
res_start
+script_0_start
.byt SC_SETFLAG, 0	; bReadMapPoster=false
.byt 0
.byt SC_SETFLAG, 1	; bManTalkedBoutCoffee=false
.byt 0
.byt SC_SETFLAG, 2	; bMetRavella=false
.byt 0
.byt SC_SETFLAG, 3	; bMapContactGiven=false
.byt 0
.byt SC_SETFLAG, 4	; bTradeInitiated=false
.byt 0
.byt SC_SETFLAG, 5	; bMugGiven=false
.byt 0
.byt SC_SETFLAG, 7	; bMapPrinted=false
.byt 0
.byt SC_SETFLAG, 8	; bGotMap=false
.byt 0
.byt SC_SETFLAG, 9	; bEscapeFromNurse=false
.byt 0
.byt SC_SETFLAG, 10	; bNurseGaveLaxative=false
.byt 0
.byt SC_SETFLAG, 11	; bCouchPushed=false
.byt 0
.byt SC_SETFLAG, 12	; bAutoExit=false
.byt 0
.byt SC_SETFLAG, 13	; bGuardWentForCoffee=false
.byt 0
.byt SC_SETFLAG, 18	; bSnoringHeard=false
.byt 0
.byt SC_SETFLAG, 14	; bSandwichGiven=false
.byt 0
.byt SC_SETFLAG, 15	; bTechcamOut=false
.byt 0
.byt SC_SETFLAG, 16	; bCoinStuck=false
.byt 0
.byt SC_SETFLAG, 17	; bGuardInCtrlRoom=false
.byt 0
.byt SC_SETFLAG, 19	; bDecafReady=false
.byt 0
.byt SC_SETFLAG, 20	; bCamDeactivated=false
.byt 0
.byt SC_SETFLAG, 21	; bCamCodeSeen=false
.byt 0
.byt SC_SETFLAG, 22	; bGratingOpen=false
.byt 0
.byt SC_SETFLAG, 25	; bEnvelopeExamined=false
.byt 0
.byt SC_SETFLAG, 51	; bCellPlaced=false
.byt 0
.byt SC_ASSIGN, 3	; nPushMachine=0
.byt 0
.byt SC_ASSIGN, 4	; nMsgInfo=0
.byt 0
.byt SC_LOAD_RESOURCE
.byt 4
.byt 0
.byt SC_LOCK_RESOURCE
.byt 4
.byt 0
.byt SC_LOAD_RESOURCE
.byt 1
.byt 1
.byt SC_LOCK_RESOURCE
.byt 1
.byt 1
.byt SC_CHAIN_SCRIPT
.byt 2
.byt SC_LOAD_OBJECT
.byt 0
.byt SC_SET_EGO
.byt 0
.byt SC_FOLLOW_ACTOR
.byt 0
.byt SC_LOCK_RESOURCE
.byt 3
.byt 0
.byt SC_LOAD_OBJECT
.byt 2
.byt SC_LOAD_OBJECT
.byt 3
.byt SC_LOAD_OBJECT
.byt 4
.byt SC_LOAD_OBJECT
.byt 10
.byt SC_LOAD_OBJECT
.byt 11
.byt SC_SET_FADEEFFECT
.byt SF_ADD
.byt 1
.byt 64, 128
.byt SC_LOAD_ROOM
.byt 2
.byt SC_SET_COSTUME
.byt 3
.byt 64, 210
.byt 0
.byt SC_SET_COSTUME
.byt 4
.byt 64, 211
.byt 0
.byt SC_SET_ANIMSTATE
.byt 3
.byt 0
.byt SC_SET_ANIMSTATE
.byt 4
.byt 0
.byt SC_SET_OBJECT_POS
.byt 0
.byt 2
.byt 13
.byt 14
.byt SC_LOOK_DIRECTION
.byt 0
.byt 3
.byt SC_BREAK_HERE
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 0
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_ACTOR_TALK
.byt 0
.byt 64, 200
.byt 1
.byt SC_WAIT_FOR_ACTOR
.byt 0
.byt SC_SHOW_VERBS
.byt 1
.byt SC_CHAIN_SCRIPT
.byt 30
.byt SC_STOP_SCRIPT
res_end
.)
