;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Generated by OASIS compiler
; (c) Chema 2016
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


; Script 7
.(
.byt RESOURCE_SCRIPT
.word (res_end-res_start +4)
.byt 7
res_start
+script_7_start
.byt SC_ASSIGN, 64, 200	; actor=tmpParam1
.byt SF_GETVAL,0	; tmpParam1
.byt SC_ASSIGN, 64, 201	; row=tmpParam2
.byt SF_GETVAL,1	; tmpParam2
.byt SC_ASSIGN, 64, 202	; col=tmpParam3
.byt SF_GETVAL,2	; tmpParam3
.byt SC_SET_EVENTS
.byt 2
.byt SC_BREAK_HERE
.byt SC_DELAY
.byt 10
.byt SC_WAIT_EVENT
.byt 1
.byt SC_ASSIGN, 64, 203	; cosid=sfGetCostumeID(actor)
.byt SF_GET_COSTID
.byt SF_GETVAL,64, 200	; actor
.byt SC_ASSIGN, 64, 204	; cosno=sfGetCostumeNo(actor)
.byt SF_GET_COSTNO
.byt SF_GETVAL,64, 200	; actor
.byt SC_SET_COSTUME
.byt SF_GETVAL,64, 200	; actor
.byt 14
.byt 0
.byt SC_SET_OBJECT_POS
.byt SF_GETVAL,64, 200	; actor
.byt SF_GET_CURROOM
.byt SF_GETVAL,64, 201	; row
.byt SF_GETVAL,64, 202	; col
.byt SC_LOOK_DIRECTION
.byt SF_GETVAL,64, 200	; actor
.byt 0
.byt SC_SET_ANIMSTATE
.byt SF_GETVAL,64, 200	; actor
.byt 11
.byt SC_DELAY
.byt 5
.byt SC_SET_ANIMSTATE
.byt SF_GETVAL,64, 200	; actor
.byt 10
.byt SC_DELAY
.byt 5
.byt SC_SET_ANIMSTATE
.byt SF_GETVAL,64, 200	; actor
.byt 9
.byt SC_DELAY
.byt 5
.byt SC_SET_ANIMSTATE
.byt SF_GETVAL,64, 200	; actor
.byt 8
.byt SC_WAIT_FOR_TUNE
.byt SC_SET_COSTUME
.byt SF_GETVAL,64, 200	; actor
.byt SF_GETVAL,64, 203	; cosid
.byt SF_GETVAL,64, 204	; cosno
.byt SC_SET_ANIMSTATE
.byt SF_GETVAL,64, 200	; actor
.byt 0
.byt SC_STOP_SCRIPT
res_end
.)
