;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Generated by OASIS compiler
; (c) Chema 2016
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


; Script 15
.(
.byt RESOURCE_SCRIPT
.word (res_end-res_start +4)
.byt 15
res_start
+script_15_start
.byt SC_SET_FADEEFFECT
.byt 0
.byt SC_CLEAR_ROOMAREA
.byt SC_LOCK_RESOURCE
.byt 4
.byt 64, 106
.byt SC_LOAD_ROOM
.byt 40
.byt SC_SET_OVERRIDE
.word (l_here-res_start)
.byt SC_DELAY
.byt 64, 100
.byt SC_CLEAR_ROOMAREA
.byt SC_LOAD_ROOM
.byt 64, 200
.byt SC_PLAY_TUNE
.byt 3
.byt SC_SET_CAMERA_AT
.byt 64, 120
.byt SC_BREAK_HERE
.byt SC_PAN_CAMERA
.byt 0
.byt SC_WAIT_FOR_CAMERA
.byt SC_DELAY
.byt 50
.byt SC_PRINT_AT
.byt 64, 106
.byt 0
.byt 8
.byt 64, 120
.byt SC_DELAY
.byt 64, 80
.byt SC_DELAY
.byt 64, 100
l_here
.byt SC_STOP_TUNE
.byt SC_SET_OVERRIDE
.word (l_here2-res_start)
.byt SC_LOAD_OBJECT
.byt 26
.byt SC_LOAD_OBJECT
.byt 25
.byt SC_SET_OBJECT_POS
.byt 25
.byt 64, 201
.byt 15
.byt 20
.byt SC_SET_OBJECT_POS
.byt 26
.byt 64, 201
.byt 15
.byt 37
.byt SC_LOOK_DIRECTION
.byt 25
.byt 1
.byt SC_LOOK_DIRECTION
.byt 26
.byt 1
.byt SC_LOAD_ROOM
.byt 64, 201
.byt SC_ACTOR_WALKTO
.byt 26
.byt 32
.byt 15
.byt SC_WAIT_FOR_ACTOR
.byt 26
.byt SC_DELAY
.byt 50
.byt SC_ASSIGN, 64, 201	; a=25
.byt 25
; for
; Init part
.byt SC_ASSIGN, 64, 200	; i=1
.byt 1
; Condition
.byt SC_JUMP_IF, SF_NOT
.byt SF_LE
.byt SF_GETVAL,64, 200	; i
.byt 60
.word 434
; for body
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_GE
.byt SF_GETVAL,64, 200	; i
.byt 14
.byt 12
; then part
.byt SC_ASSIGN, 64, 201	; a=26
.byt 26
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 25
.byt 53
; then part
.byt SC_LOAD_ROOM
.byt 64, 210
.byt SC_DELAY
.byt 60
; for
; Init part
.byt SC_ASSIGN, 64, 200	; i=25
.byt 25
; Condition
.byt SC_JUMP_IF, SF_NOT
.byt SF_LE
.byt SF_GETVAL,64, 200	; i
.byt 32
.word 155
; for body
.byt SC_PRINT
.byt 64, 106
.byt SF_GETVAL,64, 200	; i
.byt SC_DELAY
.byt 64, 120
; Increment expression
.byt SC_ASSIGN, 64, 200	; i=i+1
.byt SF_ADD
.byt SF_GETVAL,64, 200	; i
.byt 1
; end for
.byt SC_JUMP, 126, 0	; jump to 126
.byt SC_PRINT
.byt 64, 106
.byt 61
.byt SC_LOAD_ROOM
.byt 64, 201
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 33
.byt 53
; then part
.byt SC_LOAD_ROOM
.byt 64, 211
.byt SC_DELAY
.byt 60
; for
; Init part
.byt SC_ASSIGN, 64, 200	; i=33
.byt 33
; Condition
.byt SC_JUMP_IF, SF_NOT
.byt SF_LE
.byt SF_GETVAL,64, 200	; i
.byt 38
.word 208
; for body
.byt SC_PRINT
.byt 64, 106
.byt SF_GETVAL,64, 200	; i
.byt SC_DELAY
.byt 64, 120
; Increment expression
.byt SC_ASSIGN, 64, 200	; i=i+1
.byt SF_ADD
.byt SF_GETVAL,64, 200	; i
.byt 1
; end for
.byt SC_JUMP, 179, 0	; jump to 179
.byt SC_PRINT
.byt 64, 106
.byt 61
.byt SC_LOAD_ROOM
.byt 64, 201
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_GE
.byt SF_GETVAL,64, 200	; i
.byt 39
.byt 12
; then part
.byt SC_ASSIGN, 64, 201	; a=25
.byt 25
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 43
.byt 12
; then part
.byt SC_ASSIGN, 64, 201	; a=26
.byt 26
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_GE
.byt SF_GETVAL,64, 200	; i
.byt 44
.byt 12
; then part
.byt SC_ASSIGN, 64, 201	; a=25
.byt 25
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_GE
.byt SF_GETVAL,64, 200	; i
.byt 48
.byt 12
; then part
.byt SC_ASSIGN, 64, 201	; a=26
.byt 26
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_GE
.byt SF_GETVAL,64, 200	; i
.byt 50
.byt 12
; then part
.byt SC_ASSIGN, 64, 201	; a=25
.byt 25
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 52
.byt 12
; then part
.byt SC_ASSIGN, 64, 201	; a=26
.byt 26
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_GE
.byt SF_GETVAL,64, 200	; i
.byt 53
.byt 12
; then part
.byt SC_ASSIGN, 64, 201	; a=25
.byt 25
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 57
.byt 12
; then part
.byt SC_ASSIGN, 64, 201	; a=26
.byt 26
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_GE
.byt SF_GETVAL,64, 200	; i
.byt 58
.byt 12
; then part
.byt SC_ASSIGN, 64, 201	; a=25
.byt 25
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 60
.byt 12
; then part
.byt SC_ASSIGN, 64, 201	; a=26
.byt 26
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_OR
.byt SF_OR
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 5
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 25
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 44
.byt 25
; then part
.byt SC_LOOK_DIRECTION
.byt 25
.byt 0
.byt SC_DELAY
.byt 30
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_OR
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 39
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 58
.byt 19
; then part
.byt SC_LOOK_DIRECTION
.byt 25
.byt 1
.byt SC_DELAY
.byt 30
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 17
.byt 14
; then part
.byt SC_ACTOR_WALKTO
.byt 25
.byt 20
.byt 14
.byt SC_WAIT_FOR_ACTOR
.byt 25
; if
.byt SC_JUMP_REL_IF, SF_NOT
.byt SF_EQ
.byt SF_GETVAL,64, 200	; i
.byt 33
.byt 17
; then part
.byt SC_LOOK_DIRECTION
.byt 25
.byt 2
.byt SC_ACTOR_WALKTO
.byt 26
.byt 30
.byt 15
.byt SC_DELAY
.byt 30
.byt SC_ACTOR_TALK
.byt SF_GETVAL,64, 201	; a
.byt 64, 106
.byt SF_GETVAL,64, 200	; i
.byt SC_WAIT_FOR_ACTOR
.byt SF_GETVAL,64, 201	; a
; Increment expression
.byt SC_ASSIGN, 64, 200	; i=i+1
.byt SF_ADD
.byt SF_GETVAL,64, 200	; i
.byt 1
; end for
.byt SC_JUMP, 88, 0	; jump to 88
l_here2
.byt SC_UNLOCK_RESOURCE
.byt 4
.byt 64, 106
.byt SC_DELAY
.byt 50
.byt SC_CLEAR_ROOMAREA
.byt SC_REMOVE_OBJECT
.byt 26
.byt SC_REMOVE_OBJECT
.byt 25
.byt SC_SPAWN_SCRIPT
.byt 16
.byt SC_STOP_SCRIPT
res_end
.)

; String pack 106
.(
.byt RESOURCE_STRING
.word (res_end-res_start +4)
.byt 106
res_start
.asc "",A_FWMAGENTA+A_FWCYAN*8+128,"Federaci",94,"n. Comandancia del Espacio.",0 ; String 0
.asc "Ah, Travis. Pasa. Mi departamento ha",0 ; String 1
.asc "hecho lo posile para eliminar toda la",0 ; String 2
.asc "informaci",94,"n sobre Blake y su grupo,",0 ; String 3
.asc "pero las historias se propagan...",0 ; String 4
.asc "A tav",92,"s del boca a boca, del rumor,",0 ; String 5
.asc "cada vez que se cuenta se vuelve m",91,"s",0 ; String 6
.asc "elaborada y exagerada.",0 ; String 7
.asc "Cualquier da",35,"o a la Federaci",94,"n se",0 ; String 8
.asc "atribuye a Blake. El incidente m",91,"s",0 ; String 9
.asc "peque",35,"o se exagera hasta que se",0 ; String 10
.asc "convierte en algo her",94,"ico.",0 ; String 11
.asc "Blake se hace una leyenda.",0 ; String 12
.asc "Hay que detenerle.",0 ; String 13
.asc "Soy consciente del peligro de que se",0 ; String 14
.asc "vuelva una leyenda, pero no hay que",0 ; String 15
.asc "perder la perspectiva.       ",0 ; String 16
.asc "Es cierto que Blake comanda una nave",0 ; String 17
.asc "soberbia, pero no es m",91,"s que un hombre",0 ; String 18
.asc "ayudado por un pu",35,"ado de criminales.",0 ; String 19
.asc "Nada m",91,"s. No es invulnerable, ni es",0 ; String 20
.asc "tampoco un superhombre.",0 ; String 21
.asc "S",94,"lo es un hombre que ha tenido una",0 ; String 22
.asc "suerte extrema para evitar su captura",0 ; String 23
.asc "-- por el momento.",0 ; String 24
.asc "",A_FWMAGENTA,"Soy consciente de los hechos. Es que",0 ; String 25
.asc "",A_FWMAGENTA,"simplemente con todos los recursos de",0 ; String 26
.asc "",A_FWMAGENTA,"que la Federaci",94,"n puede disponer, este",0 ; String 27
.asc "",A_FWMAGENTA,"hombre vulnerable, pero afortunado,",0 ; String 28
.asc "",A_FWMAGENTA,"todav",93,"a est",91," causando problemas.",0 ; String 29
.asc "",A_FWMAGENTA,"Deber",93,"as saber que empieza a haber",0 ; String 30
.asc "",A_FWMAGENTA,"muchas cr",93,"ticas a tu forma de manejar",0 ; String 31
.asc "",A_FWMAGENTA,"el asunto Blake.",0 ; String 32
.asc "",A_FWWHITE+A_FWGREEN*8+$c0,"Eso no es del todo justo. Hubo dos",0 ; String 33
.asc "",A_FWWHITE+A_FWGREEN*8+$c0,"ocasiones en las que pude haber acabado",0 ; String 34
.asc "",A_FWWHITE+A_FWGREEN*8+$c0,"con Blake. S",94,"lo la insistencia que",0 ; String 35
.asc "",A_FWWHITE+A_FWGREEN*8+$c0,"muestra la Administraci",94,"n en que el",0 ; String 36
.asc "",A_FWWHITE+A_FWGREEN*8+$c0,"Libertador se capture sin da",35,"o alguno",0 ; String 37
.asc "",A_FWWHITE+A_FWGREEN*8+$c0,"me detuvo.",0 ; String 38
.asc "Ya hice esa observaci",94,"n en tu defensa,",0 ; String 39
.asc "pero ya no puedo seguir poniendo m",91,"s",0 ; String 40
.asc "excusas. Me encuentro bajo una presi",94,"n",0 ; String 41
.asc "considerable para reemplazarte.",0 ; String 42
.asc "",126,"Eh?",0 ; String 43
.asc "Oh, hasta ahora he resistido esta",0 ; String 44
.asc "presi",94,"n. Pero ahora necesito que me",0 ; String 45
.asc "demuestres que no he depositado mi",0 ; String 46
.asc "confianza en la persona equivocada.",0 ; String 47
.asc "Creo que mi ",95,"ltimo plan silenciar",91,"",0 ; String 48
.asc "todas las cr",93,"ticas.",0 ; String 49
.asc "S",93," que parece un plan excelente. Tiene",0 ; String 50
.asc "todas las papeletas para ser un ",92,"xito.",0 ; String 51
.asc "Me alegro de que lo apruebe.",0 ; String 52
.asc "Oh, Travis, deber",93,"as saberlo mejor.",0 ; String 53
.asc "En mi posici",94,"n una nunca aprueba nada",0 ; String 54
.asc "hasta que no se ha convertido en un",0 ; String 55
.asc "",92,"xito sin paliativos.",0 ; String 56
.asc "Lo s",92,".",0 ; String 57
.asc "Sin embargo, tienes mi total apoyo,",0 ; String 58
.asc "extraoficialmente, por supuesto.",0 ; String 59
.asc "Por supuesto.",0 ; String 60
.asc " ",0 ; String 61
res_end
.)
