;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Generated by OASIS compiler
; (c) Chema 2016
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


; Script 2
.(
.byt RESOURCE_SCRIPT
.word (res_end-res_start +4)
.byt 2
res_start
+script_2_start
.byt SC_LOCK_RESOURCE
.byt 1
.byt 3
.byt SC_LOCK_RESOURCE
.byt 1
.byt 4
.byt SC_LOCK_RESOURCE
.byt 1
.byt 5
.byt SC_LOCK_RESOURCE
.byt 1
.byt 6
.byt SC_SET_FADEEFFECT
.byt 0
.byt SC_LOAD_ROOM
.byt 0
.byt SC_SET_OVERRIDE
.word (l_here-res_start)
.byt SC_SET_CAMERA_AT
.byt 64, 120
.byt SC_BREAK_HERE
.byt SC_DELAY
.byt 50
.byt SC_PRINT
.byt 64, 201
.byt 1
.byt SC_DELAY
.byt 64, 70
.byt SC_PAN_CAMERA
.byt 0
.byt SC_PLAY_TUNE
.byt 0
.byt SC_PRINT
.byt 64, 201
.byt 2
.byt SC_WAIT_FOR_CAMERA
.byt SC_PRINT
.byt 64, 201
.byt 3
.byt SC_DELAY
.byt 64, 150
.byt SC_PRINT
.byt 64, 201
.byt 0
.byt SC_LOAD_ROOM
.byt 64, 201
.byt SC_BREAK_HERE
.byt SC_PRINT_AT
.byt 64, 201
.byt 4
.byt 42
.byt 64, 119
.byt SC_DELAY
.byt 50
.byt SC_DELAY
.byt 50
.byt SC_LOAD_ROOM
.byt 64, 202
.byt SC_DELAY
.byt 50
.byt SC_PRINT_AT
.byt 64, 201
.byt 5
.byt 24
.byt SF_SUB
.byt 64, 123
.byt 4
.byt SC_PRINT_AT
.byt 64, 201
.byt 6
.byt 42
.byt SF_SUB
.byt 64, 131
.byt 4
.byt SC_CLEAR_EVENTS
.byt 1
.byt SC_WAIT_EVENT
.byt 1
.byt SC_LOAD_ROOM
.byt 64, 203
.byt SC_CLEAR_EVENTS
.byt 1
.byt SC_WAIT_EVENT
.byt 1
.byt SC_PRINT_AT
.byt 64, 201
.byt 11
.byt 54
.byt 64, 120
.byt SC_PRINT_AT
.byt 64, 201
.byt 7
.byt 64, 72
.byt 64, 128
.byt SC_CLEAR_EVENTS
.byt 1
.byt SC_WAIT_EVENT
.byt 1
.byt SC_PRINT_AT
.byt 64, 201
.byt 12
.byt 54
.byt 64, 120
.byt SC_PRINT_AT
.byt 64, 201
.byt 9
.byt 64, 72
.byt 64, 128
.byt SC_CLEAR_EVENTS
.byt 1
.byt SC_WAIT_EVENT
.byt 1
.byt SC_PRINT_AT
.byt 64, 201
.byt 13
.byt 54
.byt 64, 120
.byt SC_PRINT_AT
.byt 64, 201
.byt 7
.byt 64, 72
.byt 64, 128
.byt SC_CLEAR_EVENTS
.byt 1
.byt SC_WAIT_EVENT
.byt 1
.byt SC_PRINT_AT
.byt 64, 201
.byt 14
.byt 54
.byt 64, 120
.byt SC_PRINT_AT
.byt 64, 201
.byt 8
.byt 64, 72
.byt 64, 128
.byt SC_CLEAR_EVENTS
.byt 1
.byt SC_WAIT_EVENT
.byt 1
.byt SC_PRINT_AT
.byt 64, 201
.byt 15
.byt 54
.byt 64, 120
.byt SC_PRINT_AT
.byt 64, 201
.byt 10
.byt 64, 72
.byt 64, 128
.byt SC_CLEAR_EVENTS
.byt 1
.byt SC_WAIT_EVENT
.byt 1
.byt SC_PRINT_AT
.byt 64, 201
.byt 16
.byt 24
.byt 64, 112
.byt SC_PRINT_AT
.byt 64, 201
.byt 17
.byt 24
.byt 64, 120
.byt SC_PRINT_AT
.byt 64, 201
.byt 18
.byt 24
.byt 64, 128
.byt SC_WAIT_FOR_TUNE
l_here
.byt SC_STOP_TUNE
.byt SC_CLEAR_ROOMAREA
.byt SC_MENU
.byt SC_SET_OVERRIDE
.word (l_here2-res_start)
.byt SC_LOAD_ROOM
.byt 1
.byt SC_DELAY
.byt 64, 100
.byt SC_CLEAR_ROOMAREA
.byt SC_PRINT_AT
.byt 64, 200
.byt 0
.byt 42
.byt 20
.byt SC_DELAY
.byt 50
.byt SC_PRINT_AT
.byt 64, 200
.byt 1
.byt 60
.byt 30
.byt SC_DELAY
.byt 50
.byt SC_PRINT_AT
.byt 64, 200
.byt 2
.byt 64, 120
.byt 40
.byt SC_DELAY
.byt 50
.byt SC_PRINT_AT
.byt 64, 200
.byt 3
.byt 64, 78
.byt 50
.byt SC_DELAY
.byt 50
.byt SC_PRINT_AT
.byt 64, 200
.byt 4
.byt 48
.byt 60
.byt SC_DELAY
.byt 50
.byt SC_PRINT_AT
.byt 64, 200
.byt 5
.byt 64, 90
.byt 64, 80
.byt SC_DELAY
.byt 50
.byt SC_LOAD_ROOM
.byt 64, 200
.byt SC_DELAY
.byt 50
.byt SC_LOAD_ROOM
.byt 64, 201
.byt SC_DELAY
.byt 50
.byt SC_CLEAR_ROOMAREA
.byt SC_DELAY
.byt 60
.byt SC_ASSIGN, 64, 200	; line=24
.byt 24
; for
; Init part
.byt SC_ASSIGN, 64, 201	; sentence=6
.byt 6
; Condition
.byt SC_JUMP_IF, SF_NOT
.byt SF_LE
.byt SF_GETVAL,64, 201	; sentence
.byt 16
.word 343
; for body
.byt SC_PRINT_AT
.byt 64, 200
.byt SF_GETVAL,64, 201	; sentence
.byt 1
.byt SF_GETVAL,64, 200	; line
.byt SC_ASSIGN, 64, 200	; line=line+8
.byt SF_ADD
.byt SF_GETVAL,64, 200	; line
.byt 8
.byt SC_DELAY
.byt 20
; Increment expression
.byt SC_ASSIGN, 64, 201	; sentence=sentence+1
.byt SF_ADD
.byt SF_GETVAL,64, 201	; sentence
.byt 1
; end for
.byt SC_JUMP, 47, 1	; jump to 303
.byt SC_DELAY
.byt 64, 250
.byt SC_DELAY
.byt 64, 250
.byt SC_DELAY
.byt 64, 100
.byt SC_CLEAR_EVENTS
.byt 1
.byt SC_SPAWN_SCRIPT
.byt 3
.byt SC_DELAY
.byt 10
.byt SC_SPAWN_SCRIPT
.byt 4
.byt SC_DELAY
.byt 10
.byt SC_SPAWN_SCRIPT
.byt 5
.byt SC_DELAY
.byt 10
.byt SC_SPAWN_SCRIPT
.byt 6
.byt SC_WAIT_EVENT
.byt 1
l_here2
.byt SC_UNLOCK_RESOURCE
.byt 1
.byt 3
.byt SC_UNLOCK_RESOURCE
.byt 1
.byt 4
.byt SC_UNLOCK_RESOURCE
.byt 1
.byt 5
.byt SC_UNLOCK_RESOURCE
.byt 1
.byt 6
.byt SC_CLEAR_ROOMAREA
.byt SC_STOP_SCRIPT
res_end
.)

; Script 3
.(
.byt RESOURCE_SCRIPT
.word (res_end-res_start +4)
.byt 3
res_start
+script_3_start
; for
; Init part
.byt SC_ASSIGN, 64, 200	; i=16
.byt 16
; Condition
.byt SC_JUMP_IF, SF_NOT
.byt SF_LT
.byt SF_GETVAL,64, 200	; i
.byt 64, 128
.word 35
; for body
.byt SC_PRINT_AT
.byt 64, 201
.byt 0
.byt 0
.byt SF_GETVAL,64, 200	; i
.byt SC_DELAY
.byt 15
; Increment expression
.byt SC_ASSIGN, 64, 200	; i=i+8
.byt SF_ADD
.byt SF_GETVAL,64, 200	; i
.byt 8
; end for
.byt SC_JUMP, 4, 0	; jump to 4
.byt SC_STOP_SCRIPT
res_end
.)

; Script 4
.(
.byt RESOURCE_SCRIPT
.word (res_end-res_start +4)
.byt 4
res_start
+script_4_start
; for
; Init part
.byt SC_ASSIGN, 64, 200	; i=16
.byt 16
; Condition
.byt SC_JUMP_IF, SF_NOT
.byt SF_LT
.byt SF_GETVAL,64, 200	; i
.byt 64, 128
.word 35
; for body
.byt SC_PRINT_AT
.byt 64, 201
.byt 1
.byt 0
.byt SF_GETVAL,64, 200	; i
.byt SC_DELAY
.byt 15
; Increment expression
.byt SC_ASSIGN, 64, 200	; i=i+8
.byt SF_ADD
.byt SF_GETVAL,64, 200	; i
.byt 8
; end for
.byt SC_JUMP, 4, 0	; jump to 4
.byt SC_STOP_SCRIPT
res_end
.)

; Script 5
.(
.byt RESOURCE_SCRIPT
.word (res_end-res_start +4)
.byt 5
res_start
+script_5_start
; for
; Init part
.byt SC_ASSIGN, 64, 200	; i=16
.byt 16
; Condition
.byt SC_JUMP_IF, SF_NOT
.byt SF_LT
.byt SF_GETVAL,64, 200	; i
.byt 64, 128
.word 35
; for body
.byt SC_PRINT_AT
.byt 64, 201
.byt 2
.byt 0
.byt SF_GETVAL,64, 200	; i
.byt SC_DELAY
.byt 15
; Increment expression
.byt SC_ASSIGN, 64, 200	; i=i+8
.byt SF_ADD
.byt SF_GETVAL,64, 200	; i
.byt 8
; end for
.byt SC_JUMP, 4, 0	; jump to 4
.byt SC_STOP_SCRIPT
res_end
.)

; Script 6
.(
.byt RESOURCE_SCRIPT
.word (res_end-res_start +4)
.byt 6
res_start
+script_6_start
; for
; Init part
.byt SC_ASSIGN, 64, 200	; i=16
.byt 16
; Condition
.byt SC_JUMP_IF, SF_NOT
.byt SF_LT
.byt SF_GETVAL,64, 200	; i
.byt 64, 128
.word 35
; for body
.byt SC_PRINT_AT
.byt 64, 201
.byt 3
.byt 0
.byt SF_GETVAL,64, 200	; i
.byt SC_DELAY
.byt 15
; Increment expression
.byt SC_ASSIGN, 64, 200	; i=i+8
.byt SF_ADD
.byt SF_GETVAL,64, 200	; i
.byt 8
; end for
.byt SC_JUMP, 4, 0	; jump to 4
.byt SC_SET_EVENTS
.byt 1
.byt SC_STOP_SCRIPT
res_end
.)
