;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Generated by OASIS compiler
; (c) Chema 2016
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


; String pack 100
.(
.byt RESOURCE_STRING
.word (res_end-res_start +4)
.byt 100
res_start
.asc "",125,"Hey! ",125,"Calma!",0 ; String 0
.asc "Odio la violencia personal,",0 ; String 1
.asc "especialmente si yo soy la persona.",0 ; String 2
.asc "",125,"Hola!",0 ; String 3
.asc "",126,"Qui",92,"n eres?",0 ; String 4
.asc "Vila Restal.",0 ; String 5
.asc "Roj Blake. ",126,"Por qu",92," est",91,"s aqu",93,"?",0 ; String 6
.asc "No tuve eleccion.",0 ; String 7
.asc "Robo cosas.",0 ; String 8
.asc "Compulsivo, me temo.",0 ; String 9
.asc "Me ajustaron la cabeza los mejores",0 ; String 10
.asc "del campo.",0 ; String 11
.asc "Pero no se queda ajustada.",0 ; String 12
.asc "",126,"Cu",91,"l es tu historia?",0 ; String 13
.asc "Bueno, soy inocente-- ",0 ; String 14
.asc "al menos de lo que me acusaron.",0 ; String 15
.asc "Claro...",0 ; String 16
.asc "",126,"El resto?",0 ; String 17
.asc "Oh, un grupo muy antisocial. Asesinos,",0 ; String 18
.asc "tramposos,... contrabandistas...",0 ; String 19
.asc "-- ladrones -",0 ; String 20
.asc "-- y esos son los amables.",0 ; String 21
.asc "",126,"Por qu",92," est",91,"s aqu",93,"?",0 ; String 22
.asc "Comerciaba por los Mundos Cercanos.",0 ; String 23
.asc "Soy una comerciante independiente.",0 ; String 24
.asc "Contrabandista. Una de las buenas:",0 ; String 25
.asc "Jenna Stannis. Es un honor estar",0 ; String 26
.asc "preso con ella.",0 ; String 27
.asc "Me alegro de complacerte.",0 ; String 28
.asc "Blake -- Kerr Avon.",0 ; String 29
.asc "Con los ordenadores, es el n",95,"mero",0 ; String 30
.asc "dos de toda la Federaci",94,"n.",0 ; String 31
.asc "",125,"Casi roba 5 millones!",0 ; String 32
.asc "",126,"Qui",92,"n es el n",95,"mero uno?",0 ; String 33
.asc "El que lo pill",94,".",0 ; String 34
.asc "",126,"Qu",92," pas",94,"?",0 ; String 35
.asc "Confi",92," en otra gente.",0 ; String 36
.asc "Blake -- ",92,"l es Olag Gan.",0 ; String 37
.asc "Tuvo un... bueno...",0 ; String 38
.asc "incidente con un guardia.",0 ; String 39
.asc "",125,"No quer",93,"a matarle!",0 ; String 40
.asc "El estaba armado y yo no.",0 ; String 41
.asc "Mat",94," a mi compa",35,"era...",0 ; String 42
.asc "Gan me ha estado cuidando.",0 ; String 43
.asc "Es un amigo leal.",0 ; String 44
.asc "Su fuerza y tus... habilidades",0 ; String 45
.asc "ser",91,"n de mucha ayuda.",0 ; String 46
res_end
.)
