;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Generated by OASIS compiler
; (c) Chema 2016
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


; String pack 0
.(
.byt RESOURCE_STRING
.word (res_end-res_start +4)
.byt 0
res_start
.asc "That doesn't seem to work.",0 ; String 0
.asc "I can't do that.",0 ; String 1
.asc "I don't know what you mean.",0 ; String 2
.asc "What?!",0 ; String 3
.asc "I don't follow your banter.",0 ; String 4
.asc "Look at what?",0 ; String 5
.asc "Ok I'm looking... oh very nice!",0 ; String 6
.asc "What do you want me to look at?",0 ; String 7
.asc "Can't see anything of interest.",0 ; String 8
.asc "Let's avoid unnecessary violence.",0 ; String 9
.asc "Please specify how to use it.",0 ; String 10
res_end
.)
