@ECHO OFF

::
:: Set the build paremeters
::
SET OSDKADDR=$500
SET OSDKNAME=SKELETONF
SET OSDKTAPNAME=SKELETONF
SET OSDKBIN=%OSDK%\bin

SET OSDKFILE=SKELETONF drawSKELETONF SKELETONF00 SKELETONF01 SKELETONF02 SKELETONF03 SKELETONF04 SKELETONF05 SKELETONF06 SKELETONF07 SKELETONF08 SKELETONF09 SKELETONF10 SKELETONF11 SKELETONF12 SKELETONF13 SKELETONF14   
